// Generated by api-types-codegen. Do not edit by hand.

pub mod routes {
    use crate::{GatewayClient, Result, RouteDescriptor};

    pub const PUT_ARTIFACTS_BY_ID_MEDIA: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Put,
        path: "/api/artifacts/{id}/media",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ArtifactIdParams"),
        query: None,
        body: Some("api_types::ArtifactMediaUpdateRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const GET_ARTIFACTS_BY_ID_MEDIA_BY_INDEX: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/artifacts/{id}/media/{index}",
        transport: api_types::RouteTransport::Static,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ArtifactMediaParams"),
        query: None,
        body: None,
        response: None,
        event: None,
    };

    pub const POST_CAPTAIN_ADOPT: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/captain/adopt",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::AdoptRequest"),
        response: Some("api_types::TaskCreateResponse"),
        event: None,
    };

    pub const POST_CAPTAIN_NUDGE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/captain/nudge",
        transport: api_types::RouteTransport::Multipart,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::NudgeRequest"),
        response: Some("api_types::NudgeResponse"),
        event: None,
    };

    pub const POST_CAPTAIN_STOP: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/captain/stop",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::StopWorkersResponse"),
        event: None,
    };

    pub const POST_CAPTAIN_TICK: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/captain/tick",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TickRequest"),
        response: Some("api_types::TickDrainResult"),
        event: None,
    };

    pub const POST_CAPTAIN_TRIAGE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/captain/triage",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TriageRequest"),
        response: Some("api_types::TriageResponse"),
        event: None,
    };

    pub const GET_CHANNELS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/channels",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::ChannelsResponse"),
        event: None,
    };

    pub const POST_CHANNELS_TELEGRAM_OWNER: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/channels/telegram/owner",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TelegramOwnerRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_CLIENTLOGS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/client-logs",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ClientLogBatchRequest"),
        response: Some("api_types::ClientLogBatchResponse"),
        event: None,
    };

    pub const GET_CONFIG: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/config",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::MandoConfig"),
        event: None,
    };

    pub const PUT_CONFIG: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Put,
        path: "/api/config",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::MandoConfig"),
        response: Some("api_types::ConfigWriteResponse"),
        event: None,
    };

    pub const POST_CONFIG_SETUP: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/config/setup",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ConfigSetupRequest"),
        response: Some("api_types::ConfigSetupResponse"),
        event: None,
    };

    pub const GET_CONFIG_STATUS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/config/status",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::ConfigStatusResponse"),
        event: None,
    };

    pub const GET_CREDENTIALS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/credentials",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::CredentialsListResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::AddCodexCredentialRequest"),
        response: Some("api_types::AddCodexCredentialResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX_APP_RESTORE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex/app/restore",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::CodexDesktopAppRestoreRequest"),
        response: Some("api_types::CodexDesktopAppOperationResponse"),
        event: None,
    };

    pub const GET_CREDENTIALS_CODEX_APP_STATUS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/credentials/codex/app/status",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: Some("api_types::CodexDesktopAppStatusQuery"),
        body: None,
        response: Some("api_types::CodexDesktopAppStatusResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX_APP_USE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex/app/use",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::CodexDesktopAppUseRequest"),
        response: Some("api_types::CodexDesktopAppOperationResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX_LOGIN_CANCEL: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex/login/cancel",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::CancelCodexLoginResponse"),
        event: None,
    };

    pub const GET_CREDENTIALS_CODEX_LOGIN_CURRENT: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/credentials/codex/login/current",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::CodexLoginStatusResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX_LOGIN_START: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex/login/start",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::StartCodexLoginRequest"),
        response: Some("api_types::StartCodexLoginResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX_PICK: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex/pick",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::CredentialPickRequest"),
        response: Some("api_types::CodexCredentialPickResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX_SYNC: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex/sync",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::SyncCodexCredentialRequest"),
        response: Some("api_types::SyncCodexCredentialResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_CODEX_BY_ID_AUTH: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/codex/{id}/auth",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: Some("api_types::UpdateCodexCredentialAuthRequest"),
        response: Some("api_types::AddCodexCredentialResponse"),
        event: None,
    };

    pub const GET_CREDENTIALS_CODEX_BY_ID_RESETCREDITS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/credentials/codex/{id}/reset-credits",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: None,
        response: Some("api_types::CodexResetCreditsResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_PICK: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/pick",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::CredentialPickRequest"),
        response: Some("api_types::CredentialPickResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_SETUPTOKEN: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/setup-token",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::SetupTokenRequest"),
        response: Some("api_types::SetupTokenResponse"),
        event: None,
    };

    pub const DELETE_CREDENTIALS_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Delete,
        path: "/api/credentials/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: None,
        response: Some("api_types::CredentialMutationResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_BY_ID_DISABLE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/{id}/disable",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::CredentialMutationResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_BY_ID_ENABLE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/{id}/enable",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::CredentialMutationResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_BY_ID_PROBE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/{id}/probe",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::ProbeCredentialResponse"),
        event: None,
    };

    pub const GET_CREDENTIALS_BY_ID_TOKEN: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/credentials/{id}/token",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: None,
        response: Some("api_types::CredentialTokenResponse"),
        event: None,
    };

    pub const POST_CREDENTIALS_BY_ID_TOKEN: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/credentials/{id}/token",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::CredentialIdParams"),
        query: None,
        body: Some("api_types::UpdateCredentialTokenRequest"),
        response: Some("api_types::UpdateCredentialTokenResponse"),
        event: None,
    };

    pub const GET_EVENTS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/events",
        transport: api_types::RouteTransport::Sse,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: None,
        event: Some("api_types::SseEnvelope"),
    };

    pub const POST_FIRECRAWL_SCRAPE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/firecrawl/scrape",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::FirecrawlScrapeRequest"),
        response: Some("api_types::FirecrawlScrapeResponse"),
        event: None,
    };

    pub const GET_GITHUB_ATTACHMENTS_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/github/attachments/{id}",
        transport: api_types::RouteTransport::Static,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::GitHubUserAttachmentParams"),
        query: None,
        body: None,
        response: None,
        event: None,
    };

    pub const GET_HEALTH: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/health",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Public,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::HealthResponse"),
        event: None,
    };

    pub const GET_HEALTH_SYSTEM: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/health/system",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::SystemHealthResponse"),
        event: None,
    };

    pub const GET_HEALTH_TELEGRAM: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/health/telegram",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::TelegramHealth"),
        event: None,
    };

    pub const GET_IMAGES_BY_FILENAME: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/images/{filename}",
        transport: api_types::RouteTransport::Static,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ImageFilenameParams"),
        query: None,
        body: None,
        response: None,
        event: None,
    };

    pub const POST_NOTIFY: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/notify",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::NotifyRequest"),
        response: Some("api_types::NotifyResponse"),
        event: None,
    };

    pub const GET_PROJECTS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/projects",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::ProjectsListResponse"),
        event: None,
    };

    pub const POST_PROJECTS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/projects",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::AddProjectRequest"),
        response: Some("api_types::ProjectUpsertResponse"),
        event: None,
    };

    pub const DELETE_PROJECTS_BY_NAME: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Delete,
        path: "/api/projects/{name}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ProjectNameParams"),
        query: None,
        body: None,
        response: Some("api_types::ProjectDeleteResponse"),
        event: None,
    };

    pub const PATCH_PROJECTS_BY_NAME: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Patch,
        path: "/api/projects/{name}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ProjectNameParams"),
        query: None,
        body: Some("api_types::EditProjectRequest"),
        response: Some("api_types::ProjectUpsertResponse"),
        event: None,
    };

    pub const POST_SCOUT_ASK: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/ask",
        transport: api_types::RouteTransport::Multipart,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ScoutAskRequest"),
        response: Some("api_types::AskResponse"),
        event: None,
    };

    pub const POST_SCOUT_BULK: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/bulk",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ScoutBulkCommandRequest"),
        response: Some("api_types::ScoutBulkUpdateResponse"),
        event: None,
    };

    pub const POST_SCOUT_BULKDELETE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/bulk-delete",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ScoutBulkDeleteRequest"),
        response: Some("api_types::ScoutBulkDeleteResponse"),
        event: None,
    };

    pub const GET_SCOUT_ITEMS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/scout/items",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: Some("api_types::ScoutQuery"),
        body: None,
        response: Some("api_types::ScoutResponse"),
        event: None,
    };

    pub const POST_SCOUT_ITEMS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/items",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ScoutAddRequest"),
        response: Some("api_types::ScoutAddResponse"),
        event: None,
    };

    pub const DELETE_SCOUT_ITEMS_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Delete,
        path: "/api/scout/items/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutItemIdParams"),
        query: None,
        body: None,
        response: Some("api_types::ScoutDeleteResponse"),
        event: None,
    };

    pub const GET_SCOUT_ITEMS_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/scout/items/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutItemIdParams"),
        query: None,
        body: None,
        response: Some("api_types::ScoutItem"),
        event: None,
    };

    pub const PATCH_SCOUT_ITEMS_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Patch,
        path: "/api/scout/items/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutItemIdParams"),
        query: None,
        body: Some("api_types::ScoutLifecycleCommandRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_SCOUT_ITEMS_BY_ID_ACT: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/items/{id}/act",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutItemIdParams"),
        query: None,
        body: Some("api_types::ScoutActRequest"),
        response: Some("api_types::ActResponse"),
        event: None,
    };

    pub const GET_SCOUT_ITEMS_BY_ID_ARTICLE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/scout/items/{id}/article",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutItemIdParams"),
        query: None,
        body: None,
        response: Some("api_types::ScoutArticleResponse"),
        event: None,
    };

    pub const GET_SCOUT_ITEMS_BY_ID_SESSIONS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/scout/items/{id}/sessions",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutItemIdParams"),
        query: None,
        body: None,
        response: Some("Vec<api_types::ScoutItemSession>"),
        event: None,
    };

    pub const POST_SCOUT_ITEMS_BY_ID_TELEGRAPH: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/items/{id}/telegraph",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutItemIdParams"),
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::TelegraphPublishResponse"),
        event: None,
    };

    pub const POST_SCOUT_PROCESS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/process",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ScoutProcessRequest"),
        response: Some("api_types::ProcessResponse"),
        event: None,
    };

    pub const GET_SCOUT_RESEARCH: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/scout/research",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("Vec<api_types::ScoutResearchRun>"),
        event: None,
    };

    pub const POST_SCOUT_RESEARCH: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/scout/research",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::ScoutResearchRequest"),
        response: Some("api_types::ResearchStartResponse"),
        event: None,
    };

    pub const GET_SCOUT_RESEARCH_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/scout/research/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutResearchIdParams"),
        query: None,
        body: None,
        response: Some("api_types::ScoutResearchRun"),
        event: None,
    };

    pub const GET_SCOUT_RESEARCH_BY_ID_ITEMS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/scout/research/{id}/items",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::ScoutResearchIdParams"),
        query: None,
        body: None,
        response: Some("Vec<api_types::ScoutItem>"),
        event: None,
    };

    pub const GET_SESSIONS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: Some("api_types::SessionsQuery"),
        body: None,
        response: Some("api_types::SessionsListResponse"),
        event: None,
    };

    pub const GET_SESSIONS_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: None,
        body: None,
        response: Some("api_types::SessionEntry"),
        event: None,
    };

    pub const GET_SESSIONS_BY_ID_COST: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/cost",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: None,
        body: None,
        response: Some("api_types::SessionCostResponse"),
        event: None,
    };

    pub const GET_SESSIONS_BY_ID_EVENTS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/events",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: None,
        body: None,
        response: Some("api_types::TranscriptEventsResponse"),
        event: None,
    };

    pub const GET_SESSIONS_BY_ID_EVENTS_STREAM: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/events/stream",
        transport: api_types::RouteTransport::Sse,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: None,
        body: None,
        response: None,
        event: Some("api_types::TranscriptEventEnvelope"),
    };

    pub const GET_SESSIONS_BY_ID_IMAGES_BY_TOOL_BY_INDEX: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/images/{tool}/{index}",
        transport: api_types::RouteTransport::Static,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionToolResultImageParams"),
        query: None,
        body: None,
        response: None,
        event: None,
    };

    pub const GET_SESSIONS_BY_ID_JSONLPATH: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/jsonl-path",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: None,
        body: None,
        response: Some("api_types::SessionJsonlPathResponse"),
        event: None,
    };

    pub const GET_SESSIONS_BY_ID_MESSAGES: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/messages",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: Some("api_types::SessionMessagesQuery"),
        body: None,
        response: Some("api_types::SessionMessagesResponse"),
        event: None,
    };

    pub const GET_SESSIONS_BY_ID_STREAM: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/stream",
        transport: api_types::RouteTransport::Ndjson,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: Some("api_types::SessionStreamQuery"),
        body: None,
        response: None,
        event: None,
    };

    pub const GET_SESSIONS_BY_ID_TOOLS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/sessions/{id}/tools",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::SessionIdParams"),
        query: None,
        body: None,
        response: Some("api_types::SessionToolUsageResponse"),
        event: None,
    };

    pub const GET_STATS_ACTIVITY: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/stats/activity",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::ActivityStatsResponse"),
        event: None,
    };

    pub const DELETE_TASKS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Delete,
        path: "/api/tasks",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskDeleteRequest"),
        response: Some("api_types::DeleteTasksResponse"),
        event: None,
    };

    pub const GET_TASKS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/tasks",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: Some("api_types::TaskListQuery"),
        body: None,
        response: Some("api_types::TaskListResponse"),
        event: None,
    };

    pub const POST_TASKS_ACCEPT: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/accept",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskIdRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_ADD: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/add",
        transport: api_types::RouteTransport::Multipart,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskAddRequest"),
        response: Some("api_types::TaskItem"),
        event: None,
    };

    pub const POST_TASKS_BULK: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/bulk",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskBulkUpdateRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_CANCEL: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/cancel",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskIdRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_DELETE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/delete",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskDeleteRequest"),
        response: Some("api_types::DeleteTasksResponse"),
        event: None,
    };

    pub const POST_TASKS_HANDOFF: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/handoff",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskIdRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_MERGE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/merge",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::MergeRequest"),
        response: Some("api_types::MergeResponse"),
        event: None,
    };

    pub const POST_TASKS_REOPEN: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/reopen",
        transport: api_types::RouteTransport::Multipart,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskFeedbackRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_RESUMERATELIMITED: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/resume-rate-limited",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskIdRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_RETRY: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/retry",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskIdRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_REWORK: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/rework",
        transport: api_types::RouteTransport::Multipart,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskFeedbackRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_TASKS_STOP: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/stop",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::TaskIdRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const PATCH_TASKS_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Patch,
        path: "/api/tasks/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: None,
        body: Some("api_types::TaskPatchRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const GET_TASKS_BY_ID_ARTIFACTS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/tasks/{id}/artifacts",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: None,
        body: None,
        response: Some("api_types::ArtifactsResponse"),
        event: None,
    };

    pub const POST_TASKS_BY_ID_CLARIFY: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/{id}/clarify",
        transport: api_types::RouteTransport::Multipart,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: Some("api_types::ClarifyQuery"),
        body: Some("api_types::ClarifyRequest"),
        response: Some("api_types::ClarifyResponse"),
        event: None,
    };

    pub const POST_TASKS_BY_ID_EVIDENCE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/{id}/evidence",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: None,
        body: Some("api_types::TaskEvidenceRequest"),
        response: Some("api_types::TaskEvidenceResponse"),
        event: None,
    };

    pub const GET_TASKS_BY_ID_FEED: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/tasks/{id}/feed",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: None,
        body: None,
        response: Some("api_types::FeedResponse"),
        event: None,
    };

    pub const GET_TASKS_BY_ID_PRSUMMARY: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/tasks/{id}/pr-summary",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: None,
        body: None,
        response: Some("api_types::PrSummaryResponse"),
        event: None,
    };

    pub const GET_TASKS_BY_ID_SESSIONS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/tasks/{id}/sessions",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: Some("api_types::SessionsQuery"),
        body: None,
        response: Some("api_types::ItemSessionsResponse"),
        event: None,
    };

    pub const POST_TASKS_BY_ID_SUMMARY: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/tasks/{id}/summary",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: None,
        body: Some("api_types::TaskSummaryRequest"),
        response: Some("api_types::TaskSummaryResponse"),
        event: None,
    };

    pub const GET_TASKS_BY_ID_TIMELINE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/tasks/{id}/timeline",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::TaskIdParams"),
        query: None,
        body: None,
        response: Some("api_types::TimelineResponse"),
        event: None,
    };

    pub const POST_UI_LAUNCH: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/ui/launch",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_UI_QUITTING: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/ui/quitting",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_UI_REGISTER: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/ui/register",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::UiRegisterRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_UI_RESTART: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/ui/restart",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const POST_UI_UPDATING: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/ui/updating",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    pub const GET_WORKBENCHES: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/workbenches",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: Some("api_types::WorkbenchListQuery"),
        body: None,
        response: Some("api_types::WorkbenchesResponse"),
        event: None,
    };

    pub const PATCH_WORKBENCHES_BY_ID: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Patch,
        path: "/api/workbenches/{id}",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: Some("api_types::WorkbenchIdParams"),
        query: None,
        body: Some("api_types::WorkbenchPatchRequest"),
        response: Some("api_types::WorkbenchItem"),
        event: None,
    };

    pub const GET_WORKERS: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/workers",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::WorkersResponse"),
        event: None,
    };

    pub const GET_WORKTREES: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Get,
        path: "/api/worktrees",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: None,
        response: Some("api_types::WorktreeListResponse"),
        event: None,
    };

    pub const POST_WORKTREES: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/worktrees",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::CreateWorktreeRequest"),
        response: Some("api_types::CreateWorktreeResponse"),
        event: None,
    };

    pub const POST_WORKTREES_CLEANUP: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/worktrees/cleanup",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::WorktreeCleanupRequest"),
        response: Some("api_types::WorktreeCleanupResponse"),
        event: None,
    };

    pub const POST_WORKTREES_PRUNE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/worktrees/prune",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::EmptyRequest"),
        response: Some("api_types::WorktreePruneResponse"),
        event: None,
    };

    pub const POST_WORKTREES_REMOVE: RouteDescriptor = RouteDescriptor {
        method: api_types::RouteMethod::Post,
        path: "/api/worktrees/remove",
        transport: api_types::RouteTransport::Json,
        auth: api_types::RouteAuth::Protected,
        params: None,
        query: None,
        body: Some("api_types::RemoveWorktreeRequest"),
        response: Some("api_types::BoolOkResponse"),
        event: None,
    };

    impl GatewayClient {
        pub async fn put_artifacts_by_id_media(
            &self,
            params: &api_types::ArtifactIdParams,
            body: &api_types::ArtifactMediaUpdateRequest,
        ) -> Result<api_types::BoolOkResponse> {
            let path = crate::http::render_path(
                &PUT_ARTIFACTS_BY_ID_MEDIA,
                &[("id", params.id.to_string())],
            );
            self.put_json(&PUT_ARTIFACTS_BY_ID_MEDIA, &path, body).await
        }

        pub async fn get_artifacts_by_id_media_by_index(
            &self,
            params: &api_types::ArtifactMediaParams,
        ) -> Result<Vec<u8>> {
            let path = crate::http::render_path(
                &GET_ARTIFACTS_BY_ID_MEDIA_BY_INDEX,
                &[
                    ("id", params.id.to_string()),
                    ("index", params.index.to_string()),
                ],
            );
            self.get_bytes(&GET_ARTIFACTS_BY_ID_MEDIA_BY_INDEX, &path)
                .await
        }

        pub async fn post_captain_adopt(
            &self,
            body: &api_types::AdoptRequest,
        ) -> Result<api_types::TaskCreateResponse> {
            self.post_json(&POST_CAPTAIN_ADOPT, POST_CAPTAIN_ADOPT.path, body)
                .await
        }

        pub async fn post_captain_nudge_multipart(
            &self,
            form: reqwest::multipart::Form,
        ) -> Result<api_types::NudgeResponse> {
            self.post_multipart(&POST_CAPTAIN_NUDGE, POST_CAPTAIN_NUDGE.path, form)
                .await
        }

        pub async fn post_captain_nudge(
            &self,
            body: &api_types::NudgeRequest,
        ) -> Result<api_types::NudgeResponse> {
            self.post_json(&POST_CAPTAIN_NUDGE, POST_CAPTAIN_NUDGE.path, body)
                .await
        }

        pub async fn post_captain_stop(&self) -> Result<api_types::StopWorkersResponse> {
            self.post_json(
                &POST_CAPTAIN_STOP,
                POST_CAPTAIN_STOP.path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_captain_tick(
            &self,
            body: &api_types::TickRequest,
        ) -> Result<api_types::TickDrainResult> {
            self.post_json(&POST_CAPTAIN_TICK, POST_CAPTAIN_TICK.path, body)
                .await
        }

        pub async fn post_captain_triage(
            &self,
            body: &api_types::TriageRequest,
        ) -> Result<api_types::TriageResponse> {
            self.post_json(&POST_CAPTAIN_TRIAGE, POST_CAPTAIN_TRIAGE.path, body)
                .await
        }

        pub async fn get_channels(&self) -> Result<api_types::ChannelsResponse> {
            self.get_json(&GET_CHANNELS, GET_CHANNELS.path).await
        }

        pub async fn post_channels_telegram_owner(
            &self,
            body: &api_types::TelegramOwnerRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(
                &POST_CHANNELS_TELEGRAM_OWNER,
                POST_CHANNELS_TELEGRAM_OWNER.path,
                body,
            )
            .await
        }

        pub async fn post_clientlogs(
            &self,
            body: &api_types::ClientLogBatchRequest,
        ) -> Result<api_types::ClientLogBatchResponse> {
            self.post_json(&POST_CLIENTLOGS, POST_CLIENTLOGS.path, body)
                .await
        }

        pub async fn get_config(&self) -> Result<api_types::MandoConfig> {
            self.get_json(&GET_CONFIG, GET_CONFIG.path).await
        }

        pub async fn put_config(
            &self,
            body: &api_types::MandoConfig,
        ) -> Result<api_types::ConfigWriteResponse> {
            self.put_json(&PUT_CONFIG, PUT_CONFIG.path, body).await
        }

        pub async fn post_config_setup(
            &self,
            body: &api_types::ConfigSetupRequest,
        ) -> Result<api_types::ConfigSetupResponse> {
            self.post_json(&POST_CONFIG_SETUP, POST_CONFIG_SETUP.path, body)
                .await
        }

        pub async fn get_config_status(&self) -> Result<api_types::ConfigStatusResponse> {
            self.get_json(&GET_CONFIG_STATUS, GET_CONFIG_STATUS.path)
                .await
        }

        pub async fn get_credentials(&self) -> Result<api_types::CredentialsListResponse> {
            self.get_json(&GET_CREDENTIALS, GET_CREDENTIALS.path).await
        }

        pub async fn post_credentials_codex(
            &self,
            body: &api_types::AddCodexCredentialRequest,
        ) -> Result<api_types::AddCodexCredentialResponse> {
            self.post_json(&POST_CREDENTIALS_CODEX, POST_CREDENTIALS_CODEX.path, body)
                .await
        }

        pub async fn post_credentials_codex_app_restore(
            &self,
            body: &api_types::CodexDesktopAppRestoreRequest,
        ) -> Result<api_types::CodexDesktopAppOperationResponse> {
            self.post_json(
                &POST_CREDENTIALS_CODEX_APP_RESTORE,
                POST_CREDENTIALS_CODEX_APP_RESTORE.path,
                body,
            )
            .await
        }

        pub async fn get_credentials_codex_app_status(
            &self,
            query: &api_types::CodexDesktopAppStatusQuery,
        ) -> Result<api_types::CodexDesktopAppStatusResponse> {
            self.get_json_query(
                &GET_CREDENTIALS_CODEX_APP_STATUS,
                GET_CREDENTIALS_CODEX_APP_STATUS.path,
                query,
            )
            .await
        }

        pub async fn post_credentials_codex_app_use(
            &self,
            body: &api_types::CodexDesktopAppUseRequest,
        ) -> Result<api_types::CodexDesktopAppOperationResponse> {
            self.post_json(
                &POST_CREDENTIALS_CODEX_APP_USE,
                POST_CREDENTIALS_CODEX_APP_USE.path,
                body,
            )
            .await
        }

        pub async fn post_credentials_codex_login_cancel(
            &self,
        ) -> Result<api_types::CancelCodexLoginResponse> {
            self.post_json(
                &POST_CREDENTIALS_CODEX_LOGIN_CANCEL,
                POST_CREDENTIALS_CODEX_LOGIN_CANCEL.path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn get_credentials_codex_login_current(
            &self,
        ) -> Result<api_types::CodexLoginStatusResponse> {
            self.get_json(
                &GET_CREDENTIALS_CODEX_LOGIN_CURRENT,
                GET_CREDENTIALS_CODEX_LOGIN_CURRENT.path,
            )
            .await
        }

        pub async fn post_credentials_codex_login_start(
            &self,
            body: &api_types::StartCodexLoginRequest,
        ) -> Result<api_types::StartCodexLoginResponse> {
            self.post_json(
                &POST_CREDENTIALS_CODEX_LOGIN_START,
                POST_CREDENTIALS_CODEX_LOGIN_START.path,
                body,
            )
            .await
        }

        pub async fn post_credentials_codex_pick(
            &self,
            body: &api_types::CredentialPickRequest,
        ) -> Result<api_types::CodexCredentialPickResponse> {
            self.post_json(
                &POST_CREDENTIALS_CODEX_PICK,
                POST_CREDENTIALS_CODEX_PICK.path,
                body,
            )
            .await
        }

        pub async fn post_credentials_codex_sync(
            &self,
            body: &api_types::SyncCodexCredentialRequest,
        ) -> Result<api_types::SyncCodexCredentialResponse> {
            self.post_json(
                &POST_CREDENTIALS_CODEX_SYNC,
                POST_CREDENTIALS_CODEX_SYNC.path,
                body,
            )
            .await
        }

        pub async fn post_credentials_codex_by_id_auth(
            &self,
            params: &api_types::CredentialIdParams,
            body: &api_types::UpdateCodexCredentialAuthRequest,
        ) -> Result<api_types::AddCodexCredentialResponse> {
            let path = crate::http::render_path(
                &POST_CREDENTIALS_CODEX_BY_ID_AUTH,
                &[("id", params.id.to_string())],
            );
            self.post_json(&POST_CREDENTIALS_CODEX_BY_ID_AUTH, &path, body)
                .await
        }

        pub async fn get_credentials_codex_by_id_resetcredits(
            &self,
            params: &api_types::CredentialIdParams,
        ) -> Result<api_types::CodexResetCreditsResponse> {
            let path = crate::http::render_path(
                &GET_CREDENTIALS_CODEX_BY_ID_RESETCREDITS,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_CREDENTIALS_CODEX_BY_ID_RESETCREDITS, &path)
                .await
        }

        pub async fn post_credentials_pick(
            &self,
            body: &api_types::CredentialPickRequest,
        ) -> Result<api_types::CredentialPickResponse> {
            self.post_json(&POST_CREDENTIALS_PICK, POST_CREDENTIALS_PICK.path, body)
                .await
        }

        pub async fn post_credentials_setuptoken(
            &self,
            body: &api_types::SetupTokenRequest,
        ) -> Result<api_types::SetupTokenResponse> {
            self.post_json(
                &POST_CREDENTIALS_SETUPTOKEN,
                POST_CREDENTIALS_SETUPTOKEN.path,
                body,
            )
            .await
        }

        pub async fn delete_credentials_by_id(
            &self,
            params: &api_types::CredentialIdParams,
        ) -> Result<api_types::CredentialMutationResponse> {
            let path = crate::http::render_path(
                &DELETE_CREDENTIALS_BY_ID,
                &[("id", params.id.to_string())],
            );
            self.delete_json(&DELETE_CREDENTIALS_BY_ID, &path).await
        }

        pub async fn post_credentials_by_id_disable(
            &self,
            params: &api_types::CredentialIdParams,
        ) -> Result<api_types::CredentialMutationResponse> {
            let path = crate::http::render_path(
                &POST_CREDENTIALS_BY_ID_DISABLE,
                &[("id", params.id.to_string())],
            );
            self.post_json(
                &POST_CREDENTIALS_BY_ID_DISABLE,
                &path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_credentials_by_id_enable(
            &self,
            params: &api_types::CredentialIdParams,
        ) -> Result<api_types::CredentialMutationResponse> {
            let path = crate::http::render_path(
                &POST_CREDENTIALS_BY_ID_ENABLE,
                &[("id", params.id.to_string())],
            );
            self.post_json(
                &POST_CREDENTIALS_BY_ID_ENABLE,
                &path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_credentials_by_id_probe(
            &self,
            params: &api_types::CredentialIdParams,
        ) -> Result<api_types::ProbeCredentialResponse> {
            let path = crate::http::render_path(
                &POST_CREDENTIALS_BY_ID_PROBE,
                &[("id", params.id.to_string())],
            );
            self.post_json(
                &POST_CREDENTIALS_BY_ID_PROBE,
                &path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn get_credentials_by_id_token(
            &self,
            params: &api_types::CredentialIdParams,
        ) -> Result<api_types::CredentialTokenResponse> {
            let path = crate::http::render_path(
                &GET_CREDENTIALS_BY_ID_TOKEN,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_CREDENTIALS_BY_ID_TOKEN, &path).await
        }

        pub async fn post_credentials_by_id_token(
            &self,
            params: &api_types::CredentialIdParams,
            body: &api_types::UpdateCredentialTokenRequest,
        ) -> Result<api_types::UpdateCredentialTokenResponse> {
            let path = crate::http::render_path(
                &POST_CREDENTIALS_BY_ID_TOKEN,
                &[("id", params.id.to_string())],
            );
            self.post_json(&POST_CREDENTIALS_BY_ID_TOKEN, &path, body)
                .await
        }

        pub async fn post_firecrawl_scrape(
            &self,
            body: &api_types::FirecrawlScrapeRequest,
        ) -> Result<api_types::FirecrawlScrapeResponse> {
            self.post_json(&POST_FIRECRAWL_SCRAPE, POST_FIRECRAWL_SCRAPE.path, body)
                .await
        }

        pub async fn get_github_attachments_by_id(
            &self,
            params: &api_types::GitHubUserAttachmentParams,
        ) -> Result<Vec<u8>> {
            let path = crate::http::render_path(
                &GET_GITHUB_ATTACHMENTS_BY_ID,
                &[("id", params.id.to_string())],
            );
            self.get_bytes(&GET_GITHUB_ATTACHMENTS_BY_ID, &path).await
        }

        pub async fn get_health(&self) -> Result<api_types::HealthResponse> {
            self.get_json(&GET_HEALTH, GET_HEALTH.path).await
        }

        pub async fn get_health_system(&self) -> Result<api_types::SystemHealthResponse> {
            self.get_json(&GET_HEALTH_SYSTEM, GET_HEALTH_SYSTEM.path)
                .await
        }

        pub async fn get_health_telegram(&self) -> Result<api_types::TelegramHealth> {
            self.get_json(&GET_HEALTH_TELEGRAM, GET_HEALTH_TELEGRAM.path)
                .await
        }

        pub async fn get_images_by_filename(
            &self,
            params: &api_types::ImageFilenameParams,
        ) -> Result<Vec<u8>> {
            let path = crate::http::render_path(
                &GET_IMAGES_BY_FILENAME,
                &[("filename", params.filename.to_string())],
            );
            self.get_bytes(&GET_IMAGES_BY_FILENAME, &path).await
        }

        pub async fn post_notify(
            &self,
            body: &api_types::NotifyRequest,
        ) -> Result<api_types::NotifyResponse> {
            self.post_json(&POST_NOTIFY, POST_NOTIFY.path, body).await
        }

        pub async fn get_projects(&self) -> Result<api_types::ProjectsListResponse> {
            self.get_json(&GET_PROJECTS, GET_PROJECTS.path).await
        }

        pub async fn post_projects(
            &self,
            body: &api_types::AddProjectRequest,
        ) -> Result<api_types::ProjectUpsertResponse> {
            self.post_json(&POST_PROJECTS, POST_PROJECTS.path, body)
                .await
        }

        pub async fn delete_projects_by_name(
            &self,
            params: &api_types::ProjectNameParams,
        ) -> Result<api_types::ProjectDeleteResponse> {
            let path = crate::http::render_path(
                &DELETE_PROJECTS_BY_NAME,
                &[("name", params.name.to_string())],
            );
            self.delete_json(&DELETE_PROJECTS_BY_NAME, &path).await
        }

        pub async fn patch_projects_by_name(
            &self,
            params: &api_types::ProjectNameParams,
            body: &api_types::EditProjectRequest,
        ) -> Result<api_types::ProjectUpsertResponse> {
            let path = crate::http::render_path(
                &PATCH_PROJECTS_BY_NAME,
                &[("name", params.name.to_string())],
            );
            self.patch_json(&PATCH_PROJECTS_BY_NAME, &path, body).await
        }

        pub async fn post_scout_ask_multipart(
            &self,
            form: reqwest::multipart::Form,
        ) -> Result<api_types::AskResponse> {
            self.post_multipart(&POST_SCOUT_ASK, POST_SCOUT_ASK.path, form)
                .await
        }

        pub async fn post_scout_ask(
            &self,
            body: &api_types::ScoutAskRequest,
        ) -> Result<api_types::AskResponse> {
            self.post_json(&POST_SCOUT_ASK, POST_SCOUT_ASK.path, body)
                .await
        }

        pub async fn post_scout_bulk(
            &self,
            body: &api_types::ScoutBulkCommandRequest,
        ) -> Result<api_types::ScoutBulkUpdateResponse> {
            self.post_json(&POST_SCOUT_BULK, POST_SCOUT_BULK.path, body)
                .await
        }

        pub async fn post_scout_bulkdelete(
            &self,
            body: &api_types::ScoutBulkDeleteRequest,
        ) -> Result<api_types::ScoutBulkDeleteResponse> {
            self.post_json(&POST_SCOUT_BULKDELETE, POST_SCOUT_BULKDELETE.path, body)
                .await
        }

        pub async fn get_scout_items(
            &self,
            query: &api_types::ScoutQuery,
        ) -> Result<api_types::ScoutResponse> {
            self.get_json_query(&GET_SCOUT_ITEMS, GET_SCOUT_ITEMS.path, query)
                .await
        }

        pub async fn post_scout_items(
            &self,
            body: &api_types::ScoutAddRequest,
        ) -> Result<api_types::ScoutAddResponse> {
            self.post_json(&POST_SCOUT_ITEMS, POST_SCOUT_ITEMS.path, body)
                .await
        }

        pub async fn delete_scout_items_by_id(
            &self,
            params: &api_types::ScoutItemIdParams,
        ) -> Result<api_types::ScoutDeleteResponse> {
            let path = crate::http::render_path(
                &DELETE_SCOUT_ITEMS_BY_ID,
                &[("id", params.id.to_string())],
            );
            self.delete_json(&DELETE_SCOUT_ITEMS_BY_ID, &path).await
        }

        pub async fn get_scout_items_by_id(
            &self,
            params: &api_types::ScoutItemIdParams,
        ) -> Result<api_types::ScoutItem> {
            let path =
                crate::http::render_path(&GET_SCOUT_ITEMS_BY_ID, &[("id", params.id.to_string())]);
            self.get_json(&GET_SCOUT_ITEMS_BY_ID, &path).await
        }

        pub async fn patch_scout_items_by_id(
            &self,
            params: &api_types::ScoutItemIdParams,
            body: &api_types::ScoutLifecycleCommandRequest,
        ) -> Result<api_types::BoolOkResponse> {
            let path = crate::http::render_path(
                &PATCH_SCOUT_ITEMS_BY_ID,
                &[("id", params.id.to_string())],
            );
            self.patch_json(&PATCH_SCOUT_ITEMS_BY_ID, &path, body).await
        }

        pub async fn post_scout_items_by_id_act(
            &self,
            params: &api_types::ScoutItemIdParams,
            body: &api_types::ScoutActRequest,
        ) -> Result<api_types::ActResponse> {
            let path = crate::http::render_path(
                &POST_SCOUT_ITEMS_BY_ID_ACT,
                &[("id", params.id.to_string())],
            );
            self.post_json(&POST_SCOUT_ITEMS_BY_ID_ACT, &path, body)
                .await
        }

        pub async fn get_scout_items_by_id_article(
            &self,
            params: &api_types::ScoutItemIdParams,
        ) -> Result<api_types::ScoutArticleResponse> {
            let path = crate::http::render_path(
                &GET_SCOUT_ITEMS_BY_ID_ARTICLE,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SCOUT_ITEMS_BY_ID_ARTICLE, &path).await
        }

        pub async fn get_scout_items_by_id_sessions(
            &self,
            params: &api_types::ScoutItemIdParams,
        ) -> Result<Vec<api_types::ScoutItemSession>> {
            let path = crate::http::render_path(
                &GET_SCOUT_ITEMS_BY_ID_SESSIONS,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SCOUT_ITEMS_BY_ID_SESSIONS, &path).await
        }

        pub async fn post_scout_items_by_id_telegraph(
            &self,
            params: &api_types::ScoutItemIdParams,
        ) -> Result<api_types::TelegraphPublishResponse> {
            let path = crate::http::render_path(
                &POST_SCOUT_ITEMS_BY_ID_TELEGRAPH,
                &[("id", params.id.to_string())],
            );
            self.post_json(
                &POST_SCOUT_ITEMS_BY_ID_TELEGRAPH,
                &path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_scout_process(
            &self,
            body: &api_types::ScoutProcessRequest,
        ) -> Result<api_types::ProcessResponse> {
            self.post_json(&POST_SCOUT_PROCESS, POST_SCOUT_PROCESS.path, body)
                .await
        }

        pub async fn get_scout_research(&self) -> Result<Vec<api_types::ScoutResearchRun>> {
            self.get_json(&GET_SCOUT_RESEARCH, GET_SCOUT_RESEARCH.path)
                .await
        }

        pub async fn post_scout_research(
            &self,
            body: &api_types::ScoutResearchRequest,
        ) -> Result<api_types::ResearchStartResponse> {
            self.post_json(&POST_SCOUT_RESEARCH, POST_SCOUT_RESEARCH.path, body)
                .await
        }

        pub async fn get_scout_research_by_id(
            &self,
            params: &api_types::ScoutResearchIdParams,
        ) -> Result<api_types::ScoutResearchRun> {
            let path = crate::http::render_path(
                &GET_SCOUT_RESEARCH_BY_ID,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SCOUT_RESEARCH_BY_ID, &path).await
        }

        pub async fn get_scout_research_by_id_items(
            &self,
            params: &api_types::ScoutResearchIdParams,
        ) -> Result<Vec<api_types::ScoutItem>> {
            let path = crate::http::render_path(
                &GET_SCOUT_RESEARCH_BY_ID_ITEMS,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SCOUT_RESEARCH_BY_ID_ITEMS, &path).await
        }

        pub async fn get_sessions(
            &self,
            query: &api_types::SessionsQuery,
        ) -> Result<api_types::SessionsListResponse> {
            self.get_json_query(&GET_SESSIONS, GET_SESSIONS.path, query)
                .await
        }

        pub async fn get_sessions_by_id(
            &self,
            params: &api_types::SessionIdParams,
        ) -> Result<api_types::SessionEntry> {
            let path =
                crate::http::render_path(&GET_SESSIONS_BY_ID, &[("id", params.id.to_string())]);
            self.get_json(&GET_SESSIONS_BY_ID, &path).await
        }

        pub async fn get_sessions_by_id_cost(
            &self,
            params: &api_types::SessionIdParams,
        ) -> Result<api_types::SessionCostResponse> {
            let path = crate::http::render_path(
                &GET_SESSIONS_BY_ID_COST,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SESSIONS_BY_ID_COST, &path).await
        }

        pub async fn get_sessions_by_id_events(
            &self,
            params: &api_types::SessionIdParams,
        ) -> Result<api_types::TranscriptEventsResponse> {
            let path = crate::http::render_path(
                &GET_SESSIONS_BY_ID_EVENTS,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SESSIONS_BY_ID_EVENTS, &path).await
        }

        pub async fn get_sessions_by_id_images_by_tool_by_index(
            &self,
            params: &api_types::SessionToolResultImageParams,
        ) -> Result<Vec<u8>> {
            let path = crate::http::render_path(
                &GET_SESSIONS_BY_ID_IMAGES_BY_TOOL_BY_INDEX,
                &[
                    ("id", params.id.to_string()),
                    ("tool", params.tool.to_string()),
                    ("index", params.index.to_string()),
                ],
            );
            self.get_bytes(&GET_SESSIONS_BY_ID_IMAGES_BY_TOOL_BY_INDEX, &path)
                .await
        }

        pub async fn get_sessions_by_id_jsonlpath(
            &self,
            params: &api_types::SessionIdParams,
        ) -> Result<api_types::SessionJsonlPathResponse> {
            let path = crate::http::render_path(
                &GET_SESSIONS_BY_ID_JSONLPATH,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SESSIONS_BY_ID_JSONLPATH, &path).await
        }

        pub async fn get_sessions_by_id_messages(
            &self,
            params: &api_types::SessionIdParams,
            query: &api_types::SessionMessagesQuery,
        ) -> Result<api_types::SessionMessagesResponse> {
            let path = crate::http::render_path(
                &GET_SESSIONS_BY_ID_MESSAGES,
                &[("id", params.id.to_string())],
            );
            self.get_json_query(&GET_SESSIONS_BY_ID_MESSAGES, &path, query)
                .await
        }

        pub async fn get_sessions_by_id_stream(
            &self,
            params: &api_types::SessionIdParams,
            query: &api_types::SessionStreamQuery,
        ) -> Result<String> {
            let path = crate::http::render_path(
                &GET_SESSIONS_BY_ID_STREAM,
                &[("id", params.id.to_string())],
            );
            self.get_text_query(&GET_SESSIONS_BY_ID_STREAM, &path, query)
                .await
        }

        pub async fn get_sessions_by_id_tools(
            &self,
            params: &api_types::SessionIdParams,
        ) -> Result<api_types::SessionToolUsageResponse> {
            let path = crate::http::render_path(
                &GET_SESSIONS_BY_ID_TOOLS,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_SESSIONS_BY_ID_TOOLS, &path).await
        }

        pub async fn get_stats_activity(&self) -> Result<api_types::ActivityStatsResponse> {
            self.get_json(&GET_STATS_ACTIVITY, GET_STATS_ACTIVITY.path)
                .await
        }

        pub async fn delete_tasks(
            &self,
            body: &api_types::TaskDeleteRequest,
        ) -> Result<api_types::DeleteTasksResponse> {
            self.delete_json_body(&DELETE_TASKS, DELETE_TASKS.path, body)
                .await
        }

        pub async fn get_tasks(
            &self,
            query: &api_types::TaskListQuery,
        ) -> Result<api_types::TaskListResponse> {
            self.get_json_query(&GET_TASKS, GET_TASKS.path, query).await
        }

        pub async fn post_tasks_accept(
            &self,
            body: &api_types::TaskIdRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_ACCEPT, POST_TASKS_ACCEPT.path, body)
                .await
        }

        pub async fn post_tasks_add_multipart(
            &self,
            form: reqwest::multipart::Form,
        ) -> Result<api_types::TaskItem> {
            self.post_multipart(&POST_TASKS_ADD, POST_TASKS_ADD.path, form)
                .await
        }

        pub async fn post_tasks_bulk(
            &self,
            body: &api_types::TaskBulkUpdateRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_BULK, POST_TASKS_BULK.path, body)
                .await
        }

        pub async fn post_tasks_cancel(
            &self,
            body: &api_types::TaskIdRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_CANCEL, POST_TASKS_CANCEL.path, body)
                .await
        }

        pub async fn post_tasks_delete(
            &self,
            body: &api_types::TaskDeleteRequest,
        ) -> Result<api_types::DeleteTasksResponse> {
            self.post_json(&POST_TASKS_DELETE, POST_TASKS_DELETE.path, body)
                .await
        }

        pub async fn post_tasks_handoff(
            &self,
            body: &api_types::TaskIdRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_HANDOFF, POST_TASKS_HANDOFF.path, body)
                .await
        }

        pub async fn post_tasks_merge(
            &self,
            body: &api_types::MergeRequest,
        ) -> Result<api_types::MergeResponse> {
            self.post_json(&POST_TASKS_MERGE, POST_TASKS_MERGE.path, body)
                .await
        }

        pub async fn post_tasks_reopen_multipart(
            &self,
            form: reqwest::multipart::Form,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_multipart(&POST_TASKS_REOPEN, POST_TASKS_REOPEN.path, form)
                .await
        }

        pub async fn post_tasks_reopen(
            &self,
            body: &api_types::TaskFeedbackRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_REOPEN, POST_TASKS_REOPEN.path, body)
                .await
        }

        pub async fn post_tasks_resumeratelimited(
            &self,
            body: &api_types::TaskIdRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(
                &POST_TASKS_RESUMERATELIMITED,
                POST_TASKS_RESUMERATELIMITED.path,
                body,
            )
            .await
        }

        pub async fn post_tasks_retry(
            &self,
            body: &api_types::TaskIdRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_RETRY, POST_TASKS_RETRY.path, body)
                .await
        }

        pub async fn post_tasks_rework_multipart(
            &self,
            form: reqwest::multipart::Form,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_multipart(&POST_TASKS_REWORK, POST_TASKS_REWORK.path, form)
                .await
        }

        pub async fn post_tasks_rework(
            &self,
            body: &api_types::TaskFeedbackRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_REWORK, POST_TASKS_REWORK.path, body)
                .await
        }

        pub async fn post_tasks_stop(
            &self,
            body: &api_types::TaskIdRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_TASKS_STOP, POST_TASKS_STOP.path, body)
                .await
        }

        pub async fn patch_tasks_by_id(
            &self,
            params: &api_types::TaskIdParams,
            body: &api_types::TaskPatchRequest,
        ) -> Result<api_types::BoolOkResponse> {
            let path =
                crate::http::render_path(&PATCH_TASKS_BY_ID, &[("id", params.id.to_string())]);
            self.patch_json(&PATCH_TASKS_BY_ID, &path, body).await
        }

        pub async fn get_tasks_by_id_artifacts(
            &self,
            params: &api_types::TaskIdParams,
        ) -> Result<api_types::ArtifactsResponse> {
            let path = crate::http::render_path(
                &GET_TASKS_BY_ID_ARTIFACTS,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_TASKS_BY_ID_ARTIFACTS, &path).await
        }

        pub async fn post_tasks_by_id_clarify_multipart(
            &self,
            params: &api_types::TaskIdParams,
            query: &api_types::ClarifyQuery,
            form: reqwest::multipart::Form,
        ) -> Result<api_types::ClarifyResponse> {
            let path = crate::http::render_path(
                &POST_TASKS_BY_ID_CLARIFY,
                &[("id", params.id.to_string())],
            );
            self.post_multipart_query(&POST_TASKS_BY_ID_CLARIFY, &path, query, form)
                .await
        }

        pub async fn post_tasks_by_id_clarify(
            &self,
            params: &api_types::TaskIdParams,
            query: &api_types::ClarifyQuery,
            body: &api_types::ClarifyRequest,
        ) -> Result<api_types::ClarifyResponse> {
            let path = crate::http::render_path(
                &POST_TASKS_BY_ID_CLARIFY,
                &[("id", params.id.to_string())],
            );
            self.post_json_query(&POST_TASKS_BY_ID_CLARIFY, &path, query, body)
                .await
        }

        pub async fn post_tasks_by_id_evidence(
            &self,
            params: &api_types::TaskIdParams,
            body: &api_types::TaskEvidenceRequest,
        ) -> Result<api_types::TaskEvidenceResponse> {
            let path = crate::http::render_path(
                &POST_TASKS_BY_ID_EVIDENCE,
                &[("id", params.id.to_string())],
            );
            self.post_json(&POST_TASKS_BY_ID_EVIDENCE, &path, body)
                .await
        }

        pub async fn get_tasks_by_id_feed(
            &self,
            params: &api_types::TaskIdParams,
        ) -> Result<api_types::FeedResponse> {
            let path =
                crate::http::render_path(&GET_TASKS_BY_ID_FEED, &[("id", params.id.to_string())]);
            self.get_json(&GET_TASKS_BY_ID_FEED, &path).await
        }

        pub async fn get_tasks_by_id_prsummary(
            &self,
            params: &api_types::TaskIdParams,
        ) -> Result<api_types::PrSummaryResponse> {
            let path = crate::http::render_path(
                &GET_TASKS_BY_ID_PRSUMMARY,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_TASKS_BY_ID_PRSUMMARY, &path).await
        }

        pub async fn get_tasks_by_id_sessions(
            &self,
            params: &api_types::TaskIdParams,
            query: &api_types::SessionsQuery,
        ) -> Result<api_types::ItemSessionsResponse> {
            let path = crate::http::render_path(
                &GET_TASKS_BY_ID_SESSIONS,
                &[("id", params.id.to_string())],
            );
            self.get_json_query(&GET_TASKS_BY_ID_SESSIONS, &path, query)
                .await
        }

        pub async fn post_tasks_by_id_summary(
            &self,
            params: &api_types::TaskIdParams,
            body: &api_types::TaskSummaryRequest,
        ) -> Result<api_types::TaskSummaryResponse> {
            let path = crate::http::render_path(
                &POST_TASKS_BY_ID_SUMMARY,
                &[("id", params.id.to_string())],
            );
            self.post_json(&POST_TASKS_BY_ID_SUMMARY, &path, body).await
        }

        pub async fn get_tasks_by_id_timeline(
            &self,
            params: &api_types::TaskIdParams,
        ) -> Result<api_types::TimelineResponse> {
            let path = crate::http::render_path(
                &GET_TASKS_BY_ID_TIMELINE,
                &[("id", params.id.to_string())],
            );
            self.get_json(&GET_TASKS_BY_ID_TIMELINE, &path).await
        }

        pub async fn post_ui_launch(&self) -> Result<api_types::BoolOkResponse> {
            self.post_json(
                &POST_UI_LAUNCH,
                POST_UI_LAUNCH.path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_ui_quitting(&self) -> Result<api_types::BoolOkResponse> {
            self.post_json(
                &POST_UI_QUITTING,
                POST_UI_QUITTING.path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_ui_register(
            &self,
            body: &api_types::UiRegisterRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_UI_REGISTER, POST_UI_REGISTER.path, body)
                .await
        }

        pub async fn post_ui_restart(&self) -> Result<api_types::BoolOkResponse> {
            self.post_json(
                &POST_UI_RESTART,
                POST_UI_RESTART.path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_ui_updating(&self) -> Result<api_types::BoolOkResponse> {
            self.post_json(
                &POST_UI_UPDATING,
                POST_UI_UPDATING.path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn get_workbenches(
            &self,
            query: &api_types::WorkbenchListQuery,
        ) -> Result<api_types::WorkbenchesResponse> {
            self.get_json_query(&GET_WORKBENCHES, GET_WORKBENCHES.path, query)
                .await
        }

        pub async fn patch_workbenches_by_id(
            &self,
            params: &api_types::WorkbenchIdParams,
            body: &api_types::WorkbenchPatchRequest,
        ) -> Result<api_types::WorkbenchItem> {
            let path = crate::http::render_path(
                &PATCH_WORKBENCHES_BY_ID,
                &[("id", params.id.to_string())],
            );
            self.patch_json(&PATCH_WORKBENCHES_BY_ID, &path, body).await
        }

        pub async fn get_workers(&self) -> Result<api_types::WorkersResponse> {
            self.get_json(&GET_WORKERS, GET_WORKERS.path).await
        }

        pub async fn get_worktrees(&self) -> Result<api_types::WorktreeListResponse> {
            self.get_json(&GET_WORKTREES, GET_WORKTREES.path).await
        }

        pub async fn post_worktrees(
            &self,
            body: &api_types::CreateWorktreeRequest,
        ) -> Result<api_types::CreateWorktreeResponse> {
            self.post_json(&POST_WORKTREES, POST_WORKTREES.path, body)
                .await
        }

        pub async fn post_worktrees_cleanup(
            &self,
            body: &api_types::WorktreeCleanupRequest,
        ) -> Result<api_types::WorktreeCleanupResponse> {
            self.post_json(&POST_WORKTREES_CLEANUP, POST_WORKTREES_CLEANUP.path, body)
                .await
        }

        pub async fn post_worktrees_prune(&self) -> Result<api_types::WorktreePruneResponse> {
            self.post_json(
                &POST_WORKTREES_PRUNE,
                POST_WORKTREES_PRUNE.path,
                &api_types::EmptyRequest {},
            )
            .await
        }

        pub async fn post_worktrees_remove(
            &self,
            body: &api_types::RemoveWorktreeRequest,
        ) -> Result<api_types::BoolOkResponse> {
            self.post_json(&POST_WORKTREES_REMOVE, POST_WORKTREES_REMOVE.path, body)
                .await
        }
    }
}
