//! Clarification flow — single-turn and multi-turn via unified endpoint.

use crate::Task;
use anyhow::Result;
use rustc_hash::FxHashMap;
use settings::CaptainWorkflow;
use tracing::{info, warn};

use global_claude::CcConfig;

use super::dashboard::truncate_utf8;
use global_claude::parse_llm_json;

/// JSON schema enforced on clarifier structured output. The task's project is
/// fixed at creation and never inferred here, so the schema has no `repo`
/// field — the clarifier only decides readiness, enriches context, and
/// (optionally) refines the title / resource / no_pr hint.
pub(crate) fn build_clarifier_schema() -> serde_json::Value {
    serde_json::json!({
        "type": "object",
        "properties": {
            "status": { "type": "string", "enum": ["ready", "clarifying", "escalate", "answered"] },
            "context": { "type": "string" },
            "questions": {
                "type": ["array", "null"],
                "items": {
                    "type": "object",
                    "properties": {
                        "question": { "type": "string" },
                        "answer": { "type": ["string", "null"] },
                        "self_answered": { "type": "boolean" },
                        "category": { "type": "string", "enum": ["code", "intent"] }
                    },
                    "required": ["question", "self_answered", "category"]
                }
            },
            "title": { "type": "string" },
            "no_pr": { "type": ["boolean", "null"] },
            "resource": { "type": ["string", "null"] },
            "is_bug_fix": { "type": "boolean" }
        },
        "required": ["status", "context", "title", "is_bug_fix"]
    })
}

// ── Single-turn (captain tick auto-clarification) ───────────────────

/// Run the clarification flow for a new task (single-turn).
#[tracing::instrument(skip_all)]
pub(crate) async fn run_clarification(
    item: &Task,
    workflow: &CaptainWorkflow,
    config: &settings::Config,
    pool: &sqlx::SqlitePool,
    pre_session_id: Option<&str>,
) -> Result<ClarifierResult> {
    let prompt = build_clarifier_prompt(item, None, workflow)?;

    // Resolve project cwd so the clarifier can read project files.
    let cwd = resolve_clarifier_cwd(item, config)?;

    let task_id = item.id.to_string();
    let task_id_ref = task_id.as_str();
    let cwd_ref = cwd.as_path();
    let model = workflow.models.clarifier.as_str();
    let timeout = workflow.agent.clarifier_timeout_s;
    let result = match settings::cc_failover::run_with_credential_failover(
        pool,
        "clarifier",
        &prompt,
        |ctx| {
            let mut builder = CcConfig::builder()
                .model(model)
                .timeout(timeout)
                .caller("clarifier")
                .task_id(task_id_ref)
                .cwd(cwd_ref.to_path_buf())
                .allowed_tools(vec!["Read".into(), "Glob".into(), "Grep".into()])
                .json_schema(build_clarifier_schema());
            builder = global_claude::with_credential(builder, &ctx.credential);
            if let Some(rid) = &ctx.resume_session_id {
                builder = builder.resume(rid);
            } else if let Some(sid) = pre_session_id {
                builder = builder.session_id(sid);
            }
            builder.build()
        },
    )
    .await
    {
        Ok(result) => result,
        Err(e) => {
            warn!(module = "clarifier", title = %item.title, error = %e, "CC failed");
            return Err(e.into());
        }
    };
    let cred_id = result.credential_id;

    if let Err(e) = crate::io::headless_cc::log_cc_session(
        pool,
        &crate::io::headless_cc::SessionLogEntry {
            session_id: &result.session_id,
            cwd: &cwd,
            model: &workflow.models.clarifier,
            caller: "clarifier",
            cost_usd: result.cost_usd,
            duration_ms: result.duration_ms,
            resumed: false,
            task_id: Some(item.id),
            status: global_types::SessionStatus::Stopped,
            worker_name: "",
            credential_id: cred_id,
            error: None,
            api_error_status: None,
        },
    )
    .await
    {
        warn!(module = "clarifier", error = %e, "failed to log clarifier session");
    }

    let text = result
        .structured
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_else(|| result.text.clone());
    let mut parsed = parse_clarifier_response(&text, &item.title);
    parsed.session_id = Some(result.session_id.clone());

    info!(
        module = "clarifier",
        title = %truncate_utf8(&item.title, 60),
        status = ?parsed.status,
        "clarification complete"
    );
    Ok(parsed)
}

// ── Types ───────────────────────────────────────────────────────────

/// A single question generated by the clarifier, with optional self-answer.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ClarifierQuestion {
    pub question: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    pub self_answered: bool,
    /// "code" (answerable from the codebase) or "intent" (requires human judgment).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
}

/// Result of a clarification turn.
pub struct ClarifierResult {
    pub status: ClarifierStatus,
    pub context: String,
    pub questions: Option<Vec<ClarifierQuestion>>,
    pub generated_title: Option<String>,
    pub no_pr: Option<bool>,
    pub resource: Option<String>,
    pub is_bug_fix: Option<bool>,
    pub session_id: Option<String>,
}

/// Clarifier outcome.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClarifierStatus {
    Ready,
    Clarifying,
    Escalate,
    Answered,
}

/// Format structured questions into human-readable text.
/// Self-answered questions are excluded — users only see what needs their input.
pub fn format_questions_text(questions: &[ClarifierQuestion]) -> String {
    questions
        .iter()
        .filter(|q| !q.self_answered)
        .enumerate()
        .map(|(i, q)| format!("{}. {}", i + 1, q.question))
        .collect::<Vec<_>>()
        .join("\n")
}

// ── Shared helpers ──────────────────────────────────────────────────

/// Resolve the working directory for the clarifier based on the item's project.
///
/// Returns `Err` if the project cannot be resolved. Previously this fell back
/// to `data_dir()` which gave the clarifier no access to project files and
/// silently produced bogus results; callers now escalate instead.
pub(crate) fn resolve_clarifier_cwd(
    item: &Task,
    config: &settings::Config,
) -> Result<std::path::PathBuf> {
    match settings::resolve_project_config(Some(&item.project), config) {
        Some((_key, proj)) => Ok(global_infra::paths::expand_tilde(&proj.path)),
        None => Err(anyhow::anyhow!(
            "could not resolve project {:?} for clarifier cwd on item {:?}",
            item.project,
            item.title
        )),
    }
}

fn build_clarifier_prompt(
    item: &Task,
    human_input: Option<&str>,
    workflow: &CaptainWorkflow,
) -> anyhow::Result<String> {
    let context = item.context.as_deref().unwrap_or("none");
    let project = item.project.as_str();

    let mut resource_names: Vec<&str> = vec!["cc"];
    for key in workflow.agent.resource_limits.keys() {
        if key != "cc" {
            resource_names.push(key.as_str());
        }
    }
    resource_names[1..].sort();
    let resource_list = resource_names.join(", ");

    let images = item
        .images
        .as_deref()
        .filter(|s| !s.is_empty())
        .map(|s| {
            let images_dir = global_infra::paths::images_dir();
            s.split(',')
                .filter_map(|f| {
                    let name = f.trim();
                    let basename = std::path::Path::new(name).file_name()?.to_str()?;
                    if basename == name && !name.contains("..") {
                        Some(format!("- {}", images_dir.join(basename).display()))
                    } else {
                        None
                    }
                })
                .collect::<Vec<_>>()
                .join("\n")
        })
        .unwrap_or_default();

    let mut vars: FxHashMap<&str, &str> = FxHashMap::default();
    vars.insert("title", item.title.as_str());
    vars.insert("context", context);
    vars.insert("project", project);
    vars.insert("images", images.as_str());
    vars.insert("resource_list", &resource_list);
    if let Some(input) = human_input {
        vars.insert("human_input", input);
    }

    settings::render_prompt("clarifier", &workflow.prompts, &vars).map_err(|e| anyhow::anyhow!(e))
}

pub(crate) fn build_interactive_clarifier_turn_prompt(
    item: &Task,
    workflow: &CaptainWorkflow,
    human_input: &str,
    outstanding_questions: Option<&[ClarifierQuestion]>,
) -> anyhow::Result<String> {
    let details = item
        .original_prompt
        .as_deref()
        .unwrap_or(item.context.as_deref().unwrap_or("(none)"));
    let current_context = item.context.as_deref().unwrap_or("(none)");
    let questions_text = outstanding_questions
        .map(format_questions_text)
        .unwrap_or_else(|| "(none)".to_string());

    let mut vars: FxHashMap<&str, &str> = FxHashMap::default();
    vars.insert("title", item.title.as_str());
    vars.insert("details", details);
    vars.insert("current_context", current_context);
    vars.insert("outstanding_questions", questions_text.as_str());
    vars.insert("human_response", human_input.trim());

    settings::render_prompt("interactive_clarifier", &workflow.prompts, &vars)
        .map_err(|e| anyhow::anyhow!(e))
}

fn escalate(title: &str, reason: &str) -> ClarifierResult {
    ClarifierResult {
        status: ClarifierStatus::Escalate,
        context: title.to_string(),
        questions: Some(vec![ClarifierQuestion {
            question: reason.to_string(),
            answer: None,
            self_answered: false,
            category: Some("intent".into()),
        }]),
        generated_title: None,
        no_pr: None,
        resource: None,
        is_bug_fix: None,
        session_id: None,
    }
}

pub(crate) fn parse_clarifier_response(text: &str, item_title: &str) -> ClarifierResult {
    let parsed = match parse_llm_json(text) {
        Ok(v) => v,
        Err(e) => {
            warn!(module = "clarifier", error = %e, "unparseable response — escalating");
            return escalate(item_title, "Clarifier returned unparseable response");
        }
    };

    if !parsed["status"].is_string() {
        warn!(module = "clarifier", "missing status field — escalating");
        return escalate(item_title, "Clarifier returned JSON without status field");
    }

    // has_valid_status guarantees is_string(), so as_str() always succeeds here.
    // If it somehow doesn't (e.g. non-string JSON type slipped through), fail closed.
    let status_str = match parsed["status"].as_str() {
        Some(s) => s,
        None => {
            warn!(
                module = "clarifier",
                raw = %parsed["status"],
                "status field present but not a string — escalating (fail-closed)"
            );
            "escalate"
        }
    };
    let status = match status_str {
        "clarifying" => ClarifierStatus::Clarifying,
        "escalate" => ClarifierStatus::Escalate,
        "answered" => ClarifierStatus::Answered,
        "understood" | "ready" => ClarifierStatus::Ready,
        unknown => {
            warn!(
                module = "clarifier",
                status = %unknown,
                "clarifier returned unknown status — escalating (fail-closed)"
            );
            ClarifierStatus::Escalate
        }
    };

    let context = parsed["context"].as_str().unwrap_or(item_title).to_string();
    let questions = parsed["questions"].as_array().map(|arr| {
        arr.iter()
            .filter_map(|v| {
                Some(ClarifierQuestion {
                    question: v["question"].as_str()?.to_string(),
                    answer: v["answer"].as_str().map(String::from),
                    self_answered: v["self_answered"].as_bool().unwrap_or(false),
                    category: v["category"].as_str().map(String::from),
                })
            })
            .collect()
    });
    let generated_title = parsed["title"]
        .as_str()
        .or_else(|| parsed["generated_title"].as_str())
        .map(String::from);

    let no_pr = parsed["no_pr"].as_bool();
    let resource = parsed["resource"].as_str().map(String::from);
    let is_bug_fix = parsed["is_bug_fix"].as_bool();
    // The schema requires `is_bug_fix` as a non-null boolean. If we still see
    // `None`, the LLM violated the schema — log loudly so the failure is
    // visible instead of silently defaulting downstream consumers to `false`
    // (the prior behavior, which suppressed the bug-fix protocol on
    // misclassified tasks).
    if is_bug_fix.is_none() {
        tracing::warn!(
            module = "captain-runtime-clarifier",
            "clarifier returned null is_bug_fix despite schema requiring boolean — \
             downstream defaults to false; investigate the model output"
        );
    }

    ClarifierResult {
        status,
        context,
        questions,
        generated_title,
        no_pr,
        resource,
        is_bug_fix,
        session_id: None,
    }
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_understood_response() {
        let json = r#"{"status":"understood","context":"enriched ctx","questions":null,"generated_title":"Better title"}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Ready);
        assert_eq!(result.context, "enriched ctx");
        assert!(result.questions.is_none());
        assert_eq!(result.generated_title.as_deref(), Some("Better title"));
    }

    #[test]
    fn parse_structured_questions() {
        let json = r#"{"status":"clarifying","context":"partial","questions":[{"question":"What repo?","answer":null,"self_answered":false,"category":"intent"},{"question":"Where is the code?","answer":"In src/lib.rs","self_answered":true,"category":"code"}]}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Clarifying);
        let qs = result.questions.unwrap();
        assert_eq!(qs.len(), 2);
        assert_eq!(qs[0].question, "What repo?");
        assert!(!qs[0].self_answered);
        assert!(qs[0].answer.is_none());
        assert_eq!(qs[0].category.as_deref(), Some("intent"));
        assert_eq!(qs[1].question, "Where is the code?");
        assert!(qs[1].self_answered);
        assert_eq!(qs[1].answer.as_deref(), Some("In src/lib.rs"));
        assert_eq!(qs[1].category.as_deref(), Some("code"));
    }

    #[test]
    fn parse_invalid_json_escalates() {
        let result = parse_clarifier_response("not json", "fallback title");
        assert_eq!(result.status, ClarifierStatus::Escalate);
        assert_eq!(result.context, "fallback title");
    }

    #[test]
    fn parse_code_fenced_json() {
        let fenced = "```json\n{\"status\":\"understood\",\"context\":\"enriched\",\"title\":\"Better\",\"resource\":\"cc\",\"no_pr\":false}\n```";
        let result = parse_clarifier_response(fenced, "fallback");
        assert_eq!(result.status, ClarifierStatus::Ready);
        assert_eq!(result.context, "enriched");
        assert_eq!(result.generated_title.as_deref(), Some("Better"));
        assert_eq!(result.no_pr, Some(false));
        assert_eq!(result.resource.as_deref(), Some("cc"));
    }

    #[test]
    fn schema_has_no_repo_field() {
        let schema = build_clarifier_schema();
        assert!(schema["properties"].get("repo").is_none());
        let required = schema["required"].as_array().unwrap();
        assert!(required.contains(&serde_json::json!("status")));
        assert!(required.contains(&serde_json::json!("context")));
        assert!(required.contains(&serde_json::json!("title")));
    }

    #[test]
    fn format_questions_text_mixed() {
        let qs = vec![
            ClarifierQuestion {
                question: "What DB?".into(),
                answer: None,
                self_answered: false,
                category: Some("intent".into()),
            },
            ClarifierQuestion {
                question: "What HTTP client?".into(),
                answer: Some("reqwest".into()),
                self_answered: true,
                category: Some("code".into()),
            },
        ];
        let text = format_questions_text(&qs);
        assert!(text.contains("1. What DB?"));
        // Self-answered questions are excluded from user-facing output.
        assert!(!text.contains("HTTP client"));
        assert!(!text.contains("self-answered"));
    }

    #[test]
    fn build_prompt_without_human_input() {
        let workflow = CaptainWorkflow::compiled_default();
        let mut item = Task::new("Fix bug");
        item.context = Some("in auth".into());
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(prompt.contains("Fix bug"));
        assert!(prompt.contains("in auth"));
        assert!(!prompt.contains("Human provided"));
    }

    #[test]
    fn build_prompt_with_human_input() {
        let workflow = CaptainWorkflow::compiled_default();
        let item = Task::new("Fix bug");
        let prompt =
            build_clarifier_prompt(&item, Some("it's in the login page"), &workflow).unwrap();
        assert!(prompt.contains("Human provided additional details: it's in the login page"));
    }

    #[test]
    fn build_prompt_with_images() {
        let workflow = CaptainWorkflow::compiled_default();
        let mut item = Task::new("Fix layout");
        item.images = Some("abc123.png,def456.jpg".into());
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(prompt.contains("abc123.png"));
        assert!(prompt.contains("def456.jpg"));
        assert!(prompt.contains("Attached Images"));
    }

    #[test]
    fn build_prompt_rejects_path_traversal_images() {
        let workflow = CaptainWorkflow::compiled_default();
        let mut item = Task::new("Fix layout");
        item.images = Some("good.png,../../etc/passwd,/absolute/path.jpg".into());
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(prompt.contains("good.png"));
        assert!(!prompt.contains("passwd"));
        assert!(!prompt.contains("/absolute/path.jpg"));
    }

    #[test]
    fn build_prompt_without_images_omits_section() {
        let workflow = CaptainWorkflow::compiled_default();
        let item = Task::new("Fix bug");
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(!prompt.contains("Attached Images"));
    }

    #[test]
    fn parse_unknown_status_escalates() {
        let json = r#"{"status":"pending","context":"ctx"}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Escalate);
    }

    #[test]
    fn parse_ready_status_accepted() {
        let json = r#"{"status":"ready","context":"ctx"}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Ready);
    }
}
