//! Clarification flow — single-turn and multi-turn via unified endpoint.

use crate::Task;
use anyhow::Result;
use rustc_hash::FxHashMap;
use settings::CaptainWorkflow;
use tracing::warn;

use global_claude::parse_llm_json;

/// JSON schema enforced on clarifier structured output. The task's project is
/// fixed at creation and never inferred here, so the schema has no `repo`
/// field — the clarifier only decides readiness, enriches context, and
/// (optionally) refines the title / resource / no_pr hint.
pub(crate) fn build_clarifier_schema(
    workflow: &CaptainWorkflow,
) -> super::agent_runtime::AgentOutputSchema {
    super::agent_runtime::AgentOutputSchema(build_clarifier_schema_value(workflow))
}

fn build_clarifier_schema_value(workflow: &CaptainWorkflow) -> serde_json::Value {
    let resource_schema = build_resource_schema_value(&workflow.agent.resource_limits);
    serde_json::json!({
        "type": "object",
        "properties": {
            "status": { "type": "string", "enum": ["ready", "clarifying", "escalate", "answered"] },
            "context": { "type": "string" },
            "questions": {
                "type": ["array", "null"],
                "items": {
                    "type": "object",
                    "properties": {
                        "question": { "type": "string" },
                        "answer": { "type": ["string", "null"] },
                        "self_answered": { "type": "boolean" },
                        "category": { "type": "string", "enum": ["code", "intent"] }
                    },
                    "required": ["question", "self_answered", "category"]
                }
            },
            "title": { "type": "string" },
            "no_pr": { "type": ["boolean", "null"] },
            "resource": resource_schema,
            "is_bug_fix": { "type": "boolean" }
        },
        "required": ["status", "context", "title", "is_bug_fix"]
    })
}

fn build_resource_schema_value(
    resource_limits: &std::collections::HashMap<String, usize>,
) -> serde_json::Value {
    let mut enum_values = vec![serde_json::Value::Null];
    for name in sorted_resource_names(resource_limits) {
        enum_values.push(serde_json::Value::String(name.to_string()));
    }
    serde_json::json!({
        "type": ["string", "null"],
        "enum": enum_values,
    })
}

// ── Single-turn (captain tick auto-clarification) ───────────────────

// ── Types ───────────────────────────────────────────────────────────

/// A single question generated by the clarifier, with optional self-answer.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ClarifierQuestion {
    pub question: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    pub self_answered: bool,
    /// "code" (answerable from the codebase) or "intent" (requires human judgment).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
}

/// Result of a clarification turn.
pub struct ClarifierResult {
    pub status: ClarifierStatus,
    pub context: String,
    pub questions: Option<Vec<ClarifierQuestion>>,
    pub generated_title: Option<String>,
    pub no_pr: Option<bool>,
    pub resource: Option<String>,
    pub is_bug_fix: Option<bool>,
    pub session_id: Option<String>,
}

/// Clarifier outcome.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClarifierStatus {
    Ready,
    Clarifying,
    Escalate,
    Answered,
}

/// Format structured questions into human-readable text.
/// Answered questions are excluded — users only see what needs their input.
pub fn format_questions_text(questions: &[ClarifierQuestion]) -> String {
    questions
        .iter()
        .filter(|q| !q.self_answered && q.answer.as_deref().is_none_or(|a| a.trim().is_empty()))
        .enumerate()
        .map(|(i, q)| format!("{}. {}", i + 1, q.question))
        .collect::<Vec<_>>()
        .join("\n")
}

// ── Shared helpers ──────────────────────────────────────────────────

/// Resolve the working directory for the clarifier based on the item's project.
///
/// Returns `Err` if the project cannot be resolved. Previously this fell back
/// to `data_dir()` which gave the clarifier no access to project files and
/// silently produced bogus results; callers now escalate instead.
pub(crate) fn resolve_clarifier_cwd(
    item: &Task,
    config: &settings::Config,
) -> Result<std::path::PathBuf> {
    match settings::resolve_project_config(Some(&item.project), config) {
        Some((_key, proj)) => Ok(global_infra::paths::expand_tilde(&proj.path)),
        None => Err(anyhow::anyhow!(
            "could not resolve project {:?} for clarifier cwd on item {:?}",
            item.project,
            item.title
        )),
    }
}

pub(crate) fn build_clarifier_prompt(
    item: &Task,
    human_input: Option<&str>,
    workflow: &CaptainWorkflow,
) -> anyhow::Result<String> {
    let context = item.context.as_deref().unwrap_or("none");
    let project = item.project.as_str();

    let resource_list = resource_list_text(&workflow.agent.resource_limits);

    let images = item
        .images
        .as_deref()
        .filter(|s| !s.is_empty())
        .map(|s| {
            let images_dir = global_infra::paths::images_dir();
            s.split(',')
                .filter_map(|f| {
                    let name = f.trim();
                    let basename = std::path::Path::new(name).file_name()?.to_str()?;
                    if basename == name && !name.contains("..") {
                        Some(format!("- {}", images_dir.join(basename).display()))
                    } else {
                        None
                    }
                })
                .collect::<Vec<_>>()
                .join("\n")
        })
        .unwrap_or_default();

    let mut vars: FxHashMap<&str, &str> = FxHashMap::default();
    vars.insert("title", item.title.as_str());
    vars.insert("context", context);
    vars.insert("project", project);
    vars.insert("images", images.as_str());
    vars.insert("resource_list", &resource_list);
    if let Some(input) = human_input {
        vars.insert("human_input", input);
    }

    settings::render_prompt("clarifier", &workflow.prompts, &vars).map_err(|e| anyhow::anyhow!(e))
}

fn resource_list_text(resource_limits: &std::collections::HashMap<String, usize>) -> String {
    let names = sorted_resource_names(resource_limits);
    if names.is_empty() {
        "none".to_string()
    } else {
        names.join(", ")
    }
}

pub(super) fn sorted_resource_names(
    resource_limits: &std::collections::HashMap<String, usize>,
) -> Vec<&str> {
    let mut names: Vec<&str> = resource_limits.keys().map(String::as_str).collect();
    names.sort_unstable();
    names
}

pub(crate) fn build_interactive_clarifier_turn_prompt(
    item: &Task,
    workflow: &CaptainWorkflow,
    human_input: &str,
    outstanding_questions: Option<&[ClarifierQuestion]>,
) -> anyhow::Result<String> {
    let details = item
        .original_prompt
        .as_deref()
        .unwrap_or(item.context.as_deref().unwrap_or("(none)"));
    let current_context = item.context.as_deref().unwrap_or("(none)");
    let questions_text = outstanding_questions
        .map(format_questions_text)
        .unwrap_or_else(|| "(none)".to_string());

    let mut vars: FxHashMap<&str, &str> = FxHashMap::default();
    vars.insert("title", item.title.as_str());
    vars.insert("details", details);
    vars.insert("current_context", current_context);
    vars.insert("outstanding_questions", questions_text.as_str());
    vars.insert("human_response", human_input.trim());

    settings::render_prompt("interactive_clarifier", &workflow.prompts, &vars)
        .map_err(|e| anyhow::anyhow!(e))
}

fn escalate(title: &str, reason: &str) -> ClarifierResult {
    ClarifierResult {
        status: ClarifierStatus::Escalate,
        context: title.to_string(),
        questions: Some(vec![ClarifierQuestion {
            question: reason.to_string(),
            answer: None,
            self_answered: false,
            category: Some("intent".into()),
        }]),
        generated_title: None,
        no_pr: None,
        resource: None,
        is_bug_fix: None,
        session_id: None,
    }
}

pub(crate) fn parse_clarifier_response(text: &str, item_title: &str) -> ClarifierResult {
    let parsed = match parse_llm_json(text) {
        Ok(v) => v,
        Err(e) => {
            warn!(module = "clarifier", error = %e, "unparseable response — escalating");
            return escalate(item_title, "Clarifier returned unparseable response");
        }
    };

    if !parsed["status"].is_string() {
        warn!(module = "clarifier", "missing status field — escalating");
        return escalate(item_title, "Clarifier returned JSON without status field");
    }

    // has_valid_status guarantees is_string(), so as_str() always succeeds here.
    // If it somehow doesn't (e.g. non-string JSON type slipped through), fail closed.
    let status_str = match parsed["status"].as_str() {
        Some(s) => s,
        None => {
            warn!(
                module = "clarifier",
                raw = %parsed["status"],
                "status field present but not a string — escalating (fail-closed)"
            );
            "escalate"
        }
    };
    let mut status = match status_str {
        "clarifying" => ClarifierStatus::Clarifying,
        "escalate" => ClarifierStatus::Escalate,
        "answered" => ClarifierStatus::Answered,
        "understood" | "ready" => ClarifierStatus::Ready,
        unknown => {
            warn!(
                module = "clarifier",
                status = %unknown,
                "clarifier returned unknown status — escalating (fail-closed)"
            );
            ClarifierStatus::Escalate
        }
    };

    let context = parsed["context"].as_str().unwrap_or(item_title).to_string();
    let questions = parsed["questions"].as_array().and_then(|arr| {
        let unanswered: Vec<_> = arr
            .iter()
            .filter_map(|v| {
                Some(ClarifierQuestion {
                    question: v["question"].as_str()?.to_string(),
                    answer: v["answer"].as_str().map(String::from),
                    self_answered: v["self_answered"].as_bool().unwrap_or(false),
                    category: v["category"].as_str().map(String::from),
                })
            })
            .filter(|q| !q.self_answered && q.answer.as_deref().is_none_or(|a| a.trim().is_empty()))
            .collect();
        if unanswered.is_empty() {
            None
        } else {
            Some(unanswered)
        }
    });
    if status == ClarifierStatus::Clarifying && questions.is_none() {
        warn!(
            module = "clarifier",
            "clarifier requested follow-up but returned no unanswered questions — marking ready"
        );
        status = ClarifierStatus::Ready;
    }

    let generated_title = parsed["title"]
        .as_str()
        .or_else(|| parsed["generated_title"].as_str())
        .map(String::from);

    let no_pr = parsed["no_pr"].as_bool();
    let resource = parsed["resource"].as_str().map(String::from);
    let is_bug_fix = parsed["is_bug_fix"].as_bool();
    // The schema requires `is_bug_fix` as a non-null boolean. If we still see
    // `None`, the LLM violated the schema — log loudly so the failure is
    // visible instead of silently defaulting downstream consumers to `false`
    // (the prior behavior, which suppressed the bug-fix protocol on
    // misclassified tasks).
    if is_bug_fix.is_none() {
        tracing::warn!(
            module = "captain-runtime-clarifier",
            "clarifier returned null is_bug_fix despite schema requiring boolean — \
             downstream defaults to false; investigate the model output"
        );
    }

    ClarifierResult {
        status,
        context,
        questions,
        generated_title,
        no_pr,
        resource,
        is_bug_fix,
        session_id: None,
    }
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_understood_response() {
        let json = r#"{"status":"understood","context":"enriched ctx","questions":null,"generated_title":"Better title"}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Ready);
        assert_eq!(result.context, "enriched ctx");
        assert!(result.questions.is_none());
        assert_eq!(result.generated_title.as_deref(), Some("Better title"));
    }

    #[test]
    fn parse_structured_questions_keeps_only_unanswered() {
        let json = r#"{"status":"clarifying","context":"partial","questions":[{"question":"What repo?","answer":null,"self_answered":false,"category":"intent"},{"question":"Where is the code?","answer":"In src/lib.rs","self_answered":true,"category":"code"},{"question":"Which UI?","answer":"Sidebar","self_answered":false,"category":"intent"}]}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Clarifying);
        let qs = result.questions.unwrap();
        assert_eq!(qs.len(), 1);
        assert_eq!(qs[0].question, "What repo?");
        assert!(!qs[0].self_answered);
        assert!(qs[0].answer.is_none());
        assert_eq!(qs[0].category.as_deref(), Some("intent"));
    }

    #[test]
    fn parse_invalid_json_escalates() {
        let result = parse_clarifier_response("not json", "fallback title");
        assert_eq!(result.status, ClarifierStatus::Escalate);
        assert_eq!(result.context, "fallback title");
    }

    #[test]
    fn clarifying_with_no_unanswered_questions_becomes_ready() {
        let json = r#"{"status":"clarifying","context":"ctx","questions":[{"question":"Which UI?","answer":"Sidebar","self_answered":false,"category":"intent"}]}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Ready);
        assert!(result.questions.is_none());
    }

    #[test]
    fn parse_code_fenced_json() {
        let fenced = "```json\n{\"status\":\"understood\",\"context\":\"enriched\",\"title\":\"Better\",\"resource\":\"emulator\",\"no_pr\":false}\n```";
        let result = parse_clarifier_response(fenced, "fallback");
        assert_eq!(result.status, ClarifierStatus::Ready);
        assert_eq!(result.context, "enriched");
        assert_eq!(result.generated_title.as_deref(), Some("Better"));
        assert_eq!(result.no_pr, Some(false));
        assert_eq!(result.resource.as_deref(), Some("emulator"));
    }

    #[test]
    fn schema_has_no_repo_field() {
        let workflow = CaptainWorkflow::compiled_default();
        let schema = build_clarifier_schema(&workflow).0;
        assert!(schema["properties"].get("repo").is_none());
        let required = schema["required"].as_array().unwrap();
        assert!(required.contains(&serde_json::json!("status")));
        assert!(required.contains(&serde_json::json!("context")));
        assert!(required.contains(&serde_json::json!("title")));
    }

    #[test]
    fn schema_enumerates_configured_resources_and_null_only() {
        let workflow = CaptainWorkflow::compiled_default();
        let schema = build_clarifier_schema(&workflow).0;
        assert_eq!(
            schema["properties"]["resource"]["enum"],
            serde_json::json!([null, "emulator"])
        );
        assert!(!schema["properties"]["resource"]["enum"]
            .as_array()
            .unwrap()
            .contains(&serde_json::json!("cc")));
    }

    #[test]
    fn format_questions_text_mixed() {
        let qs = vec![
            ClarifierQuestion {
                question: "What DB?".into(),
                answer: None,
                self_answered: false,
                category: Some("intent".into()),
            },
            ClarifierQuestion {
                question: "What HTTP client?".into(),
                answer: Some("reqwest".into()),
                self_answered: true,
                category: Some("code".into()),
            },
            ClarifierQuestion {
                question: "Which screen?".into(),
                answer: Some("Settings".into()),
                self_answered: false,
                category: Some("intent".into()),
            },
        ];
        let text = format_questions_text(&qs);
        assert!(text.contains("1. What DB?"));
        // Answered questions are excluded from user-facing output.
        assert!(!text.contains("HTTP client"));
        assert!(!text.contains("Which screen"));
    }

    #[test]
    fn build_prompt_without_human_input() {
        let workflow = CaptainWorkflow::compiled_default();
        let mut item = Task::new("Fix bug");
        item.context = Some("in auth".into());
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(prompt.contains("Fix bug"));
        assert!(prompt.contains("in auth"));
        assert!(!prompt.contains("Human provided"));
    }

    #[test]
    fn build_prompt_with_human_input() {
        let workflow = CaptainWorkflow::compiled_default();
        let item = Task::new("Fix bug");
        let prompt =
            build_clarifier_prompt(&item, Some("it's in the login page"), &workflow).unwrap();
        assert!(prompt.contains("Human provided additional details: it's in the login page"));
    }

    #[test]
    fn build_prompt_with_images() {
        let workflow = CaptainWorkflow::compiled_default();
        let mut item = Task::new("Fix layout");
        item.images = Some("abc123.png,def456.jpg".into());
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(prompt.contains("abc123.png"));
        assert!(prompt.contains("def456.jpg"));
        assert!(prompt.contains("Attached Images"));
    }

    #[test]
    fn build_prompt_rejects_path_traversal_images() {
        let workflow = CaptainWorkflow::compiled_default();
        let mut item = Task::new("Fix layout");
        item.images = Some("good.png,../../etc/passwd,/absolute/path.jpg".into());
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(prompt.contains("good.png"));
        assert!(!prompt.contains("passwd"));
        assert!(!prompt.contains("/absolute/path.jpg"));
    }

    #[test]
    fn build_prompt_without_images_omits_section() {
        let workflow = CaptainWorkflow::compiled_default();
        let item = Task::new("Fix bug");
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(!prompt.contains("Attached Images"));
    }

    /// Guards the prompt-side fix for jargon-heavy human-facing questions.
    /// If this section is removed by mistake, the LLM will drift back to
    /// asking devs-to-devs questions referencing function/file names.
    #[test]
    fn build_prompt_includes_human_phrasing_guidance() {
        let workflow = CaptainWorkflow::compiled_default();
        let item = Task::new("Fix bug");
        let prompt = build_clarifier_prompt(&item, None, &workflow).unwrap();
        assert!(prompt.contains("Phrasing the questions you ask the human"));
        assert!(prompt.contains("plain English"));
        assert!(prompt.contains("Avoid code identifiers"));
        assert!(prompt.contains("unanswered human-facing questions only"));
    }

    #[test]
    fn build_interactive_prompt_includes_plain_english_rule() {
        let workflow = CaptainWorkflow::compiled_default();
        let item = Task::new("Fix bug");
        let prompt =
            build_interactive_clarifier_turn_prompt(&item, &workflow, "the answer", None).unwrap();
        assert!(prompt.contains("plain English"));
        assert!(prompt.contains("Avoid code identifiers"));
        assert!(prompt.contains("Do not repeat answered questions"));
    }

    #[test]
    fn parse_unknown_status_escalates() {
        let json = r#"{"status":"pending","context":"ctx"}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Escalate);
    }

    #[test]
    fn parse_ready_status_accepted() {
        let json = r#"{"status":"ready","context":"ctx"}"#;
        let result = parse_clarifier_response(json, "fallback");
        assert_eq!(result.status, ClarifierStatus::Ready);
    }
}
