mod type_decls;

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

use anyhow::{bail, Context, Result};
use api_types::{route_registrations, RouteRegistration, RouteTransport};
use type_decls::known_type_decls;

fn main() -> Result<()> {
    mando_gateway::contract_inventory_link_anchor();
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .context("repo root not found")?;
    let out_dir = repo_root.join("electron/src/shared/daemon-contract");
    let rust_client_path = repo_root.join("rust/crates/gateway-client/src/generated.rs");
    let check_only = env::args().skip(1).any(|arg| arg == "--check");
    let routes = route_registrations();
    ensure_contract_invariants(&routes)?;

    let routes_src = format_typescript(
        repo_root,
        "src/shared/daemon-contract/routes.ts",
        &render_routes_ts(&routes),
    )?;
    let index_src = format_typescript(
        repo_root,
        "src/shared/daemon-contract/index.ts",
        &render_index_ts(&routes)?,
    )?;
    let rust_client_src = format_rust(&render_rust_client(&routes))?;

    if check_only {
        ensure_file_matches(&out_dir.join("routes.ts"), &routes_src)?;
        ensure_file_matches(&out_dir.join("index.ts"), &index_src)?;
        // schemas.ts is derived from index.ts via gen-schemas.mjs.
        let expected_schemas = generate_schemas_from_index(repo_root)?;
        ensure_file_matches(&out_dir.join("schemas.ts"), &expected_schemas)?;
        ensure_file_matches(&rust_client_path, &rust_client_src)?;
        return Ok(());
    }

    fs::create_dir_all(&out_dir)?;
    fs::write(out_dir.join("routes.ts"), routes_src)?;
    fs::write(out_dir.join("index.ts"), &index_src)?;
    // schemas.ts is generated by walking index.ts via TypeScript compiler API.
    // Hooking it here keeps `cargo run -p api-types-codegen` as the single regen entry point.
    let schemas_src = generate_schemas_from_index(repo_root)?;
    fs::write(out_dir.join("schemas.ts"), schemas_src)?;
    fs::write(rust_client_path, rust_client_src)?;
    Ok(())
}

fn format_rust(source: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("failed to spawn rustfmt for generated Rust client")?;
    child
        .stdin
        .as_mut()
        .context("failed to open rustfmt stdin")?
        .write_all(source.as_bytes())
        .context("failed to write generated Rust client to rustfmt")?;
    let output = child
        .wait_with_output()
        .context("failed to read rustfmt output")?;
    if !output.status.success() {
        bail!(
            "rustfmt failed for generated Rust client: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    String::from_utf8(output.stdout).context("rustfmt output was not valid UTF-8")
}

fn generate_schemas_from_index(repo_root: &Path) -> Result<String> {
    let electron_dir = repo_root.join("electron");
    // --stdout flag tells the script to print instead of writing, so Rust controls the file.
    let output = Command::new("node")
        .current_dir(&electron_dir)
        .args(["scripts/gen-schemas.mjs", "--stdout"])
        .output()
        .context("failed to spawn node for gen-schemas.mjs")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("gen-schemas.mjs failed: {stderr}");
    }
    let written =
        String::from_utf8(output.stdout).context("gen-schemas.mjs stdout was not valid UTF-8")?;
    let formatted =
        format_typescript(repo_root, "src/shared/daemon-contract/schemas.ts", &written)?;
    Ok(formatted)
}

fn ensure_file_matches(path: &Path, expected: &str) -> Result<()> {
    let actual = fs::read_to_string(path)
        .with_context(|| format!("failed to read generated file {}", path.display()))?;
    if actual != expected {
        bail!("generated file out of date: {}", path.display());
    }
    Ok(())
}

fn format_typescript(repo_root: &Path, relative_path: &str, source: &str) -> Result<String> {
    let electron_dir = repo_root.join("electron");
    let mut child = Command::new("npm")
        .current_dir(&electron_dir)
        .args(["exec", "--", "prettier", "--stdin-filepath", relative_path])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .with_context(|| format!("failed to spawn prettier for {relative_path}"))?;
    {
        let stdin = child
            .stdin
            .as_mut()
            .context("failed to open prettier stdin")?;
        stdin
            .write_all(source.as_bytes())
            .with_context(|| format!("failed to write prettier input for {relative_path}"))?;
    }
    let output = child
        .wait_with_output()
        .with_context(|| format!("failed to read prettier output for {relative_path}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        bail!("prettier failed for {relative_path}: {stderr}");
    }
    String::from_utf8(output.stdout)
        .with_context(|| format!("prettier output for {relative_path} was not valid UTF-8"))
}

fn push_route_alias(out: &mut String, name: &str, source: &str, predicate: &str) {
    out.push_str(&format!("export type {name} = {{\n"));
    out.push_str(&format!("  [K in {source}]: {predicate};\n"));
    out.push_str(&format!("}}[{source}];\n"));
}

fn ensure_contract_invariants(routes: &[RouteRegistration]) -> Result<()> {
    for route in routes {
        let param_names = path_param_names(route.path);
        if !param_names.is_empty() && route.params_ty.is_none() {
            bail!(
                "route {} {} has path params ({}) but no params type",
                route.method.as_http(),
                route.path,
                param_names.join(", ")
            );
        }
        if matches!(route.transport, RouteTransport::Sse) && route.event_ty.is_none() {
            bail!(
                "route {} {} is SSE but missing an event type",
                route.method.as_http(),
                route.path
            );
        }
    }
    Ok(())
}

fn path_param_names(path: &str) -> Vec<&str> {
    path.split('/')
        .filter_map(|segment| segment.strip_prefix('{').and_then(|s| s.strip_suffix('}')))
        .collect()
}

fn render_routes_ts(routes: &[RouteRegistration]) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by api-types-codegen. Do not edit by hand.\n");
    out.push_str("import type * as Types from './index';\n\n");
    out.push_str(
        "export type RouteTransport = 'json' | 'multipart' | 'sse' | 'static' | 'ndjson';\n",
    );
    out.push_str("export type RouteAuth = 'public' | 'protected';\n\n");
    out.push_str("export interface Routes {\n");
    for route in routes {
        let key = route_key(route);
        out.push_str(&format!("  {}: {{\n", key));
        out.push_str(&format!("    method: '{}';\n", route.method.as_http()));
        out.push_str(&format!("    path: '{}';\n", route.path));
        out.push_str(&format!("    transport: '{}';\n", route.transport.as_str()));
        out.push_str(&format!("    auth: '{}';\n", route.auth.as_str()));
        if let Some(ty) = route.body_ty {
            out.push_str(&format!("    body: {};\n", render_route_type_ref(ty)));
        }
        if let Some(ty) = route.query_ty {
            out.push_str(&format!("    query: {};\n", render_route_type_ref(ty)));
        }
        if let Some(ty) = route.params_ty {
            out.push_str(&format!("    params: {};\n", render_route_type_ref(ty)));
        }
        if let Some(ty) = route.res_ty {
            out.push_str(&format!("    res: {};\n", render_route_type_ref(ty)));
        }
        if let Some(ty) = route.event_ty {
            out.push_str(&format!("    event: {};\n", render_route_type_ref(ty)));
        }
        out.push_str("  };\n");
    }
    out.push_str("}\n\n");
    for (name, source, predicate) in [
        (
            "JsonRouteKey",
            "keyof Routes",
            "Routes[K]['transport'] extends 'json' ? K : never",
        ),
        (
            "GetJsonRouteKey",
            "JsonRouteKey",
            "Routes[K]['method'] extends 'GET' ? K : never",
        ),
        (
            "PostJsonRouteKey",
            "JsonRouteKey",
            "Routes[K]['method'] extends 'POST' ? K : never",
        ),
        (
            "PutJsonRouteKey",
            "JsonRouteKey",
            "Routes[K]['method'] extends 'PUT' ? K : never",
        ),
        (
            "PatchJsonRouteKey",
            "JsonRouteKey",
            "Routes[K]['method'] extends 'PATCH' ? K : never",
        ),
        (
            "DeleteJsonRouteKey",
            "JsonRouteKey",
            "Routes[K]['method'] extends 'DELETE' ? K : never",
        ),
    ] {
        push_route_alias(&mut out, name, source, predicate);
    }
    out.push_str(
        "export type MutationJsonRouteKey = PostJsonRouteKey | PutJsonRouteKey | PatchJsonRouteKey | DeleteJsonRouteKey;\n",
    );
    for (name, source, predicate) in [
        (
            "JsonRouteWithBodyKey",
            "JsonRouteKey",
            "Routes[K] extends { body: unknown } ? K : never",
        ),
        (
            "DeleteJsonRouteWithBodyKey",
            "DeleteJsonRouteKey",
            "Routes[K] extends { body: unknown } ? K : never",
        ),
        (
            "JsonRouteWithResKey",
            "JsonRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "GetJsonRouteWithResKey",
            "GetJsonRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "PostJsonRouteWithResKey",
            "PostJsonRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "PutJsonRouteWithResKey",
            "PutJsonRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "PatchJsonRouteWithResKey",
            "PatchJsonRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "DeleteJsonRouteWithResKey",
            "DeleteJsonRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "MutationJsonRouteWithResKey",
            "MutationJsonRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "MultipartRouteKey",
            "keyof Routes",
            "Routes[K]['transport'] extends 'multipart' ? K : never",
        ),
        (
            "PostMultipartRouteKey",
            "MultipartRouteKey",
            "Routes[K]['method'] extends 'POST' ? K : never",
        ),
        (
            "MultipartRouteWithResKey",
            "MultipartRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "PostMultipartRouteWithResKey",
            "PostMultipartRouteKey",
            "Routes[K] extends { res: unknown } ? K : never",
        ),
        (
            "SseRouteKey",
            "keyof Routes",
            "Routes[K]['transport'] extends 'sse' ? K : never",
        ),
        (
            "GetSseRouteKey",
            "SseRouteKey",
            "Routes[K]['method'] extends 'GET' ? K : never",
        ),
        (
            "SseRouteWithEventKey",
            "SseRouteKey",
            "Routes[K] extends { event: unknown } ? K : never",
        ),
        (
            "GetSseRouteWithEventKey",
            "GetSseRouteKey",
            "Routes[K] extends { event: unknown } ? K : never",
        ),
    ] {
        push_route_alias(&mut out, name, source, predicate);
    }
    out.push_str("export type StaticRouteKey = {\n");
    out.push_str("  [K in keyof Routes]: Routes[K]['transport'] extends 'static' ? K : never;\n");
    out.push_str("}[keyof Routes];\n");
    out.push_str("export type NdjsonRouteKey = {\n");
    out.push_str("  [K in keyof Routes]: Routes[K]['transport'] extends 'ndjson' ? K : never;\n");
    out.push_str("}[keyof Routes];\n\n");
    out.push_str("export const routes = {\n");
    for route in routes {
        let key = route_key(route);
        out.push_str(&format!(
            "  {}: {{ method: '{}', path: '{}', transport: '{}', auth: '{}' }},\n",
            key,
            route.method.as_http(),
            route.path,
            route.transport.as_str(),
            route.auth.as_str()
        ));
    }
    out.push_str("} as const satisfies Record<keyof Routes, { method: string; path: string; transport: RouteTransport; auth: RouteAuth }>;\n");
    out
}

fn render_index_ts(routes: &[RouteRegistration]) -> Result<String> {
    let decls = known_type_decls();
    let mut route_type_names = BTreeSet::new();
    for route in routes {
        for ty in [
            route.body_ty,
            route.query_ty,
            route.params_ty,
            route.res_ty,
            route.event_ty,
        ]
        .into_iter()
        .flatten()
        {
            collect_route_type_names(ty, &mut route_type_names);
        }
    }
    let missing: Vec<String> = route_type_names
        .iter()
        .filter(|name| !decls.contains_key(*name))
        .cloned()
        .collect();
    if !missing.is_empty() {
        bail!(
            "missing TS declarations for route types: {}",
            missing.join(", ")
        );
    }

    let mut names = route_type_names;
    names.extend(decls.keys().cloned());
    let mut out = String::new();
    out.push_str("// Auto-generated by api-types-codegen. Do not edit by hand.\n");
    for name in names {
        let decl = decls
            .get(&name)
            .with_context(|| format!("missing TS declaration for {name}"))?;
        out.push_str(decl);
    }
    if out.lines().count() == 1 {
        out.push_str("export {};\n");
    }
    Ok(out)
}

fn ts_name(rust_ty: &str) -> String {
    rust_ty
        .rsplit("::")
        .next()
        .unwrap_or(rust_ty)
        .replace(['<', '>', ',', ' ', '&', '[', ']', '(', ')'], "")
}

fn render_route_type_ref(rust_ty: &str) -> String {
    let rust_ty = rust_ty.trim();
    if let Some(inner) = strip_single_generic(rust_ty, "Vec") {
        return format!("Array<{}>", render_route_type_ref(inner));
    }
    if let Some(inner) = strip_single_generic(rust_ty, "Option") {
        return format!("{} | null", render_route_type_ref(inner));
    }
    format!("Types.{}", ts_name(rust_ty))
}

fn collect_route_type_names(rust_ty: &str, names: &mut BTreeSet<String>) {
    let rust_ty = rust_ty.trim();
    if let Some(inner) = strip_single_generic(rust_ty, "Vec") {
        collect_route_type_names(inner, names);
        return;
    }
    if let Some(inner) = strip_single_generic(rust_ty, "Option") {
        collect_route_type_names(inner, names);
        return;
    }
    names.insert(ts_name(rust_ty));
}

fn strip_single_generic<'a>(rust_ty: &'a str, outer: &str) -> Option<&'a str> {
    let rust_ty = rust_ty.trim();
    let prefix = format!("{outer}<");
    if !rust_ty.starts_with(&prefix) || !rust_ty.ends_with('>') {
        return None;
    }
    let inner = &rust_ty[prefix.len()..rust_ty.len() - 1];
    let mut depth = 0usize;
    for ch in inner.chars() {
        match ch {
            '<' => depth += 1,
            '>' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => return None,
            _ => {}
        }
    }
    Some(inner.trim())
}

fn render_rust_client(routes: &[RouteRegistration]) -> String {
    let mut out = String::from(
        "// Generated by api-types-codegen. Do not edit by hand.\n\n\
         pub mod routes {\n\
         use crate::{GatewayClient, Result, RouteDescriptor};\n\n",
    );

    for route in routes {
        out.push_str(&render_rust_descriptor(route));
    }

    out.push_str("\nimpl GatewayClient {\n");
    for route in routes {
        out.push_str(&render_rust_method(route));
    }
    out.push_str("}\n}\n");
    out
}

fn render_rust_descriptor(route: &RouteRegistration) -> String {
    let name = rust_route_const(route);
    format!(
        "pub const {name}: RouteDescriptor = RouteDescriptor {{\n\
         method: api_types::RouteMethod::{method},\n\
         path: {path:?},\n\
         transport: api_types::RouteTransport::{transport:?},\n\
         auth: api_types::RouteAuth::{auth:?},\n\
         params: {params},\n\
         query: {query},\n\
         body: {body},\n\
         response: {response},\n\
         event: {event},\n\
         }};\n\n",
        method = route_method_variant(route),
        path = route.path,
        transport = route.transport,
        auth = route.auth,
        params = rust_option_literal(route.params_ty),
        query = rust_option_literal(route.query_ty),
        body = rust_option_literal(route.body_ty),
        response = rust_option_literal(route.res_ty),
        event = rust_option_literal(route.event_ty),
    )
}

fn render_rust_method(route: &RouteRegistration) -> String {
    match route.transport {
        RouteTransport::Static => render_static_method(route),
        RouteTransport::Sse => String::new(),
        RouteTransport::Ndjson => render_ndjson_method(route),
        RouteTransport::Json => render_json_method(route, &rust_route_method(route)),
        RouteTransport::Multipart => {
            let mut out = render_multipart_method(route);
            if route.path != "/api/tasks/add" {
                out.push_str(&render_json_method(route, &rust_route_method(route)));
            }
            out
        }
    }
}

fn render_static_method(route: &RouteRegistration) -> String {
    let args = rust_route_args(route);
    let signature = join_args(&args);
    let method_name = rust_route_method(route);
    let path = rust_path_setup(route);
    let path_ref = rust_path_ref(route);
    format!(
        "pub async fn {method_name}(&self{signature}) -> Result<Vec<u8>> {{\n\
         {path}\
         self.get_bytes(&{}, {path_ref}).await\n\
         }}\n\n",
        rust_route_const(route)
    )
}

fn render_json_method(route: &RouteRegistration, method_name: &str) -> String {
    let response = route.res_ty.unwrap_or("api_types::EmptyResponse");
    let mut args = rust_route_args(route);
    if let Some(body) = route.body_ty.filter(|ty| *ty != "api_types::EmptyRequest") {
        args.push(format!("body: &{body}"));
    }
    let signature = join_args(&args);
    let path = rust_path_setup(route);
    let path_ref = rust_path_ref(route);
    let body = match route.body_ty {
        Some("api_types::EmptyRequest") => "&api_types::EmptyRequest {}",
        Some(_) => "body",
        None => "",
    };
    let call = match (route.method.as_http(), route.query_ty, route.body_ty) {
        ("GET", Some(_), _) => {
            format!(
                "self.get_json_query(&{}, {path_ref}, query).await",
                rust_route_const(route)
            )
        }
        ("GET", None, _) => {
            format!(
                "self.get_json(&{}, {path_ref}).await",
                rust_route_const(route)
            )
        }
        ("POST", Some(_), Some(_)) => format!(
            "self.post_json_query(&{}, {path_ref}, query, {body}).await",
            rust_route_const(route)
        ),
        ("POST", None, Some(_)) => format!(
            "self.post_json(&{}, {path_ref}, {body}).await",
            rust_route_const(route)
        ),
        ("PUT", _, Some(_)) => format!(
            "self.put_json(&{}, {path_ref}, {body}).await",
            rust_route_const(route)
        ),
        ("PATCH", _, Some(_)) => format!(
            "self.patch_json(&{}, {path_ref}, {body}).await",
            rust_route_const(route)
        ),
        ("DELETE", _, Some(_)) => format!(
            "self.delete_json_body(&{}, {path_ref}, {body}).await",
            rust_route_const(route)
        ),
        ("DELETE", _, None) => format!(
            "self.delete_json(&{}, {path_ref}).await",
            rust_route_const(route)
        ),
        (method, _, _) => format!(
            "compile_error!(\"unsupported generated JSON route shape: {method} {}\")",
            route.path
        ),
    };
    format!(
        "pub async fn {method_name}(&self{signature}) -> Result<{response}> {{\n\
         {path}\
         {call}\n\
         }}\n\n"
    )
}

fn render_multipart_method(route: &RouteRegistration) -> String {
    let response = route.res_ty.unwrap_or("api_types::EmptyResponse");
    let mut args = rust_route_args(route);
    args.push("form: reqwest::multipart::Form".to_string());
    let signature = join_args(&args);
    let method_name = format!("{}_multipart", rust_route_method(route));
    let path = rust_path_setup(route);
    let path_ref = rust_path_ref(route);
    let call = if route.query_ty.is_some() {
        format!(
            "self.post_multipart_query(&{}, {path_ref}, query, form).await",
            rust_route_const(route)
        )
    } else {
        format!(
            "self.post_multipart(&{}, {path_ref}, form).await",
            rust_route_const(route)
        )
    };
    format!(
        "pub async fn {method_name}(&self{signature}) -> Result<{response}> {{\n\
         {path}\
         {call}\n\
         }}\n\n"
    )
}

fn render_ndjson_method(route: &RouteRegistration) -> String {
    let args = rust_route_args(route);
    let signature = join_args(&args);
    let method_name = rust_route_method(route);
    let path = rust_path_setup(route);
    let path_ref = rust_path_ref(route);
    let call = if route.query_ty.is_some() {
        format!(
            "self.get_text_query(&{}, {path_ref}, query).await",
            rust_route_const(route)
        )
    } else {
        format!(
            "compile_error!(\"generated NDJSON route is missing a query type: {}\")",
            route.path
        )
    };
    format!(
        "pub async fn {method_name}(&self{signature}) -> Result<String> {{\n\
         {path}\
         {call}\n\
         }}\n\n"
    )
}

fn rust_route_args(route: &RouteRegistration) -> Vec<String> {
    let mut args = Vec::new();
    if let Some(params) = route.params_ty {
        args.push(format!("params: &{params}"));
    }
    if let Some(query) = route.query_ty {
        args.push(format!("query: &{query}"));
    }
    args
}

fn rust_path_setup(route: &RouteRegistration) -> String {
    let names = path_param_names(route.path);
    if names.is_empty() {
        return String::new();
    }
    let pairs = names
        .iter()
        .map(|name| format!("({name:?}, params.{name}.to_string())"))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "let path = crate::http::render_path(&{}, &[{pairs}]);",
        rust_route_const(route)
    )
}

fn rust_path_ref(route: &RouteRegistration) -> String {
    if path_param_names(route.path).is_empty() {
        format!("{}.path", rust_route_const(route))
    } else {
        "&path".to_string()
    }
}

fn join_args(args: &[String]) -> String {
    if args.is_empty() {
        String::new()
    } else {
        format!(", {}", args.join(", "))
    }
}

fn rust_option_literal(value: Option<&str>) -> String {
    value.map_or_else(|| "None".to_string(), |value| format!("Some({value:?})"))
}

fn rust_route_method(route: &RouteRegistration) -> String {
    snake_case(&route_key(route))
}

fn rust_route_const(route: &RouteRegistration) -> String {
    rust_route_method(route).to_ascii_uppercase()
}

fn route_method_variant(route: &RouteRegistration) -> &'static str {
    match route.method {
        api_types::RouteMethod::Get => "Get",
        api_types::RouteMethod::Post => "Post",
        api_types::RouteMethod::Put => "Put",
        api_types::RouteMethod::Patch => "Patch",
        api_types::RouteMethod::Delete => "Delete",
    }
}

fn snake_case(value: &str) -> String {
    let mut out = String::new();
    for ch in value.chars() {
        if ch.is_ascii_uppercase() {
            if !out.is_empty() {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn route_key(route: &RouteRegistration) -> String {
    let mut parts = vec![route.method.as_http().to_ascii_lowercase()];
    for segment in route.path.trim_start_matches("/api/").split('/') {
        if segment.is_empty() {
            continue;
        }
        if let Some(param) = segment.strip_prefix('{').and_then(|s| s.strip_suffix('}')) {
            parts.push(format!("by{}", capitalize(param)));
        } else {
            parts.push(segment.replace(['{', '}', '-'], ""));
        }
    }

    let mut key = parts.remove(0);
    for part in parts {
        key.push_str(&capitalize(&part));
    }
    key
}

fn capitalize(value: &str) -> String {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
