// Auto-generated by api-types-codegen. Do not edit by hand.
export type ActResponse = {
  ok: boolean | null;
  task_id: string | null;
  title: string | null;
  skipped: boolean | null;
  reason: string | null;
};
export type ActionKind = 'skip' | 'nudge' | 'captain-review';
export type ActivityStatsResponse = { merged_7d: number; daily_merges: Array<DailyMerge> };
export type AddCodexCredentialRequest = {
  label: string;
  /**
   * Raw contents of an OpenAI Codex `auth.json` file. Validated server-side.
   */
  authJson: string;
};
export type AddCodexCredentialResponse = {
  ok: boolean;
  id: number;
  label: string;
  accountId: string;
  planType: string | null;
};
export type AddProjectRequest = { name?: string; path: string; aliases: Array<string> };
export type AdoptRequest = {
  title: string;
  worktree_path: string;
  note?: string;
  project?: string;
};
export type AdvisorActionResponse = { ok: boolean; intent: string; feedback: string };
export type AdvisorAskResponse = {
  id: number;
  ask_id: string;
  message: string;
  answer: string;
  session_id: string;
};
export type AdvisorRequest = { message: string; intent: string };
export type AdvisorResponse =
  | ({ kind: 'ask' } & AdvisorAskResponse)
  | ({ kind: 'action' } & AdvisorActionResponse);
export type ArtifactEventData = { action: string; task_id: number; artifact_id: number };
export type ArtifactIdParams = { id: number };
export type ArtifactMedia = {
  index: number;
  filename: string;
  ext: string;
  local_path: string | null;
  remote_url: string | null;
  caption: string | null;
  kind: EvidenceKind | null;
};
export type ArtifactMediaParams = { id: number; index: number };
export type ArtifactMediaUpdateRequest = { media: Array<ArtifactRemoteUrlPatch> };
export type ArtifactRemoteUrlPatch = { index: number; remote_url: string };
export type ArtifactType = 'evidence' | 'work_summary';
export type ArtifactsPayload = { ts: number; data: ArtifactEventData | null };
export type ArtifactsResponse = { artifacts: Array<TaskArtifact> };
export type AskEndResponse = { ok: boolean; ended: string };
export type AskHistoryEntry = {
  ask_id: string;
  session_id: string;
  role: string;
  content: string;
  timestamp: string;
  intent: string | null;
};
export type AskHistoryResponse = { history: Array<AskHistoryEntry> };
export type AskReopenResponse = { ok: boolean; feedback: string };
export type AskResponse = {
  id: number | null;
  ask_id: string;
  question: string | null;
  answer: string;
  session_id: string | null;
  suggested_followups: Array<string> | null;
};
export type AssistantContentBlock =
  | { kind: 'text'; data: AssistantTextBlock }
  | { kind: 'thinking'; data: AssistantThinkingBlock }
  | { kind: 'tool_use'; data: AssistantToolUseBlock };
export type AssistantEvent = {
  meta: EventMeta;
  model: string | null;
  blocks: Array<AssistantContentBlock>;
  usage: TranscriptUsageInfo | null;
  stopReason: string | null;
};
export type AssistantTextBlock = { text: string };
export type AssistantThinkingBlock = { text: string };
export type AssistantToolUseBlock = { id: string; name: ToolName; input: ToolInput };
export type BashInput = {
  command: string;
  description: string | null;
  timeout: number | null;
  runInBackground: boolean | null;
};
export type BoolOkResponse = { ok: boolean };
export type BoolTouchedResponse = { ok: boolean; touched: boolean };
export type BulkFailure = { id: number; error: string };
export type BulkResultStatus = 'ok' | 'partial' | 'error';
export type CaptainConfig = {
  autoSchedule: boolean;
  autoMerge: boolean;
  maxConcurrentWorkers: number | null;
  tickIntervalS: number;
  tz: string;
  defaultTerminalAgent: TerminalAgent;
  claudeTerminalArgs: string;
  codexTerminalArgs: string;
  projects: { [key in string]: ProjectConfig };
};
export type CcPermissionMode = 'default' | 'acceptEdits' | 'bypassPermissions' | 'plan' | 'dontAsk';
export type CcTodoItem = { content: string; activeForm: string | null; status: CcTodoItemStatus };
export type CcTodoItemStatus = 'pending' | 'in_progress' | 'completed';
export type ChannelStatus = {
  name: string;
  enabled: boolean;
  running: boolean;
  mode: TelegramMode;
  token: string;
  owner: string;
  lastError: string | null;
};
export type ChannelsConfig = { telegram: TelegramConfig };
export type ChannelsResponse = { channels: Array<ChannelStatus> };
export type ClarifierQuestion = {
  question: string;
  answer: string | null;
  self_answered: boolean;
  category: string | null;
};
export type ClarifierQuestionPayload = {
  question: string;
  answer: string | null;
  self_answered: boolean;
  category: string | null;
};
export type ClarifyAnswer = { question: string; answer: string };
export type ClarifyOutcome = 'ready' | 'clarifying' | 'escalate' | 'answered';
export type ClarifyQuery = { wait: boolean | null };
export type ClarifyRequest = { answers?: Array<ClarifyAnswer>; answer?: string };
export type ClarifyResponse = {
  ok: boolean;
  status: ClarifyOutcome;
  context: string | null;
  questions: Array<ClarifierQuestion> | null;
  session_id: string | null;
  error: string | null;
};
export type ClassifyRule = { category: string; patterns: Array<string> };
export type CleanupWorktreesRequest = { dry_run?: boolean };
export type ClientLogBatchRequest = { entries: Array<ClientLogEntry> };
export type ClientLogBatchResponse = { accepted: number };
export type ClientLogContext = {
  source: string | null;
  component: string | null;
  file: string | null;
  line: number | null;
  stack: string | null;
  sessionId: string | null;
  route: string | null;
  extra: string | null;
};
export type ClientLogEntry = {
  level: string;
  message: string;
  context: ClientLogContext | null;
  timestamp: string | null;
};
export type CodexActivateResponse = { ok: boolean; accountId: string };
export type CodexActiveResponse = {
  activeAccountId: string | null;
  matchedCredentialId: number | null;
};
export type CodexCredentialDetails = {
  accountId: string;
  planType: string | null;
  creditsBalance: string | null;
  creditsUnlimited: boolean;
};
export type ConfigPathsResponse = {
  dataDir: string;
  configPath: string;
  taskDbPath: string;
  workerHealthPath: string;
  lockfilePath: string;
  configuredTaskDbPath: string;
  configuredWorkerHealthPath: string;
  configuredLockfilePath: string;
  restartRequired: boolean;
};
export type ConfigPayload = { ts: number; data: MandoConfig | null };
export type ConfigSaveResponse = {
  ok: boolean;
  restartRequired: boolean;
  taskDbPath: string;
  workerHealthPath: string;
  lockfilePath: string;
};
export type ConfigSetupRequest = { config?: MandoConfig };
export type ConfigSetupResponse = { ok: boolean };
export type ConfigStatusResponse = {
  exists: boolean;
  setupComplete: boolean;
  error: string | null;
  taskDbPath: string;
  workerHealthPath: string;
  lockfilePath: string;
  configuredTaskDbPath: string;
  configuredWorkerHealthPath: string;
  configuredLockfilePath: string;
  restartRequired: boolean;
};
export type ConfigWriteResponse = {
  ok: boolean;
  restartRequired: boolean;
  taskDbPath: string;
  workerHealthPath: string;
  lockfilePath: string;
};
export type CreateWorktreeRequest = { name?: string; project?: string };
export type CreateWorktreeResponse = {
  ok: boolean;
  path: string;
  branch: string;
  project: string;
  workbenchId: number | null;
};
export type CredentialIdParams = { id: number };
export type CredentialInfo = {
  id: number;
  label: string;
  tokenMasked: string;
  provider: CredentialProvider;
  expiresAt: number | null;
  rateLimitCooldownUntil: number | null;
  createdAt: string;
  isExpired: boolean;
  isRateLimited: boolean;
  fiveHour?: CredentialWindowInfo | null;
  sevenDay?: CredentialWindowInfo | null;
  unifiedStatus?: CredentialRateLimitStatus | null;
  representativeClaim?: string | null;
  lastProbedAt?: number | null;
  costSinceProbeUsd?: number | null;
  /**
   * Set only when `provider == Codex`.
   */
  codex?: CodexCredentialDetails | null;
};
export type CredentialListResponse = { credentials: Array<CredentialInfo> };
export type CredentialMutationResponse = { ok: boolean; error: string | null };
export type CredentialPick = { id: number; label: string; token: string };
export type CredentialPickResponse = { pick: CredentialPick | null };
export type CredentialProbeResponse = { ok: boolean; snapshot: CredentialUsageSnapshot };
export type CredentialProvider = 'claude' | 'codex';
export type CredentialRateLimitStatus = 'allowed' | 'allowed_warning' | 'rejected';
export type CredentialTokenResponse = { token: string };
export type CredentialUsageSnapshot = {
  fiveHour: CredentialWindowInfo;
  sevenDay: CredentialWindowInfo;
  unifiedStatus: CredentialRateLimitStatus;
  representativeClaim: string | null;
  probedAt: number;
};
export type CredentialWindowInfo = {
  utilization: number;
  resetAt: number;
  status: CredentialRateLimitStatus;
};
export type CredentialsEventData = { action: string | null };
export type CredentialsListResponse = { credentials: Array<CredentialInfo> };
export type CredentialsPayload = { ts: number; data: CredentialsEventData | null };
export type DailyMerge = { date: string; count: number };
export type DashboardConfig = { host: string; port: number };
export type DeleteTasksResponse = { ok: boolean; deleted: number; warnings: Array<string> | null };
export type DrainStop = 'idle' | 'max-ticks' | 'wall-clock' | 'until-status' | 'cancelled';
export type EditInput = {
  filePath: string;
  oldString: string;
  newString: string;
  replaceAll: boolean | null;
};
export type EditProjectRequest = {
  rename?: string;
  github_repo?: string;
  clear_github_repo?: boolean;
  aliases?: Array<string>;
  hooks?: { [key in string]: string };
  preamble?: string;
  check_command?: string;
  scout_summary?: string;
  redetect_logo?: boolean;
};
export type EmptyRequest = Record<symbol, never>;
export type EmptyResponse = Record<symbol, never>;
export type ErrorResponse = { error: string };
export type EventIndex = { lineNumber: number };
export type EventMeta = {
  index: EventIndex;
  uuid: string | null;
  parentUuid: string | null;
  sessionId: string | null;
  timestamp: string | null;
  isSidechain: boolean | null;
};
export type EvidenceCreatedResponse = {
  artifact_id: number;
  task_id: number;
  media: Array<ArtifactMedia>;
};
export type EvidenceFileInput = { filename: string; ext: string; caption: string };
export type EvidenceFileRequest = {
  filename: string;
  ext: string;
  caption: string;
  /**
   * Optional typed role. When the task is classified `is_bug_fix`, captain
   * requires at least one `BeforeFix` and one `AfterFix` artifact.
   */
  kind: EvidenceKind | null;
};
export type EvidenceFilesRequest = { files: Array<EvidenceFileInput> };
export type EvidenceKind = 'before_fix' | 'after_fix' | 'cannot_reproduce' | 'other';
export type FeaturesConfig = {
  scout: boolean;
  setupDismissed: boolean;
  claudeCodeVerified: boolean;
};
export type FeedItem =
  | { type: 'timeline'; timestamp: string; data: TimelineEvent }
  | { type: 'artifact'; timestamp: string; data: TaskArtifact }
  | { type: 'message'; timestamp: string; data: AskHistoryEntry };
export type FeedResponse = { id: string; feed: Array<FeedItem>; count: number };
export type FirecrawlScrapeRequest = { url: string };
export type FirecrawlScrapeResponse = { ok: boolean; content: string };
export type GatewayConfig = { dashboard: DashboardConfig };
export type GlobInput = { pattern: string; path: string | null };
export type GrepInput = {
  pattern: string;
  path: string | null;
  glob: string | null;
  fileType: string | null;
  outputMode: GrepOutputMode | null;
  headLimit: number | null;
  caseInsensitive: boolean | null;
  multiline: boolean | null;
};
export type GrepOutputMode = 'content' | 'files_with_matches' | 'count';
export type HealthResponse = { healthy: boolean; version: string; pid: number; uptime: number };
export type HookPhase = 'started' | 'response';
export type ImageFilenameParams = { filename: string };
export type InlineKeyboardButton = {
  text: string;
  callbackData: string | null;
  url: string | null;
};
export type InterestsConfig = { high: Array<string>; low: Array<string> };
export type ItemSessionsResponse = { sessions: Array<SessionSummary>; count: number };
export type ItemStatus =
  | 'new'
  | 'clarifying'
  | 'needs-clarification'
  | 'queued'
  | 'in-progress'
  | 'captain-reviewing'
  | 'captain-merging'
  | 'awaiting-review'
  | 'rework'
  | 'handed-off'
  | 'escalated'
  | 'errored'
  | 'merged'
  | 'completed-no-pr'
  | 'plan-ready'
  | 'canceled'
  | 'stopped';
export type MandoConfig = {
  workspace: string;
  ui: UiConfig;
  features: FeaturesConfig;
  channels: ChannelsConfig;
  gateway: GatewayConfig;
  captain: CaptainConfig;
  scout: ScoutConfig;
  env: { [key in string]: string };
};
export type McpServerStatus = { name: string; status: string };
export type McpToolName = { server: string; tool: string };
export type MergeRequest = { pr_number: number; project: string };
export type MergeResponse = { status: ItemStatus; item_id: number; pr: number };
export type MessagesQuery = { limit: number | null; offset: number | null };
export type ModelUsageBreakdown = {
  model: string;
  usage: TranscriptUsageInfo;
  costUsd: number | null;
  contextWindow: number | null;
};
export type NotebookCellType = 'code' | 'markdown';
export type NotebookEditInput = {
  notebookPath: string;
  newSource: string;
  cellId: string | null;
  cellType: NotebookCellType | null;
  editMode: NotebookEditMode | null;
};
export type NotebookEditMode = 'replace' | 'insert' | 'delete';
export type NotificationEventPayload = { ts: number; data: NotificationPayload | null };
export type NotificationKind =
  | { type: 'Escalated'; item_id: string; summary: string | null }
  | { type: 'NeedsClarification'; item_id: string; questions: string | null }
  | {
      type: 'RateLimited';
      status: CredentialRateLimitStatus;
      utilization: number | null;
      resets_at: number | null;
      rate_limit_type: string | null;
      overage_status: CredentialRateLimitStatus | null;
      overage_resets_at: number | null;
      overage_disabled_reason: string | null;
    }
  | {
      type: 'ScoutProcessed';
      scout_id: number;
      title: string;
      relevance: number;
      quality: number;
      source_name: string | null;
      telegraph_url: string | null;
    }
  | { type: 'ScoutProcessFailed'; scout_id: number; url: string; error: string }
  | { type: 'AdvisorAnswered'; item_id: string; title: string }
  | { type: 'Generic' };
export type NotificationPayload = {
  message: string;
  level: NotifyLevel;
  kind: NotificationKind;
  task_key: string | null;
  reply_markup: TelegramReplyMarkup | null;
};
export type NotifyLevel = 'Low' | 'Normal' | 'High' | 'Critical';
export type NotifyRequest = { message: string; chat_id: string | null };
export type NotifyResponse = { ok: boolean; chat_id: string };
export type NudgeRequest = { item_id: string; message: string };
export type NudgeResponse = {
  ok: boolean;
  worker: string | null;
  pid: number | null;
  status: ItemStatus | null;
  alerts: Array<string> | null;
};
export type OpaqueInput = { raw: string };
export type OtherToolName = { name: string };
export type ParseTodosRequest = { text: string; project: string };
export type ParseTodosResponse = { items: Array<string> };
export type PermissionDenial = {
  toolName: string | null;
  toolUseId: string | null;
  reason: string | null;
};
export type PrSummaryResponse = {
  pr_number: number | null;
  summary: string | null;
  summary_error: string | null;
};
export type ProbeCredentialResponse = {
  ok: boolean;
  snapshot: CredentialUsageSnapshot | null;
  error: string | null;
};
export type ProcessResponse = { ok: boolean; processed: number };
export type ProjectAddResponse = {
  ok: boolean;
  name: string;
  path: string;
  githubRepo: string | null;
  logo: string | null;
};
export type ProjectConfig = {
  name: string;
  path: string;
  githubRepo: string | null;
  logo: string | null;
  aliases: Array<string>;
  hooks: { [key in string]: string };
  workerPreamble: string;
  scoutSummary: string;
  checkCommand: string;
  classifyRules: Array<ClassifyRule>;
};
export type ProjectDeleteResponse = { ok: boolean; deleted_tasks: number };
export type ProjectNameParams = { name: string };
export type ProjectPatchResponse = { ok: boolean; logo: string | null };
export type ProjectSummary = {
  key: string;
  name: string;
  path: string;
  githubRepo: string | null;
  logo: string | null;
  aliases: Array<string>;
  hooks: { [key in string]: string };
  workerPreamble: string;
  scoutSummary: string;
  checkCommand: string;
};
export type ProjectUpsertResponse = {
  ok: boolean;
  name: string;
  path: string;
  githubRepo: string | null;
  logo: string | null;
};
export type ProjectsListResponse = { projects: Array<ProjectSummary> };
export type ReadInput = {
  filePath: string;
  offset: number | null;
  limit: number | null;
  pages: string | null;
};
export type RemoveWorktreeRequest = { path: string };
export type ResearchError = { url: string; error: string };
export type ResearchEventData = {
  action: string;
  run_id: number;
  research_prompt: string | null;
  elapsed_s: number | null;
  links: Array<ResearchLink> | null;
  errors: Array<ResearchError> | null;
  added_count: number | null;
  error: string | null;
};
export type ResearchLink = {
  url: string;
  title: string;
  type: string;
  reason: string;
  id: number | null;
  added: boolean;
};
export type ResearchPayload = { ts: number; data: ResearchEventData | null };
export type ResearchStartResponse = { run_id: number };
export type ResultEvent = { meta: EventMeta; outcome: ResultOutcome; summary: ResultSummary };
export type ResultOutcome =
  | 'success'
  | 'error_during_execution'
  | 'error_max_turns'
  | 'error_max_budget_usd'
  | 'error_max_structured_output_retries';
export type ResultSummary = {
  durationMs: number | null;
  durationApiMs: number | null;
  numTurns: number | null;
  totalCostUsd: number | null;
  stopReason: string | null;
  permissionDenials: Array<PermissionDenial>;
  errors: Array<string>;
  usage: TranscriptUsageInfo | null;
  modelUsage: Array<ModelUsageBreakdown>;
  isError: boolean;
};
export type ResyncPayload = { ts: number; data: SseResyncData };
export type ReviewTrigger =
  | 'gates_pass'
  | 'timeout'
  | 'broken_session'
  | 'budget_exhausted'
  | 'clarifier_fail'
  | 'spawn_fail'
  | 'rebase_fail'
  | 'ci_failure'
  | 'degraded_context'
  | 'retry'
  | 'captain_decision'
  | 'merge_fail'
  | 'repeated_nudge';
export type ScoutActRequest = { project: string; prompt?: string };
export type ScoutAddRequest = { url: string; title?: string };
export type ScoutAddResponse = {
  added: boolean;
  id: number;
  url: string;
  type: string;
  status: ScoutItemStatus;
};
export type ScoutArticleResponse = {
  id: number;
  title: string | null;
  article: string | null;
  telegraphUrl: string | null;
};
export type ScoutAskRequest = { id: number; question: string; session_id?: string };
export type ScoutBulkCommandRequest = { ids: Array<number>; command: ScoutItemLifecycleCommand };
export type ScoutBulkDeleteRequest = { ids: Array<number> };
export type ScoutBulkDeleteResponse = {
  deleted: number;
  failed: Array<BulkFailure>;
  status: BulkResultStatus;
};
export type ScoutBulkUpdateResponse = {
  updated: number;
  failed: Array<BulkFailure>;
  status: BulkResultStatus;
};
export type ScoutConfig = { interests: InterestsConfig; userContext: UserContextConfig };
export type ScoutDeleteResponse = { removed: boolean; id: number };
export type ScoutEventData = { action: string | null; item: ScoutItem | null; id: number | null };
export type ScoutItem = {
  id: number;
  rev: number;
  url: string;
  title: string | null;
  status: ScoutItemStatus;
  item_type: string | null;
  summary: string | null;
  has_summary: boolean | null;
  relevance: number | null;
  quality: number | null;
  date_added: string | null;
  date_processed: string | null;
  added_by: string | null;
  source_name: string | null;
  date_published: string | null;
  error_count: number | null;
  research_run_id: number | null;
  telegraphUrl: string | null;
};
export type ScoutItemIdParams = { id: number };
export type ScoutItemLifecycleCommand = 'mark_pending' | 'mark_processed' | 'save' | 'archive';
export type ScoutItemSession = {
  session_id: string;
  caller: string;
  status: SessionStatus;
  created_at: string;
  model: string | null;
  duration_ms: number | null;
  cost_usd: number | null;
};
export type ScoutItemStatus = 'pending' | 'fetched' | 'processed' | 'saved' | 'archived' | 'error';
export type ScoutItemStatusFilter =
  | 'all'
  | 'pending'
  | 'fetched'
  | 'processed'
  | 'saved'
  | 'archived'
  | 'error';
export type ScoutLifecycleCommandRequest = { command: ScoutItemLifecycleCommand };
export type ScoutPayload = { ts: number; data: ScoutEventData | null };
export type ScoutProcessRequest = { id?: number };
export type ScoutQuery = {
  status: ScoutItemStatusFilter | null;
  q: string | null;
  type: string | null;
  page: number | null;
  per_page: number | null;
};
export type ScoutResearchIdParams = { id: number };
export type ScoutResearchRequest = { topic: string; process?: boolean };
export type ScoutResearchRun = {
  id: number;
  research_prompt: string;
  status: ScoutResearchRunStatus;
  error: string | null;
  session_id: string | null;
  added_count: number;
  created_at: string;
  completed_at: string | null;
  rev: number;
};
export type ScoutResearchRunStatus = 'running' | 'done' | 'failed';
export type ScoutResponse = {
  items: Array<ScoutItem>;
  count: number;
  total: number;
  page: number;
  pages: number;
  per_page: number;
  filter: string | null;
  status_counts: { [key in string]: number } | null;
};
export type SessionCategory =
  | 'workers'
  | 'clarifier'
  | 'captain-review'
  | 'captain-ops'
  | 'advisor'
  | 'planning'
  | 'todo-parser'
  | 'scout'
  | 'rebase';
export type SessionCostResponse = { cost: SessionCostSummary };
export type SessionCostSummary = {
  total_input_tokens: number;
  total_output_tokens: number;
  total_cache_read_tokens: number;
  total_cache_creation_tokens: number;
  turn_count: number;
  total_cost_usd: number | null;
};
export type SessionEntry = {
  session_id: string;
  created_at: string;
  cwd: string;
  model: string;
  caller: string;
  resumed: boolean;
  cost_usd: number | null;
  duration_ms: number | null;
  turn_count: number | null;
  scout_item_id: number | null;
  task_id: string | null;
  worker_name: string | null;
  resumed_at: string | null;
  status: SessionStatus;
  task_title: string | null;
  scout_item_title: string | null;
  github_repo: string | null;
  pr_number: number | null;
  worktree: string | null;
  branch: string | null;
  resume_cwd: string | null;
  category: SessionCategory | null;
  credential_id: number | null;
  credential_label: string | null;
  error: string | null;
  api_error_status: number | null;
};
export type SessionIdParams = { id: string };
export type SessionIds = {
  worker: string | null;
  review: string | null;
  clarifier: string | null;
  merge: string | null;
  ask: string | null;
  advisor: string | null;
};
export type SessionJsonlPathResponse = { session_id: string; path: string | null };
export type SessionMessagesQuery = { limit: number | null; offset: number | null };
export type SessionMessagesResponse = { messages: Array<TranscriptMessage> };
export type SessionStatus = 'running' | 'stopped' | 'failed';
export type SessionStreamQuery = { types?: string };
export type SessionSummary = {
  session_id: string;
  status: SessionStatus;
  caller: string;
  started_at: string;
  duration_ms: number | null;
  cost_usd: number | null;
  model: string | null;
  resumed: boolean;
  cwd: string | null;
  worker_name: string | null;
};
export type SessionToolUsageResponse = { tools: Array<SessionToolUsageSummary> };
export type SessionToolUsageSummary = { name: string; call_count: number; error_count: number };
export type SessionsEventData = { affected_task_ids: Array<number> | null };
export type SessionsListResponse = {
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
  categories: { [key in string]: number };
  total_cost_usd: number;
  sessions: Array<SessionEntry>;
};
export type SessionsPayload = { ts: number; data: SessionsEventData | null };
export type SessionsQuery = {
  page: number | null;
  per_page: number | null;
  category: SessionCategory | null;
  /**
   * Alias for category -- accepted from CLI which sends `caller=`.
   */
  caller: SessionCategory | null;
  status: SessionStatus | null;
};
export type SessionsResponse = {
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
  categories: { [key in string]: number };
  total_cost_usd: number | null;
  sessions: Array<SessionEntry>;
};
export type SetupTokenRequest = { label: string; token: string };
export type SetupTokenResponse = { ok: boolean; id: number | null; label: string | null };
export type SkillInput = { skill: string; args: string | null };
export type SnapshotErrorPayload = { ts: number; data: SseSnapshotErrorData };
export type SnapshotPayload = { ts: number; data: SseSnapshotData };
export type SseDaemonInfo = { version: string; uptime: number };
export type SseEnvelope =
  | { event: 'snapshot'; data: SnapshotPayload }
  | { event: 'snapshot_error'; data: SnapshotErrorPayload }
  | { event: 'resync'; data: ResyncPayload }
  | { event: 'tasks'; data: TasksPayload }
  | { event: 'scout'; data: ScoutPayload }
  | { event: 'status'; data: StatusPayload }
  | { event: 'sessions'; data: SessionsPayload }
  | { event: 'notification'; data: NotificationEventPayload }
  | { event: 'workbenches'; data: WorkbenchesPayload }
  | { event: 'config'; data: ConfigPayload }
  | { event: 'research'; data: ResearchPayload }
  | { event: 'credentials'; data: CredentialsPayload }
  | { event: 'artifacts'; data: ArtifactsPayload };
export type SseResyncData = { reason: string; reload: Array<string> };
export type SseSnapshotData = {
  tasks: Array<TaskItem>;
  workers: Array<WorkerDetail>;
  workbenches: Array<WorkbenchItem>;
  terminals: Array<TerminalSessionInfo>;
  config: MandoConfig;
  daemon: SseDaemonInfo;
};
export type SseSnapshotErrorData = { message: string; retry: boolean };
export type StatusEventData = { action: string | null; affected_task_ids: Array<number> | null };
export type StatusPayload = { ts: number; data: StatusEventData | null };
export type StopWorkersResponse = { killed: number };
export type StructuredOutputInput = { raw: string };
export type SummaryCreatedResponse = { artifact_id: number; task_id: number };
export type SystemApiRetryEvent = {
  meta: EventMeta;
  message: string | null;
  retryInMs: number | null;
  attempt: number | null;
};
export type SystemCompactBoundaryEvent = { meta: EventMeta; reason: string | null };
export type SystemHealthResponse = {
  healthy: boolean;
  version: string;
  pid: number;
  uptime: number;
  active_workers: number;
  total_items: number;
  captain_degraded: boolean;
  projects: Array<string>;
  dataDir: string;
  configPath: string;
  taskDbPath: string;
  workerHealthPath: string;
  lockfilePath: string;
  configuredTaskDbPath: string;
  configuredWorkerHealthPath: string;
  configuredLockfilePath: string;
  restartRequired: boolean;
  telegram: TelegramHealth;
  ui: UiHealthResponse;
};
export type SystemHookEvent = {
  meta: EventMeta;
  phase: HookPhase;
  hookId: string | null;
  hookName: string | null;
  hookEvent: string | null;
  output: string | null;
  stdout: string | null;
  stderr: string | null;
};
export type SystemInitEvent = {
  meta: EventMeta;
  cwd: string | null;
  model: string | null;
  permissionMode: CcPermissionMode | null;
  tools: Array<string>;
  slashCommands: Array<string>;
  mcpServers: Array<McpServerStatus>;
  outputStyle: string | null;
};
export type SystemLocalCommandOutputEvent = {
  meta: EventMeta;
  command: string | null;
  output: string;
};
export type SystemRateLimitEvent = { meta: EventMeta; info: string };
export type SystemStatusEvent = { meta: EventMeta; status: string | null; message: string | null };
export type TaskAddRequest = {
  title: string;
  project: string | null;
  plan: boolean;
  no_pr: boolean;
};
export type TaskArtifact = {
  id: number;
  task_id: number;
  artifact_type: ArtifactType;
  content: string;
  media: Array<ArtifactMedia>;
  created_at: string;
};
export type TaskAskRequest = { id: number; question: string; ask_id?: string };
export type TaskBulkRequest = { ids: Array<number>; updates: TaskBulkUpdates };
export type TaskBulkUpdateRequest = { ids: Array<number>; updates: TaskBulkUpdates };
export type TaskBulkUpdates = { worker?: string };
export type TaskCreateResponse = { id: number; title: string };
export type TaskDeleteRequest = { ids: Array<number>; close_pr?: boolean; force?: boolean };
export type TaskEventData = {
  action: string | null;
  item: TaskItem | null;
  id: number | null;
  cleared_by: string | null;
};
export type TaskEvidenceRequest = { files: Array<EvidenceFileRequest> };
export type TaskEvidenceResponse = {
  artifact_id: number;
  task_id: number;
  media: Array<ArtifactMedia>;
};
export type TaskFeedbackRequest = { id: number; feedback: string };
export type TaskIdParams = { id: number };
export type TaskIdRequest = { id: number };
export type TaskInput = { description: string; prompt: string; subagentType: string | null };
export type TaskItem = {
  id: number;
  rev: number;
  title: string;
  status: ItemStatus;
  project: string | null;
  github_repo: string | null;
  branch: string | null;
  pr_number: number | null;
  project_id: number | null;
  worker: string | null;
  session_ids: SessionIds | null;
  intervention_count: number;
  captain_review_trigger: ReviewTrigger | null;
  escalation_report: string | null;
  context: string | null;
  original_prompt: string | null;
  workbench_id: number;
  worktree: string | null;
  plan: string | null;
  no_pr: boolean;
  no_auto_merge: boolean;
  planning: boolean;
  /**
   * Set by the clarifier when it identifies the task as fixing existing
   * broken behavior (vs. a new feature, refactor, or research). Worker
   * prompts use this to require reproduce-first + before-state evidence;
   * captain review requires both before+after evidence to ship.
   */
  is_bug_fix: boolean;
  resource: string | null;
  images: string | null;
  created_at: string | null;
  last_activity_at: string | null;
  worker_started_at: string | null;
  worker_seq: number;
  reopen_seq: number;
  reopened_at: string | null;
  reopen_source: string | null;
  review_fail_count: number;
  clarifier_fail_count: number;
  spawn_fail_count: number;
  merge_fail_count: number;
  source: string | null;
  /**
   * Unix seconds after which captain may dispatch this task again.
   * Set when every healthy credential is in rate-limit cooldown and
   * the failover layer surfaces `AllCredentialsExhausted`. Captain
   * tick excludes tasks where `paused_until > unixepoch()`; UI shows
   * "Paused until HH:MM". `None` means not paused.
   */
  paused_until: number | null;
};
export type TaskListQuery = { include_archived: boolean | null };
export type TaskListResponse = { items: Array<TaskItem>; count: number };
export type TaskPatchRequest = {
  context?: string;
  original_prompt?: string;
  /**
   * Manual override for the clarifier's bug-fix classification. Sent from
   * the task editor when the user disagrees with the auto-classified value
   * (or wants to correct it after a misread). The captain workflow reads
   * this on the next worker spawn and captain review tick.
   */
  is_bug_fix?: boolean;
};
export type TaskSummaryRequest = { content: string };
export type TaskSummaryResponse = { artifact_id: number; task_id: number };
export type TasksPayload = { ts: number; data: TaskEventData | null };
export type TelegramConfig = { enabled: boolean; owner: string };
export type TelegramHealth = {
  enabled: boolean;
  running: boolean;
  owner: string;
  lastError: string | null;
  degraded: boolean;
  restartCount: number;
  mode: TelegramMode;
};
export type TelegramMode = 'embedded';
export type TelegramOwnerRequest = { owner: string };
export type TelegramReplyMarkup =
  | { kind: 'inlineKeyboard'; rows: Array<Array<InlineKeyboardButton>> }
  | {
      kind: 'replyKeyboard';
      rows: Array<Array<string>>;
      one_time: boolean;
      resize: boolean;
      persistent: boolean;
    }
  | { kind: 'forceReply' }
  | { kind: 'removeKeyboard' };
export type TelegraphPublishResponse = { ok: boolean; url: string };
export type TerminalAgent = 'claude' | 'codex';
export type TerminalCcSessionRequest = { ccSessionId: string };
export type TerminalCreateRequest = {
  project: string;
  cwd: string;
  agent: TerminalAgent;
  resume_session_id?: string;
  size?: TerminalSize;
  terminal_id?: string;
  name?: string;
};
export type TerminalExitPayload = { code: number | null };
export type TerminalIdParams = { id: string };
export type TerminalOutputPayload = { dataB64: string };
export type TerminalSessionInfo = {
  id: string;
  rev: number;
  project: string;
  cwd: string;
  agent: TerminalAgent;
  running: boolean;
  exit_code: number | null;
  state: TerminalState | null;
  restored: boolean | null;
  createdAt: string | null;
  endedAt: string | null;
  terminalId: string | null;
  name: string | null;
  ccSessionId: string | null;
};
export type TerminalSize = { rows: number; cols: number };
export type TerminalState = 'live' | 'restored' | 'exited';
export type TerminalStreamEnvelope =
  | { event: 'output'; data: TerminalOutputPayload }
  | { event: 'exit'; data: TerminalExitPayload };
export type TerminalStreamQuery = { replay: number | null };
export type TerminalWriteRequest = { data: string };
export type TickAction = {
  worker: string;
  action: ActionKind;
  message: string | null;
  reason: string | null;
};
export type TickDrainResult = {
  iterations: number;
  stopped_reason: DrainStop;
  /**
   * Wall-clock duration of the drain, in milliseconds.
   */
  elapsed_ms: number;
  /**
   * Final tick's `TickResult`. Always present — even a 0-iteration drain
   * (no-op request) surfaces the last tick it ran, and the guarded empty
   * result when nothing ran.
   */
  last: TickResult;
};
export type TickMode = 'live' | 'dry-run' | 'skipped';
export type TickRequest = {
  dry_run?: boolean;
  emit_notifications?: boolean;
  /**
   * Drain ticks until a pass reports no state changes (iterations converge),
   * or until a cap trips.
   */
  until_idle?: boolean;
  /**
   * Hard upper bound on ticks in this call. Clamped to a server-side
   * ceiling so a misbehaving caller can't peg the daemon.
   */
  max_ticks?: number;
  /**
   * Drain until the task identified by `task_id` reaches any of these
   * statuses. Requires `task_id`; a value without `task_id` is a 400.
   */
  until_status?: Array<ItemStatus>;
  /**
   * Target task for `until_status`.
   */
  task_id?: number;
};
export type TickResult = {
  mode: TickMode;
  tick_id: string | null;
  max_workers: number;
  active_workers: number;
  tasks: { [key in string]: number };
  alerts: Array<string>;
  dry_actions: Array<TickAction>;
  error: string | null;
  rate_limited: boolean;
};
export type TimelineEvent = {
  timestamp: string;
  actor: string;
  summary: string;
  /**
   * Tagged by `event_type`. See [`crate::TimelineEventPayload`] variants
   * for the exact shape per event kind.
   */
  data: TimelineEventPayload;
};
export type TimelineEventPayload =
  | { event_type: 'created'; source: string }
  | { event_type: 'clarify_started'; session_id: string }
  | {
      event_type: 'clarify_question';
      session_id: string;
      questions: Array<ClarifierQuestionPayload>;
    }
  | { event_type: 'clarify_timeout'; timeout_s: number }
  | { event_type: 'clarify_resolved'; session_id: string }
  | { event_type: 'human_answered'; answer: string }
  | { event_type: 'worker_spawned'; worker: string; session_id: string }
  | { event_type: 'planning_spawned'; worker: string; session_id: string }
  | {
      event_type: 'worker_nudged';
      worker: string;
      session_id: string;
      content: string;
      reason: string;
      nudge_count: number;
    }
  | {
      event_type: 'worker_nudge_failed';
      worker: string;
      session_id: string;
      reason: string;
      nudge_count_attempted: number;
      error: string;
    }
  | { event_type: 'session_resumed'; worker: string; session_id: string }
  | { event_type: 'worker_completed' }
  | { event_type: 'captain_review_started'; trigger: string; session_id: string }
  | {
      event_type: 'captain_review_merge_fail';
      trigger: string;
      fail_count: number;
      error: string;
      retries: number;
    }
  | { event_type: 'captain_review_clarifier_fail'; trigger: string; fail_count: number }
  | { event_type: 'captain_review_ci_failure'; trigger: string }
  | {
      event_type: 'captain_review_rebase_exhausted';
      trigger: string;
      pr: string;
      retries: number;
      reason: string;
    }
  | {
      event_type: 'captain_review_verdict';
      action: string;
      feedback: string;
      confidence: string;
      confidence_reason: string;
      reviewed_head_sha: string;
    }
  | {
      event_type: 'captain_review_retry';
      action: string;
      feedback: string;
      error: string;
      fail_count: number;
    }
  | { event_type: 'captain_merge_started'; session_id: string; pr: string }
  | { event_type: 'captain_merge_queued'; pr: string; source: string; confidence_reason: string }
  | { event_type: 'captain_merge_retry'; error: string; fail_count: number }
  | { event_type: 'auto_merge_triage' }
  | { event_type: 'auto_merge_triage_failed' }
  | { event_type: 'auto_merge_triage_exhausted' }
  | {
      event_type: 'awaiting_review';
      action: string;
      feedback: string;
      confidence: string;
      confidence_reason: string;
      reviewed_head_sha: string;
    }
  | {
      event_type: 'human_reopen';
      content: string;
      worker: string;
      session_id: string;
      from: ItemStatus;
      to: ItemStatus;
      source: string;
    }
  | { event_type: 'human_ask'; question: string; intent: string; ask_id: string }
  | {
      event_type: 'rebase_triggered';
      worker: string;
      session_id: string;
      pr: string;
      attempt: number;
      max_retries: number;
    }
  | { event_type: 'rework_requested'; content: string; to: ItemStatus }
  | { event_type: 'merged'; pr: string; source: string; accepted_by: string }
  | { event_type: 'accepted_no_pr'; accepted_by: string }
  | {
      event_type: 'escalated';
      action: string;
      feedback: string;
      confidence: string;
      confidence_reason: string;
      reviewed_head_sha: string;
    }
  | { event_type: 'review_errored'; error: string; fail_count: number }
  | {
      event_type: 'clarifier_failed';
      session_id: string;
      api_error_status: number;
      message: string;
    }
  | { event_type: 'canceled'; pr: string }
  | { event_type: 'canceled_by_human'; canceled_by: string }
  | { event_type: 'handed_off'; to: ItemStatus; handed_off_by: string }
  | { event_type: 'stopped'; stopped_by: string }
  | {
      event_type: 'completed_no_pr';
      action: string;
      feedback: string;
      confidence: string;
      confidence_reason: string;
      reviewed_head_sha: string;
    }
  | { event_type: 'clarifier_completed_no_pr'; session_id: string }
  | { event_type: 'status_changed'; from: ItemStatus; to: ItemStatus }
  | { event_type: 'status_changed_by_command'; from: ItemStatus; to: ItemStatus; command: string }
  | { event_type: 'status_changed_queued'; to: ItemStatus; reason: string }
  | { event_type: 'status_changed_retry_merge'; from: ItemStatus; to: ItemStatus; pr: number }
  | {
      event_type: 'status_changed_clarifier_fail';
      from: ItemStatus;
      to: ItemStatus;
      session_id: string;
      error: string;
    }
  | { event_type: 'rate_limited'; remaining_secs: number; retry_at: string }
  | { event_type: 'rate_limit_cleared'; action: string; cleared_by: string }
  | {
      event_type: 'worker_reopened';
      source: string;
      reopen_seq: number;
      outcome: string;
      feedback: string;
      worker: string;
      session_id: string;
    }
  | { event_type: 'human_ask_failed'; question: string; error: string }
  | { event_type: 'evidence_updated' }
  | { event_type: 'work_summary_updated' }
  | {
      event_type: 'planning_round';
      round: number;
      cc_feedback_len: number;
      codex_feedback_len: number;
    }
  | { event_type: 'plan_completed'; diagram: string; plan: string }
  | { event_type: 'plan_ready' };
export type TimelineResponse = { id: string; events: Array<TimelineEvent>; count: number };
export type TodoWriteInput = { todos: Array<CcTodoItem> };
export type TokenResponse = { token: string };
export type ToolInput =
  | { kind: 'bash'; data: BashInput }
  | { kind: 'read'; data: ReadInput }
  | { kind: 'edit'; data: EditInput }
  | { kind: 'write'; data: WriteInput }
  | { kind: 'grep'; data: GrepInput }
  | { kind: 'glob'; data: GlobInput }
  | { kind: 'todo_write'; data: TodoWriteInput }
  | { kind: 'web_fetch'; data: WebFetchInput }
  | { kind: 'web_search'; data: WebSearchInput }
  | { kind: 'task'; data: TaskInput }
  | { kind: 'notebook_edit'; data: NotebookEditInput }
  | { kind: 'skill'; data: SkillInput }
  | { kind: 'structured_output'; data: StructuredOutputInput }
  | { kind: 'opaque'; data: OpaqueInput };
export type ToolName =
  | { kind: 'bash' }
  | { kind: 'read' }
  | { kind: 'edit' }
  | { kind: 'write' }
  | { kind: 'grep' }
  | { kind: 'glob' }
  | { kind: 'todo_write' }
  | { kind: 'web_fetch' }
  | { kind: 'web_search' }
  | { kind: 'task' }
  | { kind: 'notebook_edit' }
  | { kind: 'skill' }
  | { kind: 'structured_output' }
  | { kind: 'mcp'; data: McpToolName }
  | { kind: 'other'; data: OtherToolName };
export type ToolProgressEvent = {
  meta: EventMeta;
  toolUseId: string;
  toolName: ToolName;
  elapsedSeconds: number | null;
};
export type ToolResultBlocks = { blocks: Array<ToolResultChildBlock> };
export type ToolResultChildBlock =
  | { kind: 'text'; data: ToolResultText }
  | { kind: 'image'; data: UserImageBlock }
  | { kind: 'unknown'; data: ToolResultUnknownBlock };
export type ToolResultContent =
  | { kind: 'text'; data: ToolResultText }
  | { kind: 'blocks'; data: ToolResultBlocks };
export type ToolResultText = { text: string };
export type ToolResultUnknownBlock = { raw: string };
export type TranscriptConnectionClosed = { reason: string };
export type TranscriptEvent =
  | { kind: 'system_init'; data: SystemInitEvent }
  | { kind: 'system_compact_boundary'; data: SystemCompactBoundaryEvent }
  | { kind: 'system_status'; data: SystemStatusEvent }
  | { kind: 'system_api_retry'; data: SystemApiRetryEvent }
  | { kind: 'system_local_command_output'; data: SystemLocalCommandOutputEvent }
  | { kind: 'system_hook'; data: SystemHookEvent }
  | { kind: 'system_rate_limit'; data: SystemRateLimitEvent }
  | { kind: 'user'; data: UserEvent }
  | { kind: 'assistant'; data: AssistantEvent }
  | { kind: 'tool_progress'; data: ToolProgressEvent }
  | { kind: 'result'; data: ResultEvent }
  | { kind: 'unknown'; data: UnknownEvent };
export type TranscriptEventEnvelope =
  | { event: 'snapshot'; data: TranscriptSnapshotBatch }
  | { event: 'snapshot_complete'; data: TranscriptSnapshotComplete }
  | { event: 'event'; data: TranscriptEvent }
  | { event: 'connection_closed'; data: TranscriptConnectionClosed }
  | { event: 'error'; data: TranscriptStreamError };
export type TranscriptEventsResponse = {
  sessionId: string;
  events: Array<TranscriptEvent>;
  isRunning: boolean;
};
export type TranscriptMessage = {
  role: string;
  uuid: string;
  parent_uuid: string | null;
  text: string;
  tool_calls: Array<TranscriptToolCall>;
  usage: TranscriptUsageInfo | null;
};
export type TranscriptSnapshotBatch = { events: Array<TranscriptEvent> };
export type TranscriptSnapshotComplete = { isRunning: boolean };
export type TranscriptStreamError = { message: string; retry: boolean };
export type TranscriptToolCall = { id: string; name: string; input_summary: string };
export type TranscriptUsageInfo = {
  input_tokens: number;
  output_tokens: number;
  cache_read_tokens: number;
  cache_creation_tokens: number;
};
export type TriageItemResponse = {
  task_id: string;
  pr_number: number;
  project: string;
  github_repo: string;
  title: string;
  fast_track: boolean;
  cursor_risk: string | null;
  file_count: number;
  fetch_failed: boolean;
  fetch_error: string;
  merge_readiness_score: number;
};
export type TriageRequest = { item_id?: string };
export type TriageResponse = { items: Array<TriageItemResponse>; table: string };
export type UiConfig = { openAtLogin: boolean };
export type UiDesiredState = 'running' | 'suppressed' | 'updating';
export type UiHealthResponse = {
  desiredState: UiDesiredState;
  currentPid: number | null;
  launchAvailable: boolean;
  running: boolean;
  lastError: string | null;
  degraded: boolean;
  restartCount: number;
};
export type UiRegisterRequest = {
  pid: number;
  execPath: string;
  args: Array<string>;
  cwd: string | null;
  env: { [key in string]: string };
};
export type UnknownEvent = {
  meta: EventMeta;
  rawType: string | null;
  rawSubtype: string | null;
  raw: string;
};
export type UserContentBlock =
  | { kind: 'text'; data: UserTextBlock }
  | { kind: 'image'; data: UserImageBlock }
  | { kind: 'tool_result'; data: UserToolResultBlock };
export type UserContextConfig = {
  role: string;
  knownDomains: Array<string>;
  explainDomains: Array<string>;
};
export type UserEvent = { meta: EventMeta; blocks: Array<UserContentBlock> };
export type UserImageBlock = { mediaType: string | null; dataLen: number | null };
export type UserTextBlock = { text: string };
export type UserToolResultBlock = {
  toolUseId: string;
  content: ToolResultContent;
  isError: boolean | null;
};
export type WebFetchInput = { url: string; prompt: string };
export type WebSearchInput = {
  query: string;
  allowedDomains: Array<string> | null;
  blockedDomains: Array<string> | null;
};
export type WorkSummaryRequest = { content: string };
export type WorkbenchEventData = { action: string | null; item: WorkbenchItem | null };
export type WorkbenchIdParams = { id: number };
export type WorkbenchItem = {
  id: number;
  rev: number;
  projectId: number;
  project: string;
  worktree: string;
  title: string;
  createdAt: string;
  lastActivityAt: string;
  pinnedAt: string | null;
  archivedAt: string | null;
  deletedAt: string | null;
};
export type WorkbenchListQuery = { status: WorkbenchStatusFilter | null };
export type WorkbenchPatchRequest = { title?: string; archived?: boolean; pinned?: boolean };
export type WorkbenchStatusFilter = 'active' | 'archived' | 'all';
export type WorkbenchesPayload = { ts: number; data: WorkbenchEventData | null };
export type WorkbenchesResponse = { workbenches: Array<WorkbenchItem> };
export type WorkerDetail = {
  id: number;
  title: string;
  status: ItemStatus | null;
  project: string;
  github_repo: string | null;
  branch: string | null;
  cc_session_id: string | null;
  worker: string | null;
  worktree: string | null;
  pr_number: number | null;
  started_at: string | null;
  last_activity_at: string | null;
  intervention_count: number | null;
  nudge_count: number | null;
  nudge_budget: number | null;
  last_action: string | null;
  pid: number | null;
  is_stale: boolean | null;
};
export type WorkerIdParams = { id: string };
export type WorkersResponse = {
  workers: Array<WorkerDetail>;
  rate_limit_remaining_secs: number | null;
};
export type WorktreeCleanupRequest = { dryRun: boolean };
export type WorktreeCleanupResponse = {
  ok: boolean;
  orphans: Array<string>;
  removed: Array<string>;
  prune_errors: Array<WorktreePruneError>;
};
export type WorktreeListItem = { project: string; path: string };
export type WorktreeListResponse = { worktrees: Array<WorktreeListItem> };
export type WorktreePruneError = { project: string; error: string };
export type WorktreePruneResponse = { ok: boolean; pruned: Array<string> };
export type WriteInput = { filePath: string; content: string };
