// Auto-generated by api-types-codegen. Do not edit by hand.
import type * as Types from './index';

export type RouteTransport = 'json' | 'multipart' | 'sse' | 'static' | 'ndjson';
export type RouteAuth = 'public' | 'protected';

export interface Routes {
  putArtifactsByIdMedia: {
    method: 'PUT';
    path: '/api/artifacts/{id}/media';
    transport: 'json';
    auth: 'protected';
    body: Types.ArtifactMediaUpdateRequest;
    params: Types.ArtifactIdParams;
    res: Types.BoolOkResponse;
  };
  getArtifactsByIdMediaByIndex: {
    method: 'GET';
    path: '/api/artifacts/{id}/media/{index}';
    transport: 'static';
    auth: 'protected';
    params: Types.ArtifactMediaParams;
  };
  postCaptainAdopt: {
    method: 'POST';
    path: '/api/captain/adopt';
    transport: 'json';
    auth: 'protected';
    body: Types.AdoptRequest;
    res: Types.TaskCreateResponse;
  };
  postCaptainNudge: {
    method: 'POST';
    path: '/api/captain/nudge';
    transport: 'multipart';
    auth: 'protected';
    body: Types.NudgeRequest;
    res: Types.NudgeResponse;
  };
  postCaptainStop: {
    method: 'POST';
    path: '/api/captain/stop';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    res: Types.StopWorkersResponse;
  };
  postCaptainTick: {
    method: 'POST';
    path: '/api/captain/tick';
    transport: 'json';
    auth: 'protected';
    body: Types.TickRequest;
    res: Types.TickDrainResult;
  };
  postCaptainTriage: {
    method: 'POST';
    path: '/api/captain/triage';
    transport: 'json';
    auth: 'protected';
    body: Types.TriageRequest;
    res: Types.TriageResponse;
  };
  getChannels: {
    method: 'GET';
    path: '/api/channels';
    transport: 'json';
    auth: 'protected';
    res: Types.ChannelsResponse;
  };
  postChannelsTelegramOwner: {
    method: 'POST';
    path: '/api/channels/telegram/owner';
    transport: 'json';
    auth: 'protected';
    body: Types.TelegramOwnerRequest;
    res: Types.BoolOkResponse;
  };
  postClientlogs: {
    method: 'POST';
    path: '/api/client-logs';
    transport: 'json';
    auth: 'protected';
    body: Types.ClientLogBatchRequest;
    res: Types.ClientLogBatchResponse;
  };
  getConfig: {
    method: 'GET';
    path: '/api/config';
    transport: 'json';
    auth: 'protected';
    res: Types.MandoConfig;
  };
  putConfig: {
    method: 'PUT';
    path: '/api/config';
    transport: 'json';
    auth: 'protected';
    body: Types.MandoConfig;
    res: Types.ConfigWriteResponse;
  };
  postConfigSetup: {
    method: 'POST';
    path: '/api/config/setup';
    transport: 'json';
    auth: 'protected';
    body: Types.ConfigSetupRequest;
    res: Types.ConfigSetupResponse;
  };
  getConfigStatus: {
    method: 'GET';
    path: '/api/config/status';
    transport: 'json';
    auth: 'protected';
    res: Types.ConfigStatusResponse;
  };
  getCredentials: {
    method: 'GET';
    path: '/api/credentials';
    transport: 'json';
    auth: 'protected';
    res: Types.CredentialsListResponse;
  };
  postCredentialsCodex: {
    method: 'POST';
    path: '/api/credentials/codex';
    transport: 'json';
    auth: 'protected';
    body: Types.AddCodexCredentialRequest;
    res: Types.AddCodexCredentialResponse;
  };
  postCredentialsCodexAppRestore: {
    method: 'POST';
    path: '/api/credentials/codex/app/restore';
    transport: 'json';
    auth: 'protected';
    body: Types.CodexDesktopAppRestoreRequest;
    res: Types.CodexDesktopAppOperationResponse;
  };
  getCredentialsCodexAppStatus: {
    method: 'GET';
    path: '/api/credentials/codex/app/status';
    transport: 'json';
    auth: 'protected';
    query: Types.CodexDesktopAppStatusQuery;
    res: Types.CodexDesktopAppStatusResponse;
  };
  postCredentialsCodexAppUse: {
    method: 'POST';
    path: '/api/credentials/codex/app/use';
    transport: 'json';
    auth: 'protected';
    body: Types.CodexDesktopAppUseRequest;
    res: Types.CodexDesktopAppOperationResponse;
  };
  postCredentialsCodexLoginCancel: {
    method: 'POST';
    path: '/api/credentials/codex/login/cancel';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    res: Types.CancelCodexLoginResponse;
  };
  getCredentialsCodexLoginCurrent: {
    method: 'GET';
    path: '/api/credentials/codex/login/current';
    transport: 'json';
    auth: 'protected';
    res: Types.CodexLoginStatusResponse;
  };
  postCredentialsCodexLoginStart: {
    method: 'POST';
    path: '/api/credentials/codex/login/start';
    transport: 'json';
    auth: 'protected';
    body: Types.StartCodexLoginRequest;
    res: Types.StartCodexLoginResponse;
  };
  postCredentialsCodexPick: {
    method: 'POST';
    path: '/api/credentials/codex/pick';
    transport: 'json';
    auth: 'protected';
    body: Types.CredentialPickRequest;
    res: Types.CodexCredentialPickResponse;
  };
  postCredentialsCodexSync: {
    method: 'POST';
    path: '/api/credentials/codex/sync';
    transport: 'json';
    auth: 'protected';
    body: Types.SyncCodexCredentialRequest;
    res: Types.SyncCodexCredentialResponse;
  };
  postCredentialsCodexByIdAuth: {
    method: 'POST';
    path: '/api/credentials/codex/{id}/auth';
    transport: 'json';
    auth: 'protected';
    body: Types.UpdateCodexCredentialAuthRequest;
    params: Types.CredentialIdParams;
    res: Types.AddCodexCredentialResponse;
  };
  getCredentialsCodexByIdResetcredits: {
    method: 'GET';
    path: '/api/credentials/codex/{id}/reset-credits';
    transport: 'json';
    auth: 'protected';
    params: Types.CredentialIdParams;
    res: Types.CodexResetCreditsResponse;
  };
  postCredentialsPick: {
    method: 'POST';
    path: '/api/credentials/pick';
    transport: 'json';
    auth: 'protected';
    body: Types.CredentialPickRequest;
    res: Types.CredentialPickResponse;
  };
  postCredentialsSetuptoken: {
    method: 'POST';
    path: '/api/credentials/setup-token';
    transport: 'json';
    auth: 'protected';
    body: Types.SetupTokenRequest;
    res: Types.SetupTokenResponse;
  };
  deleteCredentialsById: {
    method: 'DELETE';
    path: '/api/credentials/{id}';
    transport: 'json';
    auth: 'protected';
    params: Types.CredentialIdParams;
    res: Types.CredentialMutationResponse;
  };
  postCredentialsByIdDisable: {
    method: 'POST';
    path: '/api/credentials/{id}/disable';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    params: Types.CredentialIdParams;
    res: Types.CredentialMutationResponse;
  };
  postCredentialsByIdEnable: {
    method: 'POST';
    path: '/api/credentials/{id}/enable';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    params: Types.CredentialIdParams;
    res: Types.CredentialMutationResponse;
  };
  postCredentialsByIdProbe: {
    method: 'POST';
    path: '/api/credentials/{id}/probe';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    params: Types.CredentialIdParams;
    res: Types.ProbeCredentialResponse;
  };
  getCredentialsByIdToken: {
    method: 'GET';
    path: '/api/credentials/{id}/token';
    transport: 'json';
    auth: 'protected';
    params: Types.CredentialIdParams;
    res: Types.CredentialTokenResponse;
  };
  postCredentialsByIdToken: {
    method: 'POST';
    path: '/api/credentials/{id}/token';
    transport: 'json';
    auth: 'protected';
    body: Types.UpdateCredentialTokenRequest;
    params: Types.CredentialIdParams;
    res: Types.UpdateCredentialTokenResponse;
  };
  getEvents: {
    method: 'GET';
    path: '/api/events';
    transport: 'sse';
    auth: 'protected';
    event: Types.SseEnvelope;
  };
  postFirecrawlScrape: {
    method: 'POST';
    path: '/api/firecrawl/scrape';
    transport: 'json';
    auth: 'protected';
    body: Types.FirecrawlScrapeRequest;
    res: Types.FirecrawlScrapeResponse;
  };
  getGithubAttachmentsById: {
    method: 'GET';
    path: '/api/github/attachments/{id}';
    transport: 'static';
    auth: 'protected';
    params: Types.GitHubUserAttachmentParams;
  };
  getHealth: {
    method: 'GET';
    path: '/api/health';
    transport: 'json';
    auth: 'public';
    res: Types.HealthResponse;
  };
  getHealthSystem: {
    method: 'GET';
    path: '/api/health/system';
    transport: 'json';
    auth: 'protected';
    res: Types.SystemHealthResponse;
  };
  getHealthTelegram: {
    method: 'GET';
    path: '/api/health/telegram';
    transport: 'json';
    auth: 'protected';
    res: Types.TelegramHealth;
  };
  getImagesByFilename: {
    method: 'GET';
    path: '/api/images/{filename}';
    transport: 'static';
    auth: 'protected';
    params: Types.ImageFilenameParams;
  };
  postNotify: {
    method: 'POST';
    path: '/api/notify';
    transport: 'json';
    auth: 'protected';
    body: Types.NotifyRequest;
    res: Types.NotifyResponse;
  };
  getProjects: {
    method: 'GET';
    path: '/api/projects';
    transport: 'json';
    auth: 'protected';
    res: Types.ProjectsListResponse;
  };
  postProjects: {
    method: 'POST';
    path: '/api/projects';
    transport: 'json';
    auth: 'protected';
    body: Types.AddProjectRequest;
    res: Types.ProjectUpsertResponse;
  };
  deleteProjectsByName: {
    method: 'DELETE';
    path: '/api/projects/{name}';
    transport: 'json';
    auth: 'protected';
    params: Types.ProjectNameParams;
    res: Types.ProjectDeleteResponse;
  };
  patchProjectsByName: {
    method: 'PATCH';
    path: '/api/projects/{name}';
    transport: 'json';
    auth: 'protected';
    body: Types.EditProjectRequest;
    params: Types.ProjectNameParams;
    res: Types.ProjectUpsertResponse;
  };
  postScoutAsk: {
    method: 'POST';
    path: '/api/scout/ask';
    transport: 'multipart';
    auth: 'protected';
    body: Types.ScoutAskRequest;
    res: Types.AskResponse;
  };
  postScoutBulk: {
    method: 'POST';
    path: '/api/scout/bulk';
    transport: 'json';
    auth: 'protected';
    body: Types.ScoutBulkCommandRequest;
    res: Types.ScoutBulkUpdateResponse;
  };
  postScoutBulkdelete: {
    method: 'POST';
    path: '/api/scout/bulk-delete';
    transport: 'json';
    auth: 'protected';
    body: Types.ScoutBulkDeleteRequest;
    res: Types.ScoutBulkDeleteResponse;
  };
  getScoutItems: {
    method: 'GET';
    path: '/api/scout/items';
    transport: 'json';
    auth: 'protected';
    query: Types.ScoutQuery;
    res: Types.ScoutResponse;
  };
  postScoutItems: {
    method: 'POST';
    path: '/api/scout/items';
    transport: 'json';
    auth: 'protected';
    body: Types.ScoutAddRequest;
    res: Types.ScoutAddResponse;
  };
  deleteScoutItemsById: {
    method: 'DELETE';
    path: '/api/scout/items/{id}';
    transport: 'json';
    auth: 'protected';
    params: Types.ScoutItemIdParams;
    res: Types.ScoutDeleteResponse;
  };
  getScoutItemsById: {
    method: 'GET';
    path: '/api/scout/items/{id}';
    transport: 'json';
    auth: 'protected';
    params: Types.ScoutItemIdParams;
    res: Types.ScoutItem;
  };
  patchScoutItemsById: {
    method: 'PATCH';
    path: '/api/scout/items/{id}';
    transport: 'json';
    auth: 'protected';
    body: Types.ScoutLifecycleCommandRequest;
    params: Types.ScoutItemIdParams;
    res: Types.BoolOkResponse;
  };
  postScoutItemsByIdAct: {
    method: 'POST';
    path: '/api/scout/items/{id}/act';
    transport: 'json';
    auth: 'protected';
    body: Types.ScoutActRequest;
    params: Types.ScoutItemIdParams;
    res: Types.ActResponse;
  };
  getScoutItemsByIdArticle: {
    method: 'GET';
    path: '/api/scout/items/{id}/article';
    transport: 'json';
    auth: 'protected';
    params: Types.ScoutItemIdParams;
    res: Types.ScoutArticleResponse;
  };
  getScoutItemsByIdSessions: {
    method: 'GET';
    path: '/api/scout/items/{id}/sessions';
    transport: 'json';
    auth: 'protected';
    params: Types.ScoutItemIdParams;
    res: Array<Types.ScoutItemSession>;
  };
  postScoutItemsByIdTelegraph: {
    method: 'POST';
    path: '/api/scout/items/{id}/telegraph';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    params: Types.ScoutItemIdParams;
    res: Types.TelegraphPublishResponse;
  };
  postScoutProcess: {
    method: 'POST';
    path: '/api/scout/process';
    transport: 'json';
    auth: 'protected';
    body: Types.ScoutProcessRequest;
    res: Types.ProcessResponse;
  };
  getScoutResearch: {
    method: 'GET';
    path: '/api/scout/research';
    transport: 'json';
    auth: 'protected';
    res: Array<Types.ScoutResearchRun>;
  };
  postScoutResearch: {
    method: 'POST';
    path: '/api/scout/research';
    transport: 'json';
    auth: 'protected';
    body: Types.ScoutResearchRequest;
    res: Types.ResearchStartResponse;
  };
  getScoutResearchById: {
    method: 'GET';
    path: '/api/scout/research/{id}';
    transport: 'json';
    auth: 'protected';
    params: Types.ScoutResearchIdParams;
    res: Types.ScoutResearchRun;
  };
  getScoutResearchByIdItems: {
    method: 'GET';
    path: '/api/scout/research/{id}/items';
    transport: 'json';
    auth: 'protected';
    params: Types.ScoutResearchIdParams;
    res: Array<Types.ScoutItem>;
  };
  getSessions: {
    method: 'GET';
    path: '/api/sessions';
    transport: 'json';
    auth: 'protected';
    query: Types.SessionsQuery;
    res: Types.SessionsListResponse;
  };
  getSessionsById: {
    method: 'GET';
    path: '/api/sessions/{id}';
    transport: 'json';
    auth: 'protected';
    params: Types.SessionIdParams;
    res: Types.SessionEntry;
  };
  getSessionsByIdCost: {
    method: 'GET';
    path: '/api/sessions/{id}/cost';
    transport: 'json';
    auth: 'protected';
    params: Types.SessionIdParams;
    res: Types.SessionCostResponse;
  };
  getSessionsByIdEvents: {
    method: 'GET';
    path: '/api/sessions/{id}/events';
    transport: 'json';
    auth: 'protected';
    params: Types.SessionIdParams;
    res: Types.TranscriptEventsResponse;
  };
  getSessionsByIdEventsStream: {
    method: 'GET';
    path: '/api/sessions/{id}/events/stream';
    transport: 'sse';
    auth: 'protected';
    params: Types.SessionIdParams;
    event: Types.TranscriptEventEnvelope;
  };
  getSessionsByIdImagesByToolByIndex: {
    method: 'GET';
    path: '/api/sessions/{id}/images/{tool}/{index}';
    transport: 'static';
    auth: 'protected';
    params: Types.SessionToolResultImageParams;
  };
  getSessionsByIdJsonlpath: {
    method: 'GET';
    path: '/api/sessions/{id}/jsonl-path';
    transport: 'json';
    auth: 'protected';
    params: Types.SessionIdParams;
    res: Types.SessionJsonlPathResponse;
  };
  getSessionsByIdMessages: {
    method: 'GET';
    path: '/api/sessions/{id}/messages';
    transport: 'json';
    auth: 'protected';
    query: Types.SessionMessagesQuery;
    params: Types.SessionIdParams;
    res: Types.SessionMessagesResponse;
  };
  getSessionsByIdStream: {
    method: 'GET';
    path: '/api/sessions/{id}/stream';
    transport: 'ndjson';
    auth: 'protected';
    query: Types.SessionStreamQuery;
    params: Types.SessionIdParams;
  };
  getSessionsByIdTools: {
    method: 'GET';
    path: '/api/sessions/{id}/tools';
    transport: 'json';
    auth: 'protected';
    params: Types.SessionIdParams;
    res: Types.SessionToolUsageResponse;
  };
  getStatsActivity: {
    method: 'GET';
    path: '/api/stats/activity';
    transport: 'json';
    auth: 'protected';
    res: Types.ActivityStatsResponse;
  };
  deleteTasks: {
    method: 'DELETE';
    path: '/api/tasks';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskDeleteRequest;
    res: Types.DeleteTasksResponse;
  };
  getTasks: {
    method: 'GET';
    path: '/api/tasks';
    transport: 'json';
    auth: 'protected';
    query: Types.TaskListQuery;
    res: Types.TaskListResponse;
  };
  postTasksAccept: {
    method: 'POST';
    path: '/api/tasks/accept';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskIdRequest;
    res: Types.BoolOkResponse;
  };
  postTasksAdd: {
    method: 'POST';
    path: '/api/tasks/add';
    transport: 'multipart';
    auth: 'protected';
    body: Types.TaskAddRequest;
    res: Types.TaskItem;
  };
  postTasksBulk: {
    method: 'POST';
    path: '/api/tasks/bulk';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskBulkUpdateRequest;
    res: Types.BoolOkResponse;
  };
  postTasksCancel: {
    method: 'POST';
    path: '/api/tasks/cancel';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskIdRequest;
    res: Types.BoolOkResponse;
  };
  postTasksDelete: {
    method: 'POST';
    path: '/api/tasks/delete';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskDeleteRequest;
    res: Types.DeleteTasksResponse;
  };
  postTasksHandoff: {
    method: 'POST';
    path: '/api/tasks/handoff';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskIdRequest;
    res: Types.BoolOkResponse;
  };
  postTasksMerge: {
    method: 'POST';
    path: '/api/tasks/merge';
    transport: 'json';
    auth: 'protected';
    body: Types.MergeRequest;
    res: Types.MergeResponse;
  };
  postTasksReopen: {
    method: 'POST';
    path: '/api/tasks/reopen';
    transport: 'multipart';
    auth: 'protected';
    body: Types.TaskFeedbackRequest;
    res: Types.BoolOkResponse;
  };
  postTasksResumeratelimited: {
    method: 'POST';
    path: '/api/tasks/resume-rate-limited';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskIdRequest;
    res: Types.BoolOkResponse;
  };
  postTasksRetry: {
    method: 'POST';
    path: '/api/tasks/retry';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskIdRequest;
    res: Types.BoolOkResponse;
  };
  postTasksRework: {
    method: 'POST';
    path: '/api/tasks/rework';
    transport: 'multipart';
    auth: 'protected';
    body: Types.TaskFeedbackRequest;
    res: Types.BoolOkResponse;
  };
  postTasksStop: {
    method: 'POST';
    path: '/api/tasks/stop';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskIdRequest;
    res: Types.BoolOkResponse;
  };
  patchTasksById: {
    method: 'PATCH';
    path: '/api/tasks/{id}';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskPatchRequest;
    params: Types.TaskIdParams;
    res: Types.BoolOkResponse;
  };
  getTasksByIdArtifacts: {
    method: 'GET';
    path: '/api/tasks/{id}/artifacts';
    transport: 'json';
    auth: 'protected';
    params: Types.TaskIdParams;
    res: Types.ArtifactsResponse;
  };
  postTasksByIdClarify: {
    method: 'POST';
    path: '/api/tasks/{id}/clarify';
    transport: 'multipart';
    auth: 'protected';
    body: Types.ClarifyRequest;
    query: Types.ClarifyQuery;
    params: Types.TaskIdParams;
    res: Types.ClarifyResponse;
  };
  postTasksByIdEvidence: {
    method: 'POST';
    path: '/api/tasks/{id}/evidence';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskEvidenceRequest;
    params: Types.TaskIdParams;
    res: Types.TaskEvidenceResponse;
  };
  getTasksByIdFeed: {
    method: 'GET';
    path: '/api/tasks/{id}/feed';
    transport: 'json';
    auth: 'protected';
    params: Types.TaskIdParams;
    res: Types.FeedResponse;
  };
  getTasksByIdPrsummary: {
    method: 'GET';
    path: '/api/tasks/{id}/pr-summary';
    transport: 'json';
    auth: 'protected';
    params: Types.TaskIdParams;
    res: Types.PrSummaryResponse;
  };
  getTasksByIdSessions: {
    method: 'GET';
    path: '/api/tasks/{id}/sessions';
    transport: 'json';
    auth: 'protected';
    query: Types.SessionsQuery;
    params: Types.TaskIdParams;
    res: Types.ItemSessionsResponse;
  };
  postTasksByIdSummary: {
    method: 'POST';
    path: '/api/tasks/{id}/summary';
    transport: 'json';
    auth: 'protected';
    body: Types.TaskSummaryRequest;
    params: Types.TaskIdParams;
    res: Types.TaskSummaryResponse;
  };
  getTasksByIdTimeline: {
    method: 'GET';
    path: '/api/tasks/{id}/timeline';
    transport: 'json';
    auth: 'protected';
    params: Types.TaskIdParams;
    res: Types.TimelineResponse;
  };
  postUiLaunch: {
    method: 'POST';
    path: '/api/ui/launch';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    res: Types.BoolOkResponse;
  };
  postUiQuitting: {
    method: 'POST';
    path: '/api/ui/quitting';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    res: Types.BoolOkResponse;
  };
  postUiRegister: {
    method: 'POST';
    path: '/api/ui/register';
    transport: 'json';
    auth: 'protected';
    body: Types.UiRegisterRequest;
    res: Types.BoolOkResponse;
  };
  postUiRestart: {
    method: 'POST';
    path: '/api/ui/restart';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    res: Types.BoolOkResponse;
  };
  postUiUpdating: {
    method: 'POST';
    path: '/api/ui/updating';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    res: Types.BoolOkResponse;
  };
  getWorkbenches: {
    method: 'GET';
    path: '/api/workbenches';
    transport: 'json';
    auth: 'protected';
    query: Types.WorkbenchListQuery;
    res: Types.WorkbenchesResponse;
  };
  patchWorkbenchesById: {
    method: 'PATCH';
    path: '/api/workbenches/{id}';
    transport: 'json';
    auth: 'protected';
    body: Types.WorkbenchPatchRequest;
    params: Types.WorkbenchIdParams;
    res: Types.WorkbenchItem;
  };
  getWorkers: {
    method: 'GET';
    path: '/api/workers';
    transport: 'json';
    auth: 'protected';
    res: Types.WorkersResponse;
  };
  getWorktrees: {
    method: 'GET';
    path: '/api/worktrees';
    transport: 'json';
    auth: 'protected';
    res: Types.WorktreeListResponse;
  };
  postWorktrees: {
    method: 'POST';
    path: '/api/worktrees';
    transport: 'json';
    auth: 'protected';
    body: Types.CreateWorktreeRequest;
    res: Types.CreateWorktreeResponse;
  };
  postWorktreesCleanup: {
    method: 'POST';
    path: '/api/worktrees/cleanup';
    transport: 'json';
    auth: 'protected';
    body: Types.WorktreeCleanupRequest;
    res: Types.WorktreeCleanupResponse;
  };
  postWorktreesPrune: {
    method: 'POST';
    path: '/api/worktrees/prune';
    transport: 'json';
    auth: 'protected';
    body: Types.EmptyRequest;
    res: Types.WorktreePruneResponse;
  };
  postWorktreesRemove: {
    method: 'POST';
    path: '/api/worktrees/remove';
    transport: 'json';
    auth: 'protected';
    body: Types.RemoveWorktreeRequest;
    res: Types.BoolOkResponse;
  };
}

export type JsonRouteKey = {
  [K in keyof Routes]: Routes[K]['transport'] extends 'json' ? K : never;
}[keyof Routes];
export type GetJsonRouteKey = {
  [K in JsonRouteKey]: Routes[K]['method'] extends 'GET' ? K : never;
}[JsonRouteKey];
export type PostJsonRouteKey = {
  [K in JsonRouteKey]: Routes[K]['method'] extends 'POST' ? K : never;
}[JsonRouteKey];
export type PutJsonRouteKey = {
  [K in JsonRouteKey]: Routes[K]['method'] extends 'PUT' ? K : never;
}[JsonRouteKey];
export type PatchJsonRouteKey = {
  [K in JsonRouteKey]: Routes[K]['method'] extends 'PATCH' ? K : never;
}[JsonRouteKey];
export type DeleteJsonRouteKey = {
  [K in JsonRouteKey]: Routes[K]['method'] extends 'DELETE' ? K : never;
}[JsonRouteKey];
export type MutationJsonRouteKey =
  | PostJsonRouteKey
  | PutJsonRouteKey
  | PatchJsonRouteKey
  | DeleteJsonRouteKey;
export type JsonRouteWithBodyKey = {
  [K in JsonRouteKey]: Routes[K] extends { body: unknown } ? K : never;
}[JsonRouteKey];
export type DeleteJsonRouteWithBodyKey = {
  [K in DeleteJsonRouteKey]: Routes[K] extends { body: unknown } ? K : never;
}[DeleteJsonRouteKey];
export type JsonRouteWithResKey = {
  [K in JsonRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[JsonRouteKey];
export type GetJsonRouteWithResKey = {
  [K in GetJsonRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[GetJsonRouteKey];
export type PostJsonRouteWithResKey = {
  [K in PostJsonRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[PostJsonRouteKey];
export type PutJsonRouteWithResKey = {
  [K in PutJsonRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[PutJsonRouteKey];
export type PatchJsonRouteWithResKey = {
  [K in PatchJsonRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[PatchJsonRouteKey];
export type DeleteJsonRouteWithResKey = {
  [K in DeleteJsonRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[DeleteJsonRouteKey];
export type MutationJsonRouteWithResKey = {
  [K in MutationJsonRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[MutationJsonRouteKey];
export type MultipartRouteKey = {
  [K in keyof Routes]: Routes[K]['transport'] extends 'multipart' ? K : never;
}[keyof Routes];
export type PostMultipartRouteKey = {
  [K in MultipartRouteKey]: Routes[K]['method'] extends 'POST' ? K : never;
}[MultipartRouteKey];
export type MultipartRouteWithResKey = {
  [K in MultipartRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[MultipartRouteKey];
export type PostMultipartRouteWithResKey = {
  [K in PostMultipartRouteKey]: Routes[K] extends { res: unknown } ? K : never;
}[PostMultipartRouteKey];
export type SseRouteKey = {
  [K in keyof Routes]: Routes[K]['transport'] extends 'sse' ? K : never;
}[keyof Routes];
export type GetSseRouteKey = {
  [K in SseRouteKey]: Routes[K]['method'] extends 'GET' ? K : never;
}[SseRouteKey];
export type SseRouteWithEventKey = {
  [K in SseRouteKey]: Routes[K] extends { event: unknown } ? K : never;
}[SseRouteKey];
export type GetSseRouteWithEventKey = {
  [K in GetSseRouteKey]: Routes[K] extends { event: unknown } ? K : never;
}[GetSseRouteKey];
export type StaticRouteKey = {
  [K in keyof Routes]: Routes[K]['transport'] extends 'static' ? K : never;
}[keyof Routes];
export type NdjsonRouteKey = {
  [K in keyof Routes]: Routes[K]['transport'] extends 'ndjson' ? K : never;
}[keyof Routes];

export const routes = {
  putArtifactsByIdMedia: {
    method: 'PUT',
    path: '/api/artifacts/{id}/media',
    transport: 'json',
    auth: 'protected',
  },
  getArtifactsByIdMediaByIndex: {
    method: 'GET',
    path: '/api/artifacts/{id}/media/{index}',
    transport: 'static',
    auth: 'protected',
  },
  postCaptainAdopt: {
    method: 'POST',
    path: '/api/captain/adopt',
    transport: 'json',
    auth: 'protected',
  },
  postCaptainNudge: {
    method: 'POST',
    path: '/api/captain/nudge',
    transport: 'multipart',
    auth: 'protected',
  },
  postCaptainStop: {
    method: 'POST',
    path: '/api/captain/stop',
    transport: 'json',
    auth: 'protected',
  },
  postCaptainTick: {
    method: 'POST',
    path: '/api/captain/tick',
    transport: 'json',
    auth: 'protected',
  },
  postCaptainTriage: {
    method: 'POST',
    path: '/api/captain/triage',
    transport: 'json',
    auth: 'protected',
  },
  getChannels: { method: 'GET', path: '/api/channels', transport: 'json', auth: 'protected' },
  postChannelsTelegramOwner: {
    method: 'POST',
    path: '/api/channels/telegram/owner',
    transport: 'json',
    auth: 'protected',
  },
  postClientlogs: {
    method: 'POST',
    path: '/api/client-logs',
    transport: 'json',
    auth: 'protected',
  },
  getConfig: { method: 'GET', path: '/api/config', transport: 'json', auth: 'protected' },
  putConfig: { method: 'PUT', path: '/api/config', transport: 'json', auth: 'protected' },
  postConfigSetup: {
    method: 'POST',
    path: '/api/config/setup',
    transport: 'json',
    auth: 'protected',
  },
  getConfigStatus: {
    method: 'GET',
    path: '/api/config/status',
    transport: 'json',
    auth: 'protected',
  },
  getCredentials: { method: 'GET', path: '/api/credentials', transport: 'json', auth: 'protected' },
  postCredentialsCodex: {
    method: 'POST',
    path: '/api/credentials/codex',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsCodexAppRestore: {
    method: 'POST',
    path: '/api/credentials/codex/app/restore',
    transport: 'json',
    auth: 'protected',
  },
  getCredentialsCodexAppStatus: {
    method: 'GET',
    path: '/api/credentials/codex/app/status',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsCodexAppUse: {
    method: 'POST',
    path: '/api/credentials/codex/app/use',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsCodexLoginCancel: {
    method: 'POST',
    path: '/api/credentials/codex/login/cancel',
    transport: 'json',
    auth: 'protected',
  },
  getCredentialsCodexLoginCurrent: {
    method: 'GET',
    path: '/api/credentials/codex/login/current',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsCodexLoginStart: {
    method: 'POST',
    path: '/api/credentials/codex/login/start',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsCodexPick: {
    method: 'POST',
    path: '/api/credentials/codex/pick',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsCodexSync: {
    method: 'POST',
    path: '/api/credentials/codex/sync',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsCodexByIdAuth: {
    method: 'POST',
    path: '/api/credentials/codex/{id}/auth',
    transport: 'json',
    auth: 'protected',
  },
  getCredentialsCodexByIdResetcredits: {
    method: 'GET',
    path: '/api/credentials/codex/{id}/reset-credits',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsPick: {
    method: 'POST',
    path: '/api/credentials/pick',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsSetuptoken: {
    method: 'POST',
    path: '/api/credentials/setup-token',
    transport: 'json',
    auth: 'protected',
  },
  deleteCredentialsById: {
    method: 'DELETE',
    path: '/api/credentials/{id}',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsByIdDisable: {
    method: 'POST',
    path: '/api/credentials/{id}/disable',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsByIdEnable: {
    method: 'POST',
    path: '/api/credentials/{id}/enable',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsByIdProbe: {
    method: 'POST',
    path: '/api/credentials/{id}/probe',
    transport: 'json',
    auth: 'protected',
  },
  getCredentialsByIdToken: {
    method: 'GET',
    path: '/api/credentials/{id}/token',
    transport: 'json',
    auth: 'protected',
  },
  postCredentialsByIdToken: {
    method: 'POST',
    path: '/api/credentials/{id}/token',
    transport: 'json',
    auth: 'protected',
  },
  getEvents: { method: 'GET', path: '/api/events', transport: 'sse', auth: 'protected' },
  postFirecrawlScrape: {
    method: 'POST',
    path: '/api/firecrawl/scrape',
    transport: 'json',
    auth: 'protected',
  },
  getGithubAttachmentsById: {
    method: 'GET',
    path: '/api/github/attachments/{id}',
    transport: 'static',
    auth: 'protected',
  },
  getHealth: { method: 'GET', path: '/api/health', transport: 'json', auth: 'public' },
  getHealthSystem: {
    method: 'GET',
    path: '/api/health/system',
    transport: 'json',
    auth: 'protected',
  },
  getHealthTelegram: {
    method: 'GET',
    path: '/api/health/telegram',
    transport: 'json',
    auth: 'protected',
  },
  getImagesByFilename: {
    method: 'GET',
    path: '/api/images/{filename}',
    transport: 'static',
    auth: 'protected',
  },
  postNotify: { method: 'POST', path: '/api/notify', transport: 'json', auth: 'protected' },
  getProjects: { method: 'GET', path: '/api/projects', transport: 'json', auth: 'protected' },
  postProjects: { method: 'POST', path: '/api/projects', transport: 'json', auth: 'protected' },
  deleteProjectsByName: {
    method: 'DELETE',
    path: '/api/projects/{name}',
    transport: 'json',
    auth: 'protected',
  },
  patchProjectsByName: {
    method: 'PATCH',
    path: '/api/projects/{name}',
    transport: 'json',
    auth: 'protected',
  },
  postScoutAsk: {
    method: 'POST',
    path: '/api/scout/ask',
    transport: 'multipart',
    auth: 'protected',
  },
  postScoutBulk: { method: 'POST', path: '/api/scout/bulk', transport: 'json', auth: 'protected' },
  postScoutBulkdelete: {
    method: 'POST',
    path: '/api/scout/bulk-delete',
    transport: 'json',
    auth: 'protected',
  },
  getScoutItems: { method: 'GET', path: '/api/scout/items', transport: 'json', auth: 'protected' },
  postScoutItems: {
    method: 'POST',
    path: '/api/scout/items',
    transport: 'json',
    auth: 'protected',
  },
  deleteScoutItemsById: {
    method: 'DELETE',
    path: '/api/scout/items/{id}',
    transport: 'json',
    auth: 'protected',
  },
  getScoutItemsById: {
    method: 'GET',
    path: '/api/scout/items/{id}',
    transport: 'json',
    auth: 'protected',
  },
  patchScoutItemsById: {
    method: 'PATCH',
    path: '/api/scout/items/{id}',
    transport: 'json',
    auth: 'protected',
  },
  postScoutItemsByIdAct: {
    method: 'POST',
    path: '/api/scout/items/{id}/act',
    transport: 'json',
    auth: 'protected',
  },
  getScoutItemsByIdArticle: {
    method: 'GET',
    path: '/api/scout/items/{id}/article',
    transport: 'json',
    auth: 'protected',
  },
  getScoutItemsByIdSessions: {
    method: 'GET',
    path: '/api/scout/items/{id}/sessions',
    transport: 'json',
    auth: 'protected',
  },
  postScoutItemsByIdTelegraph: {
    method: 'POST',
    path: '/api/scout/items/{id}/telegraph',
    transport: 'json',
    auth: 'protected',
  },
  postScoutProcess: {
    method: 'POST',
    path: '/api/scout/process',
    transport: 'json',
    auth: 'protected',
  },
  getScoutResearch: {
    method: 'GET',
    path: '/api/scout/research',
    transport: 'json',
    auth: 'protected',
  },
  postScoutResearch: {
    method: 'POST',
    path: '/api/scout/research',
    transport: 'json',
    auth: 'protected',
  },
  getScoutResearchById: {
    method: 'GET',
    path: '/api/scout/research/{id}',
    transport: 'json',
    auth: 'protected',
  },
  getScoutResearchByIdItems: {
    method: 'GET',
    path: '/api/scout/research/{id}/items',
    transport: 'json',
    auth: 'protected',
  },
  getSessions: { method: 'GET', path: '/api/sessions', transport: 'json', auth: 'protected' },
  getSessionsById: {
    method: 'GET',
    path: '/api/sessions/{id}',
    transport: 'json',
    auth: 'protected',
  },
  getSessionsByIdCost: {
    method: 'GET',
    path: '/api/sessions/{id}/cost',
    transport: 'json',
    auth: 'protected',
  },
  getSessionsByIdEvents: {
    method: 'GET',
    path: '/api/sessions/{id}/events',
    transport: 'json',
    auth: 'protected',
  },
  getSessionsByIdEventsStream: {
    method: 'GET',
    path: '/api/sessions/{id}/events/stream',
    transport: 'sse',
    auth: 'protected',
  },
  getSessionsByIdImagesByToolByIndex: {
    method: 'GET',
    path: '/api/sessions/{id}/images/{tool}/{index}',
    transport: 'static',
    auth: 'protected',
  },
  getSessionsByIdJsonlpath: {
    method: 'GET',
    path: '/api/sessions/{id}/jsonl-path',
    transport: 'json',
    auth: 'protected',
  },
  getSessionsByIdMessages: {
    method: 'GET',
    path: '/api/sessions/{id}/messages',
    transport: 'json',
    auth: 'protected',
  },
  getSessionsByIdStream: {
    method: 'GET',
    path: '/api/sessions/{id}/stream',
    transport: 'ndjson',
    auth: 'protected',
  },
  getSessionsByIdTools: {
    method: 'GET',
    path: '/api/sessions/{id}/tools',
    transport: 'json',
    auth: 'protected',
  },
  getStatsActivity: {
    method: 'GET',
    path: '/api/stats/activity',
    transport: 'json',
    auth: 'protected',
  },
  deleteTasks: { method: 'DELETE', path: '/api/tasks', transport: 'json', auth: 'protected' },
  getTasks: { method: 'GET', path: '/api/tasks', transport: 'json', auth: 'protected' },
  postTasksAccept: {
    method: 'POST',
    path: '/api/tasks/accept',
    transport: 'json',
    auth: 'protected',
  },
  postTasksAdd: {
    method: 'POST',
    path: '/api/tasks/add',
    transport: 'multipart',
    auth: 'protected',
  },
  postTasksBulk: { method: 'POST', path: '/api/tasks/bulk', transport: 'json', auth: 'protected' },
  postTasksCancel: {
    method: 'POST',
    path: '/api/tasks/cancel',
    transport: 'json',
    auth: 'protected',
  },
  postTasksDelete: {
    method: 'POST',
    path: '/api/tasks/delete',
    transport: 'json',
    auth: 'protected',
  },
  postTasksHandoff: {
    method: 'POST',
    path: '/api/tasks/handoff',
    transport: 'json',
    auth: 'protected',
  },
  postTasksMerge: {
    method: 'POST',
    path: '/api/tasks/merge',
    transport: 'json',
    auth: 'protected',
  },
  postTasksReopen: {
    method: 'POST',
    path: '/api/tasks/reopen',
    transport: 'multipart',
    auth: 'protected',
  },
  postTasksResumeratelimited: {
    method: 'POST',
    path: '/api/tasks/resume-rate-limited',
    transport: 'json',
    auth: 'protected',
  },
  postTasksRetry: {
    method: 'POST',
    path: '/api/tasks/retry',
    transport: 'json',
    auth: 'protected',
  },
  postTasksRework: {
    method: 'POST',
    path: '/api/tasks/rework',
    transport: 'multipart',
    auth: 'protected',
  },
  postTasksStop: { method: 'POST', path: '/api/tasks/stop', transport: 'json', auth: 'protected' },
  patchTasksById: {
    method: 'PATCH',
    path: '/api/tasks/{id}',
    transport: 'json',
    auth: 'protected',
  },
  getTasksByIdArtifacts: {
    method: 'GET',
    path: '/api/tasks/{id}/artifacts',
    transport: 'json',
    auth: 'protected',
  },
  postTasksByIdClarify: {
    method: 'POST',
    path: '/api/tasks/{id}/clarify',
    transport: 'multipart',
    auth: 'protected',
  },
  postTasksByIdEvidence: {
    method: 'POST',
    path: '/api/tasks/{id}/evidence',
    transport: 'json',
    auth: 'protected',
  },
  getTasksByIdFeed: {
    method: 'GET',
    path: '/api/tasks/{id}/feed',
    transport: 'json',
    auth: 'protected',
  },
  getTasksByIdPrsummary: {
    method: 'GET',
    path: '/api/tasks/{id}/pr-summary',
    transport: 'json',
    auth: 'protected',
  },
  getTasksByIdSessions: {
    method: 'GET',
    path: '/api/tasks/{id}/sessions',
    transport: 'json',
    auth: 'protected',
  },
  postTasksByIdSummary: {
    method: 'POST',
    path: '/api/tasks/{id}/summary',
    transport: 'json',
    auth: 'protected',
  },
  getTasksByIdTimeline: {
    method: 'GET',
    path: '/api/tasks/{id}/timeline',
    transport: 'json',
    auth: 'protected',
  },
  postUiLaunch: { method: 'POST', path: '/api/ui/launch', transport: 'json', auth: 'protected' },
  postUiQuitting: {
    method: 'POST',
    path: '/api/ui/quitting',
    transport: 'json',
    auth: 'protected',
  },
  postUiRegister: {
    method: 'POST',
    path: '/api/ui/register',
    transport: 'json',
    auth: 'protected',
  },
  postUiRestart: { method: 'POST', path: '/api/ui/restart', transport: 'json', auth: 'protected' },
  postUiUpdating: {
    method: 'POST',
    path: '/api/ui/updating',
    transport: 'json',
    auth: 'protected',
  },
  getWorkbenches: { method: 'GET', path: '/api/workbenches', transport: 'json', auth: 'protected' },
  patchWorkbenchesById: {
    method: 'PATCH',
    path: '/api/workbenches/{id}',
    transport: 'json',
    auth: 'protected',
  },
  getWorkers: { method: 'GET', path: '/api/workers', transport: 'json', auth: 'protected' },
  getWorktrees: { method: 'GET', path: '/api/worktrees', transport: 'json', auth: 'protected' },
  postWorktrees: { method: 'POST', path: '/api/worktrees', transport: 'json', auth: 'protected' },
  postWorktreesCleanup: {
    method: 'POST',
    path: '/api/worktrees/cleanup',
    transport: 'json',
    auth: 'protected',
  },
  postWorktreesPrune: {
    method: 'POST',
    path: '/api/worktrees/prune',
    transport: 'json',
    auth: 'protected',
  },
  postWorktreesRemove: {
    method: 'POST',
    path: '/api/worktrees/remove',
    transport: 'json',
    auth: 'protected',
  },
} as const satisfies Record<
  keyof Routes,
  { method: string; path: string; transport: RouteTransport; auth: RouteAuth }
>;
