//! Session management methods for the Telegram bot.
//!
//! Input, ask, QA, and act sessions — extracted from bot.rs for file length.

use anyhow::Result;
use tracing::{debug, warn};

use crate::telegram_format::{escape_html, render_markdown_reply_html};

use crate::bot::{ActSession, QaSession, Session, TelegramBot};
use crate::gateway_paths as paths;

/// Per-chat "command awaiting follow-up text" state. Each command that
/// supports the `/todo`-style "send args, or send the command alone and
/// reply with the args" UX gets its own `HashSet<chat_id>` field plus a
/// `set_pending_*` / `clear_pending_*` pair generated by this macro.
macro_rules! pending_methods {
    ($set:ident, $clear:ident, $field:ident) => {
        pub fn $set(&mut self, chat_id: &str) {
            self.$field.insert(chat_id.to_string());
        }
        pub fn $clear(&mut self, chat_id: &str) {
            self.$field.remove(chat_id);
        }
    };
}

impl TelegramBot {
    // ── Pending command follow-ups ───────────────────────────────────
    pending_methods!(set_pending_todo, clear_pending_todo, pending_todo);
    pending_methods!(
        set_pending_timeline,
        clear_pending_timeline,
        pending_timeline
    );
    pending_methods!(
        set_pending_scout_add,
        clear_pending_scout_add,
        pending_scout_add
    );
    pending_methods!(
        set_pending_scout_research,
        clear_pending_scout_research,
        pending_scout_research
    );

    /// Drop any per-chat pending state that is now stale because the user
    /// typed a different `/cmd`. Re-issuing the same command (or its alias)
    /// preserves the pending state — `/timeline` ↔ `/history` count as the
    /// same command for this purpose.
    pub(crate) fn clear_stale_pendings(&mut self, chat_id: &str, command: &str) {
        if command != "todo" {
            self.pending_todo.remove(chat_id);
        }
        if command != "timeline" && command != "history" {
            self.pending_timeline.remove(chat_id);
        }
        if command != "scout_add" {
            self.pending_scout_add.remove(chat_id);
        }
        if command != "scout_research" {
            self.pending_scout_research.remove(chat_id);
        }
        self.pending_reopen.remove(chat_id);
        self.pending_rework.remove(chat_id);
        self.pending_nudge.remove(chat_id);
        self.act_sessions.remove(chat_id);
    }

    // ── Input sessions ───────────────────────────────────────────────

    pub fn has_input_session(&self, cid: &str) -> bool {
        self.input_sessions.contains_key(cid)
    }
    pub fn input_session_title(&self, cid: &str) -> Option<String> {
        self.input_sessions.get(cid).cloned()
    }
    pub fn open_input_session(&mut self, cid: &str, title: &str) {
        self.input_sessions
            .insert(cid.to_string(), title.to_string());
    }
    pub fn close_input_session(&mut self, cid: &str) {
        self.input_sessions.remove(cid);
    }

    // ── Ask sessions ─────────────────────────────────────────────────

    pub fn has_ask_session(&self, cid: &str) -> bool {
        self.ask_sessions.contains_key(cid)
    }
    pub fn ask_session_rounds(&self, cid: &str) -> u32 {
        self.ask_sessions.get(cid).map(|s| s.rounds).unwrap_or(0)
    }
    pub fn open_ask_session(&mut self, cid: &str, task_id: i64) {
        // Close conflicting scout QA session so task-ask wins plain-text routing
        self.qa_sessions.remove(cid);
        self.ask_sessions
            .insert(cid.to_string(), Session::new(task_id));
    }

    pub fn ask_session_task_id(&self, cid: &str) -> Option<i64> {
        self.ask_sessions.get(cid).map(|s| s.task_id)
    }
    pub fn close_ask_session(&mut self, cid: &str) {
        self.ask_sessions.remove(cid);
    }
    pub fn increment_ask_rounds(&mut self, cid: &str) {
        if let Some(s) = self.ask_sessions.get_mut(cid) {
            s.rounds += 1;
        }
    }

    // ── Scout QA sessions ───────────────────────────────────────────

    pub fn open_qa_session(&mut self, cid: &str, item_id: i64) {
        // Close conflicting task-ask session so scout QA wins plain-text routing
        self.ask_sessions.remove(cid);
        self.qa_sessions.insert(
            cid.to_string(),
            QaSession {
                item_id,
                rounds: 0,
                cc_session_id: None,
            },
        );
    }

    pub fn close_qa_session(&mut self, cid: &str) {
        self.qa_sessions.remove(cid);
    }

    pub(crate) async fn handle_qa_text(&mut self, chat_id: &str, question: &str) -> Result<()> {
        let (item_id, cc_session_id) = match self.qa_sessions.get(chat_id) {
            Some(s) => (s.item_id, s.cc_session_id.clone()),
            None => return Ok(()),
        };

        let ack = self
            .api
            .send_message(chat_id, "\u{1f4ac} Thinking\u{2026}", None, None, true)
            .await?;
        let ack_mid = ack.get("message_id").and_then(|v| v.as_i64()).unwrap_or(0);

        let body = serde_json::json!({
            "id": item_id,
            "question": question,
            "session_id": cc_session_id,
        });
        let result = self
            .gw
            .post_typed::<_, api_types::AskResponse>(paths::SCOUT_ASK, &body)
            .await;

        let answer = match result {
            Ok(resp) => {
                if let Some(ref sid) = resp.session_id {
                    if let Some(session) = self.qa_sessions.get_mut(chat_id) {
                        session.cc_session_id = Some(sid.clone());
                    }
                } else {
                    warn!(%chat_id, item_id,
                        "no session_id in Q&A response — multi-turn will not work");
                }
                resp.answer.clone()
            }
            Err(e) => {
                warn!(%chat_id, item_id, error = %e, "Q&A gateway call failed");
                let msg = format!("Q&A failed: {}", escape_html(&e.to_string()));
                global_infra::best_effort!(
                    self.api
                        .edit_message_text(chat_id, ack_mid, &msg, Some("HTML"), None)
                        .await,
                    "bot_sessions: self .api .edit_message_text(chat_id, ack_mid, &msg, Some('H"
                );
                return Ok(());
            }
        };

        if let Some(session) = self.qa_sessions.get_mut(chat_id) {
            session.rounds += 1;
        }

        let kb = crate::assistant::formatting::qa_session_kb(item_id);
        let msg = render_markdown_reply_html(&answer, 3800);

        if let Err(e) = self
            .api
            .edit_message_text(chat_id, ack_mid, &msg, Some("HTML"), Some(kb.clone()))
            .await
        {
            debug!(error = %e, "edit failed, sending new message");
            self.api
                .send_message(chat_id, &msg, Some("HTML"), Some(kb), true)
                .await?;
        }
        Ok(())
    }

    // ── Scout act sessions ──────────────────────────────────────────

    pub fn open_act_session(&mut self, cid: &str, item_id: i64, project: &str) {
        self.act_sessions.insert(
            cid.to_string(),
            ActSession {
                item_id,
                project: project.to_string(),
            },
        );
    }

    pub fn take_act_session(&mut self, cid: &str) -> Option<ActSession> {
        self.act_sessions.remove(cid)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::http::GatewayClient;
    use std::sync::Arc;
    use tokio::sync::RwLock;

    fn test_bot() -> TelegramBot {
        let config = Arc::new(RwLock::new(settings::Config::default()));
        let gw = GatewayClient::new(0, None);
        TelegramBot::new(config, "test-token", gw)
    }

    #[test]
    fn set_pending_inserts_chat_id() {
        let mut bot = test_bot();
        bot.set_pending_timeline("chat-1");
        bot.set_pending_scout_add("chat-2");
        bot.set_pending_scout_research("chat-3");

        assert!(bot.pending_timeline.contains("chat-1"));
        assert!(bot.pending_scout_add.contains("chat-2"));
        assert!(bot.pending_scout_research.contains("chat-3"));
    }

    #[test]
    fn clear_pending_removes_chat_id() {
        let mut bot = test_bot();
        bot.set_pending_timeline("chat-1");
        bot.clear_pending_timeline("chat-1");
        assert!(!bot.pending_timeline.contains("chat-1"));
    }

    #[test]
    fn clear_stale_pendings_keeps_matching_command() {
        let mut bot = test_bot();
        bot.set_pending_timeline("chat-1");
        bot.set_pending_scout_add("chat-1");
        bot.set_pending_scout_research("chat-1");

        bot.clear_stale_pendings("chat-1", "timeline");
        assert!(bot.pending_timeline.contains("chat-1"));
        assert!(!bot.pending_scout_add.contains("chat-1"));
        assert!(!bot.pending_scout_research.contains("chat-1"));
    }

    #[test]
    fn clear_stale_pendings_treats_history_as_timeline_alias() {
        let mut bot = test_bot();
        bot.set_pending_timeline("chat-1");
        bot.clear_stale_pendings("chat-1", "history");
        assert!(
            bot.pending_timeline.contains("chat-1"),
            "/history must preserve pending_timeline (alias-equivalent)"
        );
    }

    #[test]
    fn clear_stale_pendings_drops_non_matching_command() {
        let mut bot = test_bot();
        bot.set_pending_timeline("chat-1");
        bot.set_pending_scout_add("chat-1");

        bot.clear_stale_pendings("chat-1", "tasks");
        assert!(!bot.pending_timeline.contains("chat-1"));
        assert!(!bot.pending_scout_add.contains("chat-1"));
    }

    #[test]
    fn clear_stale_pendings_isolates_chats() {
        let mut bot = test_bot();
        bot.set_pending_timeline("chat-1");
        bot.set_pending_timeline("chat-2");

        bot.clear_stale_pendings("chat-1", "tasks");
        assert!(!bot.pending_timeline.contains("chat-1"));
        assert!(
            bot.pending_timeline.contains("chat-2"),
            "clear must not touch other chats"
        );
    }
}
