//! Sync bundled prod skills to `~/.claude/skills/mando-*`.
//!
//! Skills are compiled into the binary via `include_str!` and written to disk
//! at daemon startup so Claude Code workers can invoke them as slash commands.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use tracing::{info, warn};

pub(super) struct BundledSkill {
    name: &'static str,
    files: &'static [(&'static str, &'static str, bool)], // (filename, content, executable)
}

// -- Bundled skill content (compiled into binary) --
// Generated by rust/crates/settings/build.rs from bundled-skills/*/
include!(concat!(env!("OUT_DIR"), "/bundled_skills.rs"));

fn claude_skills_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_default();
    PathBuf::from(home).join(".claude").join("skills")
}

/// Write all bundled prod skills to `~/.claude/skills/mando-*`.
///
/// Overwrites existing files to keep skills in sync with the daemon version.
/// Skips if `~/.claude/skills/` cannot be created.
pub fn sync_bundled_skills() {
    let base = claude_skills_dir();
    if let Err(e) = fs::create_dir_all(&base) {
        warn!("cannot create {}: {e}", base.display());
        return;
    }

    let mut synced = 0u32;
    for skill in SKILLS {
        let dir = base.join(skill.name);
        if let Err(e) = fs::create_dir_all(&dir) {
            warn!("cannot create {}: {e}", dir.display());
            continue;
        }
        for &(filename, content, executable) in skill.files {
            let path = dir.join(filename);
            if write_if_changed(&path, content, executable) {
                synced += 1;
            }
        }
    }

    if synced > 0 {
        info!(synced, "synced bundled skills to {}", base.display());
    }
}

/// Write content to a file only if it differs from what's on disk.
/// Uses atomic write (temp file + rename) to prevent Claude Code from
/// reading a partially-written file during daemon restart.
/// Returns `true` if the file was written.
fn write_if_changed(path: &Path, content: &str, executable: bool) -> bool {
    let needs_write = match fs::read_to_string(path) {
        Ok(existing) => existing != content,
        Err(_) => true,
    };

    if needs_write {
        let tmp = path.with_extension("tmp");
        if let Err(e) = fs::write(&tmp, content) {
            warn!("cannot write {}: {e}", tmp.display());
            return false;
        }
        if let Err(e) = fs::rename(&tmp, path) {
            warn!("cannot rename {} -> {}: {e}", tmp.display(), path.display());
            if let Err(cleanup_err) = fs::remove_file(&tmp) {
                warn!(
                    "cannot remove temp file {} after rename failure: {cleanup_err}",
                    tmp.display()
                );
            }
            return false;
        }
    }

    // Always ensure executable bit, even if content is unchanged.
    if executable {
        let needs_chmod = fs::metadata(path)
            .map(|m| m.permissions().mode() & 0o111 == 0)
            .unwrap_or(true);
        if needs_chmod {
            if let Err(e) = fs::set_permissions(path, fs::Permissions::from_mode(0o755)) {
                warn!("cannot chmod {}: {e}", path.display());
            }
        }
    }

    needs_write
}

#[cfg(test)]
mod tests {
    use super::SKILLS;
    use std::collections::HashSet;
    use std::path::PathBuf;

    fn bundled_skills_dir() -> PathBuf {
        // CARGO_MANIFEST_DIR points at rust/crates/settings; go up to the
        // repo root and then into bundled-skills/.
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .and_then(|p| p.parent())
            .expect("repo root")
            .join("bundled-skills")
    }

    #[test]
    fn skills_array_matches_bundled_skills_directory() {
        let dir = bundled_skills_dir();
        assert!(
            dir.is_dir(),
            "bundled-skills/ directory not found at {}",
            dir.display()
        );

        let disk_skills: HashSet<String> = std::fs::read_dir(&dir)
            .expect("read bundled-skills dir")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();

        let array_skills: HashSet<String> = SKILLS.iter().map(|s| s.name.to_string()).collect();

        let missing_from_array: Vec<&String> = disk_skills.difference(&array_skills).collect();
        let missing_from_disk: Vec<&String> = array_skills.difference(&disk_skills).collect();

        let mut err = String::new();
        if !missing_from_array.is_empty() {
            err.push_str(&format!(
                "\nbundled-skills/ contains directories not in SKILLS array: {missing_from_array:?}\n\
                 Each new bundled skill directory must be registered in rust/crates/settings/src/config/skills.rs.\n"
            ));
        }
        if !missing_from_disk.is_empty() {
            err.push_str(&format!(
                "\nSKILLS array contains entries without a matching bundled-skills/ directory: {missing_from_disk:?}\n\
                 Either add the directory or remove the entry from the array.\n"
            ));
        }
        assert!(err.is_empty(), "{err}");
    }

    #[test]
    fn every_skill_file_on_disk_is_in_skills_array() {
        let dir = bundled_skills_dir();

        for skill in SKILLS {
            let skill_dir = dir.join(skill.name);
            assert!(
                skill_dir.is_dir(),
                "skill directory missing on disk: {}",
                skill_dir.display()
            );

            let disk_files: HashSet<String> = std::fs::read_dir(&skill_dir)
                .expect("read skill dir")
                .filter_map(|e| e.ok())
                .filter(|e| e.path().is_file())
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .collect();

            let array_files: HashSet<String> =
                skill.files.iter().map(|(n, _, _)| n.to_string()).collect();

            let only_on_disk: Vec<&String> = disk_files.difference(&array_files).collect();
            let only_in_array: Vec<&String> = array_files.difference(&disk_files).collect();

            let mut err = String::new();
            if !only_on_disk.is_empty() {
                err.push_str(&format!(
                    "\nbundled-skills/{}/ contains files not registered in SKILLS[{}].files: {only_on_disk:?}\n",
                    skill.name, skill.name
                ));
            }
            if !only_in_array.is_empty() {
                err.push_str(&format!(
                    "\nSKILLS[{}].files lists files missing from bundled-skills/{}/: {only_in_array:?}\n",
                    skill.name, skill.name
                ));
            }
            assert!(err.is_empty(), "{err}");
        }
    }
}
