//! Model pricing table for estimating session cost from raw token usage.
//!
//! The authoritative cost for a session is the `total_cost_usd` field
//! Anthropic writes into the `type:result` envelope at the end of a clean
//! run. Our code always prefers that value when it is present.
//!
//! When a session exits abnormally (watchdog abort, process kill, panic, any
//! `stop_reason` other than `end_turn`) the CLI never emits `type:result` and
//! `total_cost_usd` is absent. The `cc_sessions.cost_usd` row then records
//! `NULL` despite real token consumption — the exact pattern that made task
//! #81's worker-81-1 show `$0.00` for ~$3 of opus-4-7 time.
//!
//! This module fills that gap by estimating cost from per-message `usage`
//! fields that CC writes on every assistant turn regardless of how the
//! session ends. The rates live here; consumers pass a `Usage` total plus a
//! model string and get an estimated dollar figure.
//!
//! Accuracy caveat: the numbers here are best-effort estimates derived from
//! Anthropic's publicly posted per-million-token prices. They will drift as
//! pricing changes and may not reflect contracted rates. Always prefer the
//! authoritative `total_cost_usd` when it is available.

/// Per-million-token rates for a model, in USD.
///
/// The four fields mirror the four token buckets CC reports:
/// - `input` — non-cached input tokens on this turn.
/// - `output` — tokens generated by the model.
/// - `cache_creation` — tokens written to the prompt cache (1h or 5m ttl,
///   billed at a small premium over input).
/// - `cache_read` — tokens served from the prompt cache (billed at a deep
///   discount).
#[derive(Debug, Clone, Copy)]
pub struct ModelRate {
    pub input_per_mtok: f64,
    pub output_per_mtok: f64,
    pub cache_creation_per_mtok: f64,
    pub cache_read_per_mtok: f64,
}

impl ModelRate {
    /// Compute cost for one turn's raw token counts.
    pub fn cost_for(
        &self,
        input_tokens: u64,
        output_tokens: u64,
        cache_creation_tokens: u64,
        cache_read_tokens: u64,
    ) -> f64 {
        let million = 1_000_000.0;
        (input_tokens as f64) * self.input_per_mtok / million
            + (output_tokens as f64) * self.output_per_mtok / million
            + (cache_creation_tokens as f64) * self.cache_creation_per_mtok / million
            + (cache_read_tokens as f64) * self.cache_read_per_mtok / million
    }
}

/// Rate table keyed by model family. Unknown models fall back to
/// [`fallback_rate`], which uses fable rates on the principle that
/// overestimating cost is safer than silently hiding token spend.
///
/// Id-specific arms run first: a generation whose price differs from its
/// family's older members has to win before the family substring match
/// catches it. Sonnet 5 is cheaper than Sonnet 4.x, so `claude-sonnet-5`
/// must be tested before the plain `sonnet` arm; `claude-opus-5-5` likewise
/// precedes the plain `opus` arm.
pub fn rate_for_model(model: &str) -> ModelRate {
    // Match on a lowercased copy so CC's mixed casing across versions
    // (`claude-opus-4-7`, `claude-sonnet-4-6`) lands in the same bucket
    // regardless of source.
    let lower = model.to_ascii_lowercase();

    // Fable 5.1 keeps Fable 5's base rates but reads cache at $0.25/MTok,
    // a quarter of Fable 5's $1.00, so the id arm has to win over the
    // family substring below.
    if lower.contains("fable-5-1") {
        return ModelRate {
            input_per_mtok: 10.0,
            output_per_mtok: 50.0,
            cache_creation_per_mtok: 12.5,
            cache_read_per_mtok: 0.25,
        };
    }

    // Fable: top tier, and its own family — `claude-fable-5` and any fable
    // id without its own arm land here.
    if lower.contains("fable") {
        return fable_rate();
    }

    // Sonnet 5 is priced below the 4.x sonnets; check the id before family.
    if lower.contains("claude-sonnet-5") {
        return ModelRate {
            input_per_mtok: 2.0,
            output_per_mtok: 10.0,
            cache_creation_per_mtok: 2.5,
            cache_read_per_mtok: 0.2,
        };
    }

    // Opus 5.5 is priced below Opus 5 and 4.x; check the id before family.
    if lower.contains("claude-opus-5-5") {
        return ModelRate {
            input_per_mtok: 4.0,
            output_per_mtok: 20.0,
            cache_creation_per_mtok: 5.0,
            cache_read_per_mtok: 0.2,
        };
    }

    // Haiku: cheapest tier.
    if lower.contains("haiku") {
        return ModelRate {
            input_per_mtok: 1.0,
            output_per_mtok: 5.0,
            cache_creation_per_mtok: 1.25,
            cache_read_per_mtok: 0.1,
        };
    }

    // Sonnet: mid-tier.
    if lower.contains("sonnet") {
        return ModelRate {
            input_per_mtok: 3.0,
            output_per_mtok: 15.0,
            cache_creation_per_mtok: 3.75,
            cache_read_per_mtok: 0.3,
        };
    }

    if lower.contains("opus") {
        return opus_rate();
    }

    fallback_rate()
}

fn opus_rate() -> ModelRate {
    ModelRate {
        input_per_mtok: 5.0,
        output_per_mtok: 25.0,
        cache_creation_per_mtok: 6.25,
        cache_read_per_mtok: 0.5,
    }
}

fn fable_rate() -> ModelRate {
    ModelRate {
        input_per_mtok: 10.0,
        output_per_mtok: 50.0,
        cache_creation_per_mtok: 12.5,
        cache_read_per_mtok: 1.0,
    }
}

/// Conservative default when the model string is missing or unrecognized.
/// Uses fable rates — the most expensive public tier — so unknown models do
/// not silently underreport cost.
pub fn fallback_rate() -> ModelRate {
    fable_rate()
}
