//! Model pricing table for estimating session cost from raw token usage.
//!
//! The authoritative cost for a session is the `total_cost_usd` field
//! Anthropic writes into the `type:result` envelope at the end of a clean
//! run. Our code always prefers that value when it is present.
//!
//! When a session exits abnormally (watchdog abort, process kill, panic, any
//! `stop_reason` other than `end_turn`) the CLI never emits `type:result` and
//! `total_cost_usd` is absent. The `cc_sessions.cost_usd` row then records
//! `NULL` despite real token consumption — the exact pattern that made task
//! #81's worker-81-1 show `$0.00` for ~$3 of opus-4-7 time.
//!
//! This module fills that gap by estimating cost from per-message `usage`
//! fields that CC writes on every assistant turn regardless of how the
//! session ends. The rates live here; consumers pass a `Usage` total plus a
//! model string and get an estimated dollar figure.
//!
//! Accuracy caveat: the numbers here are best-effort estimates derived from
//! Anthropic's publicly posted per-million-token prices. They will drift as
//! pricing changes and may not reflect contracted rates. Always prefer the
//! authoritative `total_cost_usd` when it is available.

/// Per-million-token rates for a model, in USD.
///
/// The four fields mirror the four token buckets CC reports:
/// - `input` — non-cached input tokens on this turn.
/// - `output` — tokens generated by the model.
/// - `cache_creation` — tokens written to the prompt cache (1h or 5m ttl,
///   billed at a small premium over input).
/// - `cache_read` — tokens served from the prompt cache (billed at a deep
///   discount).
#[derive(Debug, Clone, Copy)]
pub struct ModelRate {
    pub input_per_mtok: f64,
    pub output_per_mtok: f64,
    pub cache_creation_per_mtok: f64,
    pub cache_read_per_mtok: f64,
}

impl ModelRate {
    /// Compute cost for one turn's raw token counts.
    pub fn cost_for(
        &self,
        input_tokens: u64,
        output_tokens: u64,
        cache_creation_tokens: u64,
        cache_read_tokens: u64,
    ) -> f64 {
        let million = 1_000_000.0;
        (input_tokens as f64) * self.input_per_mtok / million
            + (output_tokens as f64) * self.output_per_mtok / million
            + (cache_creation_tokens as f64) * self.cache_creation_per_mtok / million
            + (cache_read_tokens as f64) * self.cache_read_per_mtok / million
    }
}

/// Rate table keyed by model family. Unknown models fall back to
/// [`fallback_rate`], which uses opus rates on the principle that
/// overestimating cost is safer than silently hiding token spend.
pub fn rate_for_model(model: &str) -> ModelRate {
    // Match on a lowercased copy so CC's mixed casing across versions
    // (`claude-opus-4-7`, `claude-sonnet-4-6`) lands in the same bucket
    // regardless of source.
    let lower = model.to_ascii_lowercase();

    // Haiku: cheapest tier.
    if lower.contains("haiku") {
        return ModelRate {
            input_per_mtok: 1.0,
            output_per_mtok: 5.0,
            cache_creation_per_mtok: 1.25,
            cache_read_per_mtok: 0.1,
        };
    }

    // Sonnet: mid-tier.
    if lower.contains("sonnet") {
        return ModelRate {
            input_per_mtok: 3.0,
            output_per_mtok: 15.0,
            cache_creation_per_mtok: 3.75,
            cache_read_per_mtok: 0.3,
        };
    }

    // Opus: top-tier. Also the fallback for unknown models — see module
    // docstring for the overestimate-is-safer rationale.
    if lower.contains("opus") {
        return opus_rate();
    }

    fallback_rate()
}

fn opus_rate() -> ModelRate {
    ModelRate {
        input_per_mtok: 15.0,
        output_per_mtok: 75.0,
        cache_creation_per_mtok: 18.75,
        cache_read_per_mtok: 1.5,
    }
}

/// Conservative default when the model string is missing or unrecognized.
/// Uses opus rates so unknown models do not silently underreport cost.
pub fn fallback_rate() -> ModelRate {
    opus_rate()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn opus_rate_matches_public_pricing() {
        let rate = rate_for_model("claude-opus-4-7");
        assert!((rate.input_per_mtok - 15.0).abs() < 0.01);
        assert!((rate.output_per_mtok - 75.0).abs() < 0.01);
        assert!((rate.cache_read_per_mtok - 1.5).abs() < 0.01);
    }

    #[test]
    fn haiku_rate_is_lowest() {
        let rate = rate_for_model("claude-haiku-4-5");
        assert!(rate.input_per_mtok < rate_for_model("claude-sonnet-4-6").input_per_mtok);
        assert!(
            rate_for_model("claude-sonnet-4-6").input_per_mtok
                < rate_for_model("claude-opus-4-7").input_per_mtok
        );
    }

    #[test]
    fn cost_computation_adds_all_four_buckets() {
        let rate = ModelRate {
            input_per_mtok: 10.0,
            output_per_mtok: 20.0,
            cache_creation_per_mtok: 15.0,
            cache_read_per_mtok: 1.0,
        };
        // 1M input + 0.5M output + 0.1M cache-create + 2M cache-read
        let cost = rate.cost_for(1_000_000, 500_000, 100_000, 2_000_000);
        // 10 + 10 + 1.5 + 2 = 23.5
        assert!((cost - 23.5).abs() < 0.0001, "got {cost}");
    }

    #[test]
    fn case_insensitive_model_matching() {
        let lower = rate_for_model("claude-opus-4-7");
        let upper = rate_for_model("Claude-OPUS-4-7");
        assert!((lower.input_per_mtok - upper.input_per_mtok).abs() < 0.0001);
    }

    #[test]
    fn unknown_model_defaults_to_opus() {
        // Rationale: overestimating cost is safer than hiding token spend.
        let unknown = rate_for_model("some-future-model-2027");
        let opus = rate_for_model("claude-opus-4-7");
        assert!((unknown.input_per_mtok - opus.input_per_mtok).abs() < 0.0001);
    }

    #[test]
    fn empty_model_string_uses_fallback() {
        let rate = rate_for_model("");
        let fallback = fallback_rate();
        assert!((rate.input_per_mtok - fallback.input_per_mtok).abs() < 0.0001);
    }
}
